.TH "__iar_u32" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__iar_u32
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cmsis_iccarm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBv\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t __iar_u32::v"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
