.TH "ADC_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_TypeDef \- Analog to Digital Converter 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSMPR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSMPR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJOFR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJOFR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJOFR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJOFR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBHTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSQR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSQR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSQR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJSQR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJDR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJDR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJDR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBJDR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Analog to Digital Converter 
.br
 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t ADC_TypeDef::CR1"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::CR2"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::DR"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::HTR"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::JDR1"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::JDR2"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::JDR3"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::JDR4"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::JOFR1"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::JOFR2"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::JOFR3"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::JOFR4"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::JSQR"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::LTR"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::SMPR1"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::SMPR2"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::SQR1"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::SQR2"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::SQR3"

.SS "\fB__IO\fP uint32_t ADC_TypeDef::SR"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
