.TH "AFIO_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFIO_TypeDef \- Alternate Function I/O\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEVCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMAPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEXTICR\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMAPR2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Alternate Function I/O\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t AFIO_TypeDef::EVCR"

.SS "\fB__IO\fP uint32_t AFIO_TypeDef::EXTICR[4]"

.SS "\fB__IO\fP uint32_t AFIO_TypeDef::MAPR"

.SS "\fB__IO\fP uint32_t AFIO_TypeDef::MAPR2"

.SS "uint32_t AFIO_TypeDef::RESERVED0"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
