.TH "BKP_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BKP_TypeDef \- Backup Registers 
.br
  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR7\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR8\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR9\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR10\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRTCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Backup Registers 
.br
 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t BKP_TypeDef::CR"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::CSR"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR1"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR10"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR2"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR3"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR4"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR5"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR6"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR7"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR8"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::DR9"

.SS "uint32_t BKP_TypeDef::RESERVED0"

.SS "\fB__IO\fP uint32_t BKP_TypeDef::RTCCR"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
