.TH "Drivers/STM32F1xx_HAL_Driver/Src Directory Reference" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32F1xx_HAL_Driver/Src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBstm32f1xx_hal\&.c\fP"
.br
.RI "HAL module driver\&. This is the common part of the HAL initialization\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_cortex\&.c\fP"
.br
.RI "CORTEX HAL module driver\&. This file provides firmware functions to manage the following functionalities of the CORTEX: "
.ti -1c
.RI "file \fBstm32f1xx_hal_dma\&.c\fP"
.br
.RI "DMA HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Direct Memory Access (DMA) peripheral: "
.ti -1c
.RI "file \fBstm32f1xx_hal_exti\&.c\fP"
.br
.RI "EXTI HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Extended Interrupts and events controller (EXTI) peripheral: "
.ti -1c
.RI "file \fBstm32f1xx_hal_flash\&.c\fP"
.br
.RI "FLASH HAL module driver\&. This file provides firmware functions to manage the following functionalities of the internal FLASH memory: "
.ti -1c
.RI "file \fBstm32f1xx_hal_flash_ex\&.c\fP"
.br
.RI "Extended FLASH HAL module driver\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_gpio\&.c\fP"
.br
.RI "GPIO HAL module driver\&. This file provides firmware functions to manage the following functionalities of the General Purpose Input/Output (GPIO) peripheral: "
.ti -1c
.RI "file \fBstm32f1xx_hal_gpio_ex\&.c\fP"
.br
.RI "GPIO Extension HAL module driver\&. This file provides firmware functions to manage the following functionalities of the General Purpose Input/Output (GPIO) extension peripheral\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_pwr\&.c\fP"
.br
.RI "PWR HAL module driver\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_rcc\&.c\fP"
.br
.RI "RCC HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Reset and Clock Control (RCC) peripheral: "
.ti -1c
.RI "file \fBstm32f1xx_hal_rcc_ex\&.c\fP"
.br
.RI "Extended RCC HAL module driver\&. This file provides firmware functions to manage the following functionalities RCC extension peripheral: "
.ti -1c
.RI "file \fBstm32f1xx_hal_tim\&.c\fP"
.br
.RI "TIM HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Timer (TIM) peripheral: "
.ti -1c
.RI "file \fBstm32f1xx_hal_tim_ex\&.c\fP"
.br
.RI "TIM HAL module driver\&. This file provides firmware functions to manage the following functionalities of the Timer Extended peripheral: "
.in -1c
