.TH "Core/Inc Directory Reference" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlcd_display\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.RI ": Header for \fBmain\&.c\fP file\&. This file contains the common defines of the application\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_conf\&.h\fP"
.br
.RI "HAL configuration file\&. "
.ti -1c
.RI "file \fBstm32f1xx_it\&.h\fP"
.br
.RI "This file contains the headers of the interrupt handlers\&. "
.in -1c
