.TH "Drivers/STM32F1xx_HAL_Driver/Inc Directory Reference" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32F1xx_HAL_Driver/Inc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBLegacy\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBstm32f1xx_hal\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the HAL module driver\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_cortex\&.h\fP"
.br
.RI "Header file of CORTEX HAL module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_def\&.h\fP"
.br
.RI "This file contains HAL common defines, enumeration, macros and structures definitions\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_dma\&.h\fP"
.br
.RI "Header file of DMA HAL module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_dma_ex\&.h\fP"
.br
.RI "Header file of DMA HAL extension module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_exti\&.h\fP"
.br
.RI "Header file of EXTI HAL module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_flash\&.h\fP"
.br
.RI "Header file of Flash HAL module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_flash_ex\&.h\fP"
.br
.RI "Header file of Flash HAL Extended module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_gpio\&.h\fP"
.br
.RI "Header file of GPIO HAL module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_gpio_ex\&.h\fP"
.br
.RI "Header file of GPIO HAL Extension module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_pwr\&.h\fP"
.br
.RI "Header file of PWR HAL module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_rcc\&.h\fP"
.br
.RI "Header file of RCC HAL module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_rcc_ex\&.h\fP"
.br
.RI "Header file of RCC HAL Extension module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_tim\&.h\fP"
.br
.RI "Header file of TIM HAL module\&. "
.ti -1c
.RI "file \fBstm32f1xx_hal_tim_ex\&.h\fP"
.br
.RI "Header file of TIM HAL Extended module\&. "
.in -1c
