.TH "Channel_CC_State" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Channel_CC_State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CCx_ENABLE\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBTIM_CCx_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_CCxN_ENABLE\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBTIM_CCxN_DISABLE\fP   0x00000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_CCx_DISABLE   0x00000000U"
Input or output channel is disabled 
.SS "#define TIM_CCx_ENABLE   0x00000001U"
Input or output channel is enabled 
.SS "#define TIM_CCxN_DISABLE   0x00000000U"
Complementary output channel is enabled 
.SS "#define TIM_CCxN_ENABLE   0x00000004U"
Complementary output channel is enabled 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
