.TH "CMSIS_TPI" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_TPI \- Type definitions for the Trace Port Interface (TPI)  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCore Debug Registers (CoreDebug)\fP"
.br
.RI "Type definitions for the Core Debug Registers\&. "
.ti -1c
.RI "\fBFloating Point Unit (FPU)\fP"
.br
.RI "Type definitions for the Floating Point Unit (FPU) "
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTPI_Type\fP"
.br
.RI "Structure type to access the Trace Port Interface Register (TPI)\&. "
.in -1c
.in +1c
.ti -1c
.RI "#define \fBTPI_ACPR_SWOSCALER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_SWOSCALER_Msk\fP   (0xFFFFUL /*<< \fBTPI_ACPR_SWOSCALER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_FOnMan_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_FOnMan_Msk\fP   (0x1UL << \fBTPI_FFCR_FOnMan_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_PSCR_PSCount_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_PSCR_PSCount_Msk\fP   (0x1FUL /*<< \fBTPI_PSCR_PSCount_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_LSR_nTT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_LSR_nTT_Msk\fP   (0x1UL << \fBTPI_LSR_nTT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_LSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_LSR_SLK_Msk\fP   (0x1UL << \fBTPI_LSR_SLK_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_LSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_LSR_SLI_Msk\fP   (0x1UL /*<< \fBTPI_LSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_FIFOSZ_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_FIFOSZ_Msk\fP   (0x7UL << \fBTPI_DEVID_FIFOSZ_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBTPI_ACPR_SWOSCALER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_SWOSCALER_Msk\fP   (0xFFFFUL /*<< \fBTPI_ACPR_SWOSCALER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_FOnMan_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_FOnMan_Msk\fP   (0x1UL << \fBTPI_FFCR_FOnMan_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_PSCR_PSCount_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_PSCR_PSCount_Msk\fP   (0x1FUL /*<< \fBTPI_PSCR_PSCount_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_LSR_nTT_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_LSR_nTT_Msk\fP   (0x1UL << \fBTPI_LSR_nTT_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_LSR_SLK_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_LSR_SLK_Msk\fP   (0x1UL << \fBTPI_LSR_SLK_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_LSR_SLI_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_LSR_SLI_Msk\fP   (0x1UL /*<< \fBTPI_LSR_SLI_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_FIFOSZ_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_FIFOSZ_Msk\fP   (0x7UL << \fBTPI_DEVID_FIFOSZ_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Msk\fP   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_FOnMan_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_FOnMan_Msk\fP   (0x1UL << \fBTPI_FFCR_FOnMan_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Msk\fP   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF2_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF2_ATVALID_Msk\fP   (0x3UL << \fBTPI_ITFTTD0_ATB_IF2_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF2_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF2_bytecount_Msk\fP   (0x3UL << \fBTPI_ITFTTD0_ATB_IF2_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_ATVALID_Msk\fP   (0x3UL << \fBTPI_ITFTTD0_ATB_IF1_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_bytecount_Msk\fP   (0x3UL << \fBTPI_ITFTTD0_ATB_IF1_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data2_Msk\fP   (0xFFUL << \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data1_Msk\fP   (0xFFUL << \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data0_Msk\fP   (0xFFUL /*<< \fBTPI_ITFTTD0_ATB_IF1_data0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_AFVALID2S_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_AFVALID2S_Msk\fP   (0x1UL << \fBTPI_ITATBCTR2_AFVALID2S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_AFVALID1S_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_AFVALID1S_Msk\fP   (0x1UL << \fBTPI_ITATBCTR2_AFVALID1S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2S_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2S_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2S_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1S_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1S_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1S_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_ATVALID_Msk\fP   (0x3UL << \fBTPI_ITFTTD1_ATB_IF2_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_bytecount_Msk\fP   (0x3UL << \fBTPI_ITFTTD1_ATB_IF2_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF1_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF1_ATVALID_Msk\fP   (0x3UL << \fBTPI_ITFTTD1_ATB_IF1_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF1_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF1_bytecount_Msk\fP   (0x3UL << \fBTPI_ITFTTD1_ATB_IF1_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data2_Msk\fP   (0xFFUL << \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data1_Msk\fP   (0xFFUL << \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data0_Msk\fP   (0xFFUL /*<< \fBTPI_ITFTTD1_ATB_IF2_data0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_AFVALID2S_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_AFVALID2S_Msk\fP   (0x1UL << \fBTPI_ITATBCTR0_AFVALID2S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_AFVALID1S_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_AFVALID1S_Msk\fP   (0x1UL << \fBTPI_ITATBCTR0_AFVALID1S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2S_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2S_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2S_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1S_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1S_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1S_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Msk\fP   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_FIFOSZ_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_FIFOSZ_Msk\fP   (0x7UL << \fBTPI_DEVID_FIFOSZ_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Msk\fP   (0x3FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Msk\fP   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Msk\fP   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Msk\fP   (0xFFUL /*<< \fBTPI_FIFO0_ETM0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Msk\fP   (0xFFUL /*<< \fBTPI_FIFO1_ITM0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Msk\fP   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Msk\fP   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Msk\fP   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Msk\fP   (0x1FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Msk\fP   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_FOnMan_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_FOnMan_Msk\fP   (0x1UL << \fBTPI_FFCR_FOnMan_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Msk\fP   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF2_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF2_ATVALID_Msk\fP   (0x3UL << \fBTPI_ITFTTD0_ATB_IF2_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF2_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF2_bytecount_Msk\fP   (0x3UL << \fBTPI_ITFTTD0_ATB_IF2_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_ATVALID_Msk\fP   (0x3UL << \fBTPI_ITFTTD0_ATB_IF1_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_bytecount_Msk\fP   (0x3UL << \fBTPI_ITFTTD0_ATB_IF1_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data2_Msk\fP   (0xFFUL << \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data1_Msk\fP   (0xFFUL << \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD0_ATB_IF1_data0_Msk\fP   (0xFFUL /*<< \fBTPI_ITFTTD0_ATB_IF1_data0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_AFVALID2S_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_AFVALID2S_Msk\fP   (0x1UL << \fBTPI_ITATBCTR2_AFVALID2S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_AFVALID1S_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_AFVALID1S_Msk\fP   (0x1UL << \fBTPI_ITATBCTR2_AFVALID1S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2S_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2S_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2S_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1S_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1S_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1S_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_ATVALID_Msk\fP   (0x3UL << \fBTPI_ITFTTD1_ATB_IF2_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_bytecount_Msk\fP   (0x3UL << \fBTPI_ITFTTD1_ATB_IF2_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF1_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF1_ATVALID_Msk\fP   (0x3UL << \fBTPI_ITFTTD1_ATB_IF1_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF1_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF1_bytecount_Msk\fP   (0x3UL << \fBTPI_ITFTTD1_ATB_IF1_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data2_Msk\fP   (0xFFUL << \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data1_Msk\fP   (0xFFUL << \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITFTTD1_ATB_IF2_data0_Msk\fP   (0xFFUL /*<< \fBTPI_ITFTTD1_ATB_IF2_data0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_AFVALID2S_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_AFVALID2S_Msk\fP   (0x1UL << \fBTPI_ITATBCTR0_AFVALID2S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_AFVALID1S_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_AFVALID1S_Msk\fP   (0x1UL << \fBTPI_ITATBCTR0_AFVALID1S_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2S_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2S_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2S_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1S_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1S_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1S_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Msk\fP   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_FIFOSZ_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_FIFOSZ_Msk\fP   (0x7UL << \fBTPI_DEVID_FIFOSZ_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Msk\fP   (0x3FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Msk\fP   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Msk\fP   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Msk\fP   (0xFFUL /*<< \fBTPI_FIFO0_ETM0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Msk\fP   (0xFFUL /*<< \fBTPI_FIFO1_ITM0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Msk\fP   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Msk\fP   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Msk\fP   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Msk\fP   (0x1FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Msk\fP   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Msk\fP   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Msk\fP   (0xFFUL /*<< \fBTPI_FIFO0_ETM0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Msk\fP   (0xFFUL /*<< \fBTPI_FIFO1_ITM0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Msk\fP   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Msk\fP   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Msk\fP   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Msk\fP   (0x1FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
.br
.in -1c
.in +1c
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ACPR_PRESCALER_Msk\fP   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_SPPR_TXMODE_Msk\fP   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Pos\fP   3U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtNonStop_Msk\fP   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_TCPresent_Msk\fP   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FtStopped_Msk\fP   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FFSR_FlInProg_Msk\fP   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_TrigIn_Msk\fP   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBTPI_FFCR_EnFCont_Msk\fP   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_TRIGGER_TRIGGER_Msk\fP   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM2_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM1_Msk\fP   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO0_ETM0_Msk\fP   (0xFFUL /*<< \fBTPI_FIFO0_ETM0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY2_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR2_ATREADY1_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Pos\fP   29U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Pos\fP   27U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Pos\fP   26U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_ATVALID_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Pos\fP   24U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ETM_bytecount_Msk\fP   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Pos\fP   16U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM2_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM1_Msk\fP   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_FIFO1_ITM0_Msk\fP   (0xFFUL /*<< \fBTPI_FIFO1_ITM0_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY2_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITATBCTR0_ATREADY1_Msk\fP   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_ITCTRL_Mode_Msk\fP   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NRZVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MANCVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_PTINVALID_Msk\fP   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Pos\fP   6U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_MinBufSz_Msk\fP   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Pos\fP   5U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_AsynClkIn_Msk\fP   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVID_NrTraceInput_Msk\fP   (0x1FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Pos\fP   4U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_SubType_Msk\fP   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBTPI_DEVTYPE_MajorType_Msk\fP   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the Trace Port Interface (TPI) 


.SH "Macro Definition Documentation"
.PP 
.SS "#define TPI_ACPR_PRESCALER_Msk   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
TPI ACPR: PRESCALER Mask 
.SS "#define TPI_ACPR_PRESCALER_Msk   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
TPI ACPR: PRESCALER Mask 
.SS "#define TPI_ACPR_PRESCALER_Msk   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
TPI ACPR: PRESCALER Mask 
.SS "#define TPI_ACPR_PRESCALER_Msk   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
TPI ACPR: PRESCALER Mask 
.SS "#define TPI_ACPR_PRESCALER_Msk   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
TPI ACPR: PRESCALER Mask 
.SS "#define TPI_ACPR_PRESCALER_Msk   (0x1FFFUL /*<< \fBTPI_ACPR_PRESCALER_Pos\fP*/)"
TPI ACPR: PRESCALER Mask 
.SS "#define TPI_ACPR_PRESCALER_Pos   0U"
TPI ACPR: PRESCALER Position 
.SS "#define TPI_ACPR_PRESCALER_Pos   0U"
TPI ACPR: PRESCALER Position 
.SS "#define TPI_ACPR_PRESCALER_Pos   0U"
TPI ACPR: PRESCALER Position 
.SS "#define TPI_ACPR_PRESCALER_Pos   0U"
TPI ACPR: PRESCALER Position 
.SS "#define TPI_ACPR_PRESCALER_Pos   0U"
TPI ACPR: PRESCALER Position 
.SS "#define TPI_ACPR_PRESCALER_Pos   0U"
TPI ACPR: PRESCALER Position 
.SS "#define TPI_ACPR_SWOSCALER_Msk   (0xFFFFUL /*<< \fBTPI_ACPR_SWOSCALER_Pos\fP*/)"
TPI ACPR: SWOSCALER Mask 
.SS "#define TPI_ACPR_SWOSCALER_Msk   (0xFFFFUL /*<< \fBTPI_ACPR_SWOSCALER_Pos\fP*/)"
TPI ACPR: SWOSCALER Mask 
.SS "#define TPI_ACPR_SWOSCALER_Pos   0U"
TPI ACPR: SWOSCALER Position 
.SS "#define TPI_ACPR_SWOSCALER_Pos   0U"
TPI ACPR: SWOSCALER Position 
.SS "#define TPI_DEVID_AsynClkIn_Msk   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
TPI DEVID: AsynClkIn Mask 
.SS "#define TPI_DEVID_AsynClkIn_Msk   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
TPI DEVID: AsynClkIn Mask 
.SS "#define TPI_DEVID_AsynClkIn_Msk   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
TPI DEVID: AsynClkIn Mask 
.SS "#define TPI_DEVID_AsynClkIn_Msk   (0x1UL << \fBTPI_DEVID_AsynClkIn_Pos\fP)"
TPI DEVID: AsynClkIn Mask 
.SS "#define TPI_DEVID_AsynClkIn_Pos   5U"
TPI DEVID: AsynClkIn Position 
.SS "#define TPI_DEVID_AsynClkIn_Pos   5U"
TPI DEVID: AsynClkIn Position 
.SS "#define TPI_DEVID_AsynClkIn_Pos   5U"
TPI DEVID: AsynClkIn Position 
.SS "#define TPI_DEVID_AsynClkIn_Pos   5U"
TPI DEVID: AsynClkIn Position 
.SS "#define TPI_DEVID_FIFOSZ_Msk   (0x7UL << \fBTPI_DEVID_FIFOSZ_Pos\fP)"
TPI DEVID: FIFO depth Mask 
.SS "#define TPI_DEVID_FIFOSZ_Msk   (0x7UL << \fBTPI_DEVID_FIFOSZ_Pos\fP)"
TPI DEVID: FIFOSZ Mask 
.SS "#define TPI_DEVID_FIFOSZ_Msk   (0x7UL << \fBTPI_DEVID_FIFOSZ_Pos\fP)"
TPI DEVID: FIFO depth Mask 
.SS "#define TPI_DEVID_FIFOSZ_Msk   (0x7UL << \fBTPI_DEVID_FIFOSZ_Pos\fP)"
TPI DEVID: FIFOSZ Mask 
.SS "#define TPI_DEVID_FIFOSZ_Pos   6U"
TPI DEVID: FIFO depth Position 
.SS "#define TPI_DEVID_FIFOSZ_Pos   6U"
TPI DEVID: FIFOSZ Position 
.SS "#define TPI_DEVID_FIFOSZ_Pos   6U"
TPI DEVID: FIFO depth Position 
.SS "#define TPI_DEVID_FIFOSZ_Pos   6U"
TPI DEVID: FIFOSZ Position 
.SS "#define TPI_DEVID_MANCVALID_Msk   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
TPI DEVID: MANCVALID Mask 
.SS "#define TPI_DEVID_MANCVALID_Msk   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
TPI DEVID: MANCVALID Mask 
.SS "#define TPI_DEVID_MANCVALID_Msk   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
TPI DEVID: MANCVALID Mask 
.SS "#define TPI_DEVID_MANCVALID_Msk   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
TPI DEVID: MANCVALID Mask 
.SS "#define TPI_DEVID_MANCVALID_Msk   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
TPI DEVID: MANCVALID Mask 
.SS "#define TPI_DEVID_MANCVALID_Msk   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
TPI DEVID: MANCVALID Mask 
.SS "#define TPI_DEVID_MANCVALID_Msk   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
TPI DEVID: MANCVALID Mask 
.SS "#define TPI_DEVID_MANCVALID_Msk   (0x1UL << \fBTPI_DEVID_MANCVALID_Pos\fP)"
TPI DEVID: MANCVALID Mask 
.SS "#define TPI_DEVID_MANCVALID_Pos   10U"
TPI DEVID: MANCVALID Position 
.SS "#define TPI_DEVID_MANCVALID_Pos   10U"
TPI DEVID: MANCVALID Position 
.SS "#define TPI_DEVID_MANCVALID_Pos   10U"
TPI DEVID: MANCVALID Position 
.SS "#define TPI_DEVID_MANCVALID_Pos   10U"
TPI DEVID: MANCVALID Position 
.SS "#define TPI_DEVID_MANCVALID_Pos   10U"
TPI DEVID: MANCVALID Position 
.SS "#define TPI_DEVID_MANCVALID_Pos   10U"
TPI DEVID: MANCVALID Position 
.SS "#define TPI_DEVID_MANCVALID_Pos   10U"
TPI DEVID: MANCVALID Position 
.SS "#define TPI_DEVID_MANCVALID_Pos   10U"
TPI DEVID: MANCVALID Position 
.SS "#define TPI_DEVID_MinBufSz_Msk   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
TPI DEVID: MinBufSz Mask 
.SS "#define TPI_DEVID_MinBufSz_Msk   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
TPI DEVID: MinBufSz Mask 
.SS "#define TPI_DEVID_MinBufSz_Msk   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
TPI DEVID: MinBufSz Mask 
.SS "#define TPI_DEVID_MinBufSz_Msk   (0x7UL << \fBTPI_DEVID_MinBufSz_Pos\fP)"
TPI DEVID: MinBufSz Mask 
.SS "#define TPI_DEVID_MinBufSz_Pos   6U"
TPI DEVID: MinBufSz Position 
.SS "#define TPI_DEVID_MinBufSz_Pos   6U"
TPI DEVID: MinBufSz Position 
.SS "#define TPI_DEVID_MinBufSz_Pos   6U"
TPI DEVID: MinBufSz Position 
.SS "#define TPI_DEVID_MinBufSz_Pos   6U"
TPI DEVID: MinBufSz Position 
.SS "#define TPI_DEVID_NrTraceInput_Msk   (0x3FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
TPI DEVID: NrTraceInput Mask 
.SS "#define TPI_DEVID_NrTraceInput_Msk   (0x1FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
TPI DEVID: NrTraceInput Mask 
.SS "#define TPI_DEVID_NrTraceInput_Msk   (0x1FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
TPI DEVID: NrTraceInput Mask 
.SS "#define TPI_DEVID_NrTraceInput_Msk   (0x1FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
TPI DEVID: NrTraceInput Mask 
.SS "#define TPI_DEVID_NrTraceInput_Msk   (0x1FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
TPI DEVID: NrTraceInput Mask 
.SS "#define TPI_DEVID_NrTraceInput_Msk   (0x3FUL /*<< \fBTPI_DEVID_NrTraceInput_Pos\fP*/)"
TPI DEVID: NrTraceInput Mask 
.SS "#define TPI_DEVID_NrTraceInput_Pos   0U"
TPI DEVID: NrTraceInput Position 
.SS "#define TPI_DEVID_NrTraceInput_Pos   0U"
TPI DEVID: NrTraceInput Position 
.SS "#define TPI_DEVID_NrTraceInput_Pos   0U"
TPI DEVID: NrTraceInput Position 
.SS "#define TPI_DEVID_NrTraceInput_Pos   0U"
TPI DEVID: NrTraceInput Position 
.SS "#define TPI_DEVID_NrTraceInput_Pos   0U"
TPI DEVID: NrTraceInput Position 
.SS "#define TPI_DEVID_NrTraceInput_Pos   0U"
TPI DEVID: NrTraceInput Position 
.SS "#define TPI_DEVID_NRZVALID_Msk   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
TPI DEVID: NRZVALID Mask 
.SS "#define TPI_DEVID_NRZVALID_Msk   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
TPI DEVID: NRZVALID Mask 
.SS "#define TPI_DEVID_NRZVALID_Msk   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
TPI DEVID: NRZVALID Mask 
.SS "#define TPI_DEVID_NRZVALID_Msk   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
TPI DEVID: NRZVALID Mask 
.SS "#define TPI_DEVID_NRZVALID_Msk   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
TPI DEVID: NRZVALID Mask 
.SS "#define TPI_DEVID_NRZVALID_Msk   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
TPI DEVID: NRZVALID Mask 
.SS "#define TPI_DEVID_NRZVALID_Msk   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
TPI DEVID: NRZVALID Mask 
.SS "#define TPI_DEVID_NRZVALID_Msk   (0x1UL << \fBTPI_DEVID_NRZVALID_Pos\fP)"
TPI DEVID: NRZVALID Mask 
.SS "#define TPI_DEVID_NRZVALID_Pos   11U"
TPI DEVID: NRZVALID Position 
.SS "#define TPI_DEVID_NRZVALID_Pos   11U"
TPI DEVID: NRZVALID Position 
.SS "#define TPI_DEVID_NRZVALID_Pos   11U"
TPI DEVID: NRZVALID Position 
.SS "#define TPI_DEVID_NRZVALID_Pos   11U"
TPI DEVID: NRZVALID Position 
.SS "#define TPI_DEVID_NRZVALID_Pos   11U"
TPI DEVID: NRZVALID Position 
.SS "#define TPI_DEVID_NRZVALID_Pos   11U"
TPI DEVID: NRZVALID Position 
.SS "#define TPI_DEVID_NRZVALID_Pos   11U"
TPI DEVID: NRZVALID Position 
.SS "#define TPI_DEVID_NRZVALID_Pos   11U"
TPI DEVID: NRZVALID Position 
.SS "#define TPI_DEVID_PTINVALID_Msk   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
TPI DEVID: PTINVALID Mask 
.SS "#define TPI_DEVID_PTINVALID_Msk   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
TPI DEVID: PTINVALID Mask 
.SS "#define TPI_DEVID_PTINVALID_Msk   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
TPI DEVID: PTINVALID Mask 
.SS "#define TPI_DEVID_PTINVALID_Msk   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
TPI DEVID: PTINVALID Mask 
.SS "#define TPI_DEVID_PTINVALID_Msk   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
TPI DEVID: PTINVALID Mask 
.SS "#define TPI_DEVID_PTINVALID_Msk   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
TPI DEVID: PTINVALID Mask 
.SS "#define TPI_DEVID_PTINVALID_Msk   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
TPI DEVID: PTINVALID Mask 
.SS "#define TPI_DEVID_PTINVALID_Msk   (0x1UL << \fBTPI_DEVID_PTINVALID_Pos\fP)"
TPI DEVID: PTINVALID Mask 
.SS "#define TPI_DEVID_PTINVALID_Pos   9U"
TPI DEVID: PTINVALID Position 
.SS "#define TPI_DEVID_PTINVALID_Pos   9U"
TPI DEVID: PTINVALID Position 
.SS "#define TPI_DEVID_PTINVALID_Pos   9U"
TPI DEVID: PTINVALID Position 
.SS "#define TPI_DEVID_PTINVALID_Pos   9U"
TPI DEVID: PTINVALID Position 
.SS "#define TPI_DEVID_PTINVALID_Pos   9U"
TPI DEVID: PTINVALID Position 
.SS "#define TPI_DEVID_PTINVALID_Pos   9U"
TPI DEVID: PTINVALID Position 
.SS "#define TPI_DEVID_PTINVALID_Pos   9U"
TPI DEVID: PTINVALID Position 
.SS "#define TPI_DEVID_PTINVALID_Pos   9U"
TPI DEVID: PTINVALID Position 
.SS "#define TPI_DEVTYPE_MajorType_Msk   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
TPI DEVTYPE: MajorType Mask 
.SS "#define TPI_DEVTYPE_MajorType_Msk   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
TPI DEVTYPE: MajorType Mask 
.SS "#define TPI_DEVTYPE_MajorType_Msk   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
TPI DEVTYPE: MajorType Mask 
.SS "#define TPI_DEVTYPE_MajorType_Msk   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
TPI DEVTYPE: MajorType Mask 
.SS "#define TPI_DEVTYPE_MajorType_Msk   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
TPI DEVTYPE: MajorType Mask 
.SS "#define TPI_DEVTYPE_MajorType_Msk   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
TPI DEVTYPE: MajorType Mask 
.SS "#define TPI_DEVTYPE_MajorType_Msk   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
TPI DEVTYPE: MajorType Mask 
.SS "#define TPI_DEVTYPE_MajorType_Msk   (0xFUL << \fBTPI_DEVTYPE_MajorType_Pos\fP)"
TPI DEVTYPE: MajorType Mask 
.SS "#define TPI_DEVTYPE_MajorType_Pos   0U"
TPI DEVTYPE: MajorType Position 
.SS "#define TPI_DEVTYPE_MajorType_Pos   0U"
TPI DEVTYPE: MajorType Position 
.SS "#define TPI_DEVTYPE_MajorType_Pos   0U"
TPI DEVTYPE: MajorType Position 
.SS "#define TPI_DEVTYPE_MajorType_Pos   0U"
TPI DEVTYPE: MajorType Position 
.SS "#define TPI_DEVTYPE_MajorType_Pos   0U"
TPI DEVTYPE: MajorType Position 
.SS "#define TPI_DEVTYPE_MajorType_Pos   0U"
TPI DEVTYPE: MajorType Position 
.SS "#define TPI_DEVTYPE_MajorType_Pos   0U"
TPI DEVTYPE: MajorType Position 
.SS "#define TPI_DEVTYPE_MajorType_Pos   0U"
TPI DEVTYPE: MajorType Position 
.SS "#define TPI_DEVTYPE_SubType_Msk   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
TPI DEVTYPE: SubType Mask 
.SS "#define TPI_DEVTYPE_SubType_Msk   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
TPI DEVTYPE: SubType Mask 
.SS "#define TPI_DEVTYPE_SubType_Msk   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
TPI DEVTYPE: SubType Mask 
.SS "#define TPI_DEVTYPE_SubType_Msk   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
TPI DEVTYPE: SubType Mask 
.SS "#define TPI_DEVTYPE_SubType_Msk   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
TPI DEVTYPE: SubType Mask 
.SS "#define TPI_DEVTYPE_SubType_Msk   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
TPI DEVTYPE: SubType Mask 
.SS "#define TPI_DEVTYPE_SubType_Msk   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
TPI DEVTYPE: SubType Mask 
.SS "#define TPI_DEVTYPE_SubType_Msk   (0xFUL /*<< \fBTPI_DEVTYPE_SubType_Pos\fP*/)"
TPI DEVTYPE: SubType Mask 
.SS "#define TPI_DEVTYPE_SubType_Pos   4U"
TPI DEVTYPE: SubType Position 
.SS "#define TPI_DEVTYPE_SubType_Pos   4U"
TPI DEVTYPE: SubType Position 
.SS "#define TPI_DEVTYPE_SubType_Pos   4U"
TPI DEVTYPE: SubType Position 
.SS "#define TPI_DEVTYPE_SubType_Pos   4U"
TPI DEVTYPE: SubType Position 
.SS "#define TPI_DEVTYPE_SubType_Pos   4U"
TPI DEVTYPE: SubType Position 
.SS "#define TPI_DEVTYPE_SubType_Pos   4U"
TPI DEVTYPE: SubType Position 
.SS "#define TPI_DEVTYPE_SubType_Pos   4U"
TPI DEVTYPE: SubType Position 
.SS "#define TPI_DEVTYPE_SubType_Pos   4U"
TPI DEVTYPE: SubType Position 
.SS "#define TPI_FFCR_EnFCont_Msk   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
TPI FFCR: EnFCont Mask 
.SS "#define TPI_FFCR_EnFCont_Msk   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
TPI FFCR: EnFCont Mask 
.SS "#define TPI_FFCR_EnFCont_Msk   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
TPI FFCR: EnFCont Mask 
.SS "#define TPI_FFCR_EnFCont_Msk   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
TPI FFCR: EnFCont Mask 
.SS "#define TPI_FFCR_EnFCont_Msk   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
TPI FFCR: EnFCont Mask 
.SS "#define TPI_FFCR_EnFCont_Msk   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
TPI FFCR: EnFCont Mask 
.SS "#define TPI_FFCR_EnFCont_Msk   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
TPI FFCR: EnFCont Mask 
.SS "#define TPI_FFCR_EnFCont_Msk   (0x1UL << \fBTPI_FFCR_EnFCont_Pos\fP)"
TPI FFCR: EnFCont Mask 
.SS "#define TPI_FFCR_EnFCont_Pos   1U"
TPI FFCR: EnFCont Position 
.SS "#define TPI_FFCR_EnFCont_Pos   1U"
TPI FFCR: EnFCont Position 
.SS "#define TPI_FFCR_EnFCont_Pos   1U"
TPI FFCR: EnFCont Position 
.SS "#define TPI_FFCR_EnFCont_Pos   1U"
TPI FFCR: EnFCont Position 
.SS "#define TPI_FFCR_EnFCont_Pos   1U"
TPI FFCR: EnFCont Position 
.SS "#define TPI_FFCR_EnFCont_Pos   1U"
TPI FFCR: EnFCont Position 
.SS "#define TPI_FFCR_EnFCont_Pos   1U"
TPI FFCR: EnFCont Position 
.SS "#define TPI_FFCR_EnFCont_Pos   1U"
TPI FFCR: EnFCont Position 
.SS "#define TPI_FFCR_FOnMan_Msk   (0x1UL << \fBTPI_FFCR_FOnMan_Pos\fP)"
TPI FFCR: FOnMan Mask 
.SS "#define TPI_FFCR_FOnMan_Msk   (0x1UL << \fBTPI_FFCR_FOnMan_Pos\fP)"
TPI FFCR: FOnMan Mask 
.SS "#define TPI_FFCR_FOnMan_Msk   (0x1UL << \fBTPI_FFCR_FOnMan_Pos\fP)"
TPI FFCR: FOnMan Mask 
.SS "#define TPI_FFCR_FOnMan_Msk   (0x1UL << \fBTPI_FFCR_FOnMan_Pos\fP)"
TPI FFCR: FOnMan Mask 
.SS "#define TPI_FFCR_FOnMan_Pos   6U"
TPI FFCR: FOnMan Position 
.SS "#define TPI_FFCR_FOnMan_Pos   6U"
TPI FFCR: FOnMan Position 
.SS "#define TPI_FFCR_FOnMan_Pos   6U"
TPI FFCR: FOnMan Position 
.SS "#define TPI_FFCR_FOnMan_Pos   6U"
TPI FFCR: FOnMan Position 
.SS "#define TPI_FFCR_TrigIn_Msk   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
TPI FFCR: TrigIn Mask 
.SS "#define TPI_FFCR_TrigIn_Msk   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
TPI FFCR: TrigIn Mask 
.SS "#define TPI_FFCR_TrigIn_Msk   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
TPI FFCR: TrigIn Mask 
.SS "#define TPI_FFCR_TrigIn_Msk   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
TPI FFCR: TrigIn Mask 
.SS "#define TPI_FFCR_TrigIn_Msk   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
TPI FFCR: TrigIn Mask 
.SS "#define TPI_FFCR_TrigIn_Msk   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
TPI FFCR: TrigIn Mask 
.SS "#define TPI_FFCR_TrigIn_Msk   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
TPI FFCR: TrigIn Mask 
.SS "#define TPI_FFCR_TrigIn_Msk   (0x1UL << \fBTPI_FFCR_TrigIn_Pos\fP)"
TPI FFCR: TrigIn Mask 
.SS "#define TPI_FFCR_TrigIn_Pos   8U"
TPI FFCR: TrigIn Position 
.SS "#define TPI_FFCR_TrigIn_Pos   8U"
TPI FFCR: TrigIn Position 
.SS "#define TPI_FFCR_TrigIn_Pos   8U"
TPI FFCR: TrigIn Position 
.SS "#define TPI_FFCR_TrigIn_Pos   8U"
TPI FFCR: TrigIn Position 
.SS "#define TPI_FFCR_TrigIn_Pos   8U"
TPI FFCR: TrigIn Position 
.SS "#define TPI_FFCR_TrigIn_Pos   8U"
TPI FFCR: TrigIn Position 
.SS "#define TPI_FFCR_TrigIn_Pos   8U"
TPI FFCR: TrigIn Position 
.SS "#define TPI_FFCR_TrigIn_Pos   8U"
TPI FFCR: TrigIn Position 
.SS "#define TPI_FFSR_FlInProg_Msk   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
TPI FFSR: FlInProg Mask 
.SS "#define TPI_FFSR_FlInProg_Msk   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
TPI FFSR: FlInProg Mask 
.SS "#define TPI_FFSR_FlInProg_Msk   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
TPI FFSR: FlInProg Mask 
.SS "#define TPI_FFSR_FlInProg_Msk   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
TPI FFSR: FlInProg Mask 
.SS "#define TPI_FFSR_FlInProg_Msk   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
TPI FFSR: FlInProg Mask 
.SS "#define TPI_FFSR_FlInProg_Msk   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
TPI FFSR: FlInProg Mask 
.SS "#define TPI_FFSR_FlInProg_Msk   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
TPI FFSR: FlInProg Mask 
.SS "#define TPI_FFSR_FlInProg_Msk   (0x1UL /*<< \fBTPI_FFSR_FlInProg_Pos\fP*/)"
TPI FFSR: FlInProg Mask 
.SS "#define TPI_FFSR_FlInProg_Pos   0U"
TPI FFSR: FlInProg Position 
.SS "#define TPI_FFSR_FlInProg_Pos   0U"
TPI FFSR: FlInProg Position 
.SS "#define TPI_FFSR_FlInProg_Pos   0U"
TPI FFSR: FlInProg Position 
.SS "#define TPI_FFSR_FlInProg_Pos   0U"
TPI FFSR: FlInProg Position 
.SS "#define TPI_FFSR_FlInProg_Pos   0U"
TPI FFSR: FlInProg Position 
.SS "#define TPI_FFSR_FlInProg_Pos   0U"
TPI FFSR: FlInProg Position 
.SS "#define TPI_FFSR_FlInProg_Pos   0U"
TPI FFSR: FlInProg Position 
.SS "#define TPI_FFSR_FlInProg_Pos   0U"
TPI FFSR: FlInProg Position 
.SS "#define TPI_FFSR_FtNonStop_Msk   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
TPI FFSR: FtNonStop Mask 
.SS "#define TPI_FFSR_FtNonStop_Msk   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
TPI FFSR: FtNonStop Mask 
.SS "#define TPI_FFSR_FtNonStop_Msk   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
TPI FFSR: FtNonStop Mask 
.SS "#define TPI_FFSR_FtNonStop_Msk   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
TPI FFSR: FtNonStop Mask 
.SS "#define TPI_FFSR_FtNonStop_Msk   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
TPI FFSR: FtNonStop Mask 
.SS "#define TPI_FFSR_FtNonStop_Msk   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
TPI FFSR: FtNonStop Mask 
.SS "#define TPI_FFSR_FtNonStop_Msk   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
TPI FFSR: FtNonStop Mask 
.SS "#define TPI_FFSR_FtNonStop_Msk   (0x1UL << \fBTPI_FFSR_FtNonStop_Pos\fP)"
TPI FFSR: FtNonStop Mask 
.SS "#define TPI_FFSR_FtNonStop_Pos   3U"
TPI FFSR: FtNonStop Position 
.SS "#define TPI_FFSR_FtNonStop_Pos   3U"
TPI FFSR: FtNonStop Position 
.SS "#define TPI_FFSR_FtNonStop_Pos   3U"
TPI FFSR: FtNonStop Position 
.SS "#define TPI_FFSR_FtNonStop_Pos   3U"
TPI FFSR: FtNonStop Position 
.SS "#define TPI_FFSR_FtNonStop_Pos   3U"
TPI FFSR: FtNonStop Position 
.SS "#define TPI_FFSR_FtNonStop_Pos   3U"
TPI FFSR: FtNonStop Position 
.SS "#define TPI_FFSR_FtNonStop_Pos   3U"
TPI FFSR: FtNonStop Position 
.SS "#define TPI_FFSR_FtNonStop_Pos   3U"
TPI FFSR: FtNonStop Position 
.SS "#define TPI_FFSR_FtStopped_Msk   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
TPI FFSR: FtStopped Mask 
.SS "#define TPI_FFSR_FtStopped_Msk   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
TPI FFSR: FtStopped Mask 
.SS "#define TPI_FFSR_FtStopped_Msk   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
TPI FFSR: FtStopped Mask 
.SS "#define TPI_FFSR_FtStopped_Msk   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
TPI FFSR: FtStopped Mask 
.SS "#define TPI_FFSR_FtStopped_Msk   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
TPI FFSR: FtStopped Mask 
.SS "#define TPI_FFSR_FtStopped_Msk   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
TPI FFSR: FtStopped Mask 
.SS "#define TPI_FFSR_FtStopped_Msk   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
TPI FFSR: FtStopped Mask 
.SS "#define TPI_FFSR_FtStopped_Msk   (0x1UL << \fBTPI_FFSR_FtStopped_Pos\fP)"
TPI FFSR: FtStopped Mask 
.SS "#define TPI_FFSR_FtStopped_Pos   1U"
TPI FFSR: FtStopped Position 
.SS "#define TPI_FFSR_FtStopped_Pos   1U"
TPI FFSR: FtStopped Position 
.SS "#define TPI_FFSR_FtStopped_Pos   1U"
TPI FFSR: FtStopped Position 
.SS "#define TPI_FFSR_FtStopped_Pos   1U"
TPI FFSR: FtStopped Position 
.SS "#define TPI_FFSR_FtStopped_Pos   1U"
TPI FFSR: FtStopped Position 
.SS "#define TPI_FFSR_FtStopped_Pos   1U"
TPI FFSR: FtStopped Position 
.SS "#define TPI_FFSR_FtStopped_Pos   1U"
TPI FFSR: FtStopped Position 
.SS "#define TPI_FFSR_FtStopped_Pos   1U"
TPI FFSR: FtStopped Position 
.SS "#define TPI_FFSR_TCPresent_Msk   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
TPI FFSR: TCPresent Mask 
.SS "#define TPI_FFSR_TCPresent_Msk   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
TPI FFSR: TCPresent Mask 
.SS "#define TPI_FFSR_TCPresent_Msk   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
TPI FFSR: TCPresent Mask 
.SS "#define TPI_FFSR_TCPresent_Msk   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
TPI FFSR: TCPresent Mask 
.SS "#define TPI_FFSR_TCPresent_Msk   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
TPI FFSR: TCPresent Mask 
.SS "#define TPI_FFSR_TCPresent_Msk   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
TPI FFSR: TCPresent Mask 
.SS "#define TPI_FFSR_TCPresent_Msk   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
TPI FFSR: TCPresent Mask 
.SS "#define TPI_FFSR_TCPresent_Msk   (0x1UL << \fBTPI_FFSR_TCPresent_Pos\fP)"
TPI FFSR: TCPresent Mask 
.SS "#define TPI_FFSR_TCPresent_Pos   2U"
TPI FFSR: TCPresent Position 
.SS "#define TPI_FFSR_TCPresent_Pos   2U"
TPI FFSR: TCPresent Position 
.SS "#define TPI_FFSR_TCPresent_Pos   2U"
TPI FFSR: TCPresent Position 
.SS "#define TPI_FFSR_TCPresent_Pos   2U"
TPI FFSR: TCPresent Position 
.SS "#define TPI_FFSR_TCPresent_Pos   2U"
TPI FFSR: TCPresent Position 
.SS "#define TPI_FFSR_TCPresent_Pos   2U"
TPI FFSR: TCPresent Position 
.SS "#define TPI_FFSR_TCPresent_Pos   2U"
TPI FFSR: TCPresent Position 
.SS "#define TPI_FFSR_TCPresent_Pos   2U"
TPI FFSR: TCPresent Position 
.SS "#define TPI_FIFO0_ETM0_Msk   (0xFFUL /*<< \fBTPI_FIFO0_ETM0_Pos\fP*/)"
TPI FIFO0: ETM0 Mask 
.SS "#define TPI_FIFO0_ETM0_Msk   (0xFFUL /*<< \fBTPI_FIFO0_ETM0_Pos\fP*/)"
TPI FIFO0: ETM0 Mask 
.SS "#define TPI_FIFO0_ETM0_Msk   (0xFFUL /*<< \fBTPI_FIFO0_ETM0_Pos\fP*/)"
TPI FIFO0: ETM0 Mask 
.SS "#define TPI_FIFO0_ETM0_Msk   (0xFFUL /*<< \fBTPI_FIFO0_ETM0_Pos\fP*/)"
TPI FIFO0: ETM0 Mask 
.SS "#define TPI_FIFO0_ETM0_Pos   0U"
TPI FIFO0: ETM0 Position 
.SS "#define TPI_FIFO0_ETM0_Pos   0U"
TPI FIFO0: ETM0 Position 
.SS "#define TPI_FIFO0_ETM0_Pos   0U"
TPI FIFO0: ETM0 Position 
.SS "#define TPI_FIFO0_ETM0_Pos   0U"
TPI FIFO0: ETM0 Position 
.SS "#define TPI_FIFO0_ETM1_Msk   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
TPI FIFO0: ETM1 Mask 
.SS "#define TPI_FIFO0_ETM1_Msk   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
TPI FIFO0: ETM1 Mask 
.SS "#define TPI_FIFO0_ETM1_Msk   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
TPI FIFO0: ETM1 Mask 
.SS "#define TPI_FIFO0_ETM1_Msk   (0xFFUL << \fBTPI_FIFO0_ETM1_Pos\fP)"
TPI FIFO0: ETM1 Mask 
.SS "#define TPI_FIFO0_ETM1_Pos   8U"
TPI FIFO0: ETM1 Position 
.SS "#define TPI_FIFO0_ETM1_Pos   8U"
TPI FIFO0: ETM1 Position 
.SS "#define TPI_FIFO0_ETM1_Pos   8U"
TPI FIFO0: ETM1 Position 
.SS "#define TPI_FIFO0_ETM1_Pos   8U"
TPI FIFO0: ETM1 Position 
.SS "#define TPI_FIFO0_ETM2_Msk   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
TPI FIFO0: ETM2 Mask 
.SS "#define TPI_FIFO0_ETM2_Msk   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
TPI FIFO0: ETM2 Mask 
.SS "#define TPI_FIFO0_ETM2_Msk   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
TPI FIFO0: ETM2 Mask 
.SS "#define TPI_FIFO0_ETM2_Msk   (0xFFUL << \fBTPI_FIFO0_ETM2_Pos\fP)"
TPI FIFO0: ETM2 Mask 
.SS "#define TPI_FIFO0_ETM2_Pos   16U"
TPI FIFO0: ETM2 Position 
.SS "#define TPI_FIFO0_ETM2_Pos   16U"
TPI FIFO0: ETM2 Position 
.SS "#define TPI_FIFO0_ETM2_Pos   16U"
TPI FIFO0: ETM2 Position 
.SS "#define TPI_FIFO0_ETM2_Pos   16U"
TPI FIFO0: ETM2 Position 
.SS "#define TPI_FIFO0_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
TPI FIFO0: ETM_ATVALID Mask 
.SS "#define TPI_FIFO0_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
TPI FIFO0: ETM_ATVALID Mask 
.SS "#define TPI_FIFO0_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
TPI FIFO0: ETM_ATVALID Mask 
.SS "#define TPI_FIFO0_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ETM_ATVALID_Pos\fP)"
TPI FIFO0: ETM_ATVALID Mask 
.SS "#define TPI_FIFO0_ETM_ATVALID_Pos   26U"
TPI FIFO0: ETM_ATVALID Position 
.SS "#define TPI_FIFO0_ETM_ATVALID_Pos   26U"
TPI FIFO0: ETM_ATVALID Position 
.SS "#define TPI_FIFO0_ETM_ATVALID_Pos   26U"
TPI FIFO0: ETM_ATVALID Position 
.SS "#define TPI_FIFO0_ETM_ATVALID_Pos   26U"
TPI FIFO0: ETM_ATVALID Position 
.SS "#define TPI_FIFO0_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
TPI FIFO0: ETM_bytecount Mask 
.SS "#define TPI_FIFO0_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
TPI FIFO0: ETM_bytecount Mask 
.SS "#define TPI_FIFO0_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
TPI FIFO0: ETM_bytecount Mask 
.SS "#define TPI_FIFO0_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ETM_bytecount_Pos\fP)"
TPI FIFO0: ETM_bytecount Mask 
.SS "#define TPI_FIFO0_ETM_bytecount_Pos   24U"
TPI FIFO0: ETM_bytecount Position 
.SS "#define TPI_FIFO0_ETM_bytecount_Pos   24U"
TPI FIFO0: ETM_bytecount Position 
.SS "#define TPI_FIFO0_ETM_bytecount_Pos   24U"
TPI FIFO0: ETM_bytecount Position 
.SS "#define TPI_FIFO0_ETM_bytecount_Pos   24U"
TPI FIFO0: ETM_bytecount Position 
.SS "#define TPI_FIFO0_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
TPI FIFO0: ITM_ATVALID Mask 
.SS "#define TPI_FIFO0_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
TPI FIFO0: ITM_ATVALID Mask 
.SS "#define TPI_FIFO0_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
TPI FIFO0: ITM_ATVALID Mask 
.SS "#define TPI_FIFO0_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO0_ITM_ATVALID_Pos\fP)"
TPI FIFO0: ITM_ATVALID Mask 
.SS "#define TPI_FIFO0_ITM_ATVALID_Pos   29U"
TPI FIFO0: ITM_ATVALID Position 
.SS "#define TPI_FIFO0_ITM_ATVALID_Pos   29U"
TPI FIFO0: ITM_ATVALID Position 
.SS "#define TPI_FIFO0_ITM_ATVALID_Pos   29U"
TPI FIFO0: ITM_ATVALID Position 
.SS "#define TPI_FIFO0_ITM_ATVALID_Pos   29U"
TPI FIFO0: ITM_ATVALID Position 
.SS "#define TPI_FIFO0_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
TPI FIFO0: ITM_bytecount Mask 
.SS "#define TPI_FIFO0_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
TPI FIFO0: ITM_bytecount Mask 
.SS "#define TPI_FIFO0_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
TPI FIFO0: ITM_bytecount Mask 
.SS "#define TPI_FIFO0_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO0_ITM_bytecount_Pos\fP)"
TPI FIFO0: ITM_bytecount Mask 
.SS "#define TPI_FIFO0_ITM_bytecount_Pos   27U"
TPI FIFO0: ITM_bytecount Position 
.SS "#define TPI_FIFO0_ITM_bytecount_Pos   27U"
TPI FIFO0: ITM_bytecount Position 
.SS "#define TPI_FIFO0_ITM_bytecount_Pos   27U"
TPI FIFO0: ITM_bytecount Position 
.SS "#define TPI_FIFO0_ITM_bytecount_Pos   27U"
TPI FIFO0: ITM_bytecount Position 
.SS "#define TPI_FIFO1_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
TPI FIFO1: ETM_ATVALID Mask 
.SS "#define TPI_FIFO1_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
TPI FIFO1: ETM_ATVALID Mask 
.SS "#define TPI_FIFO1_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
TPI FIFO1: ETM_ATVALID Mask 
.SS "#define TPI_FIFO1_ETM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ETM_ATVALID_Pos\fP)"
TPI FIFO1: ETM_ATVALID Mask 
.SS "#define TPI_FIFO1_ETM_ATVALID_Pos   26U"
TPI FIFO1: ETM_ATVALID Position 
.SS "#define TPI_FIFO1_ETM_ATVALID_Pos   26U"
TPI FIFO1: ETM_ATVALID Position 
.SS "#define TPI_FIFO1_ETM_ATVALID_Pos   26U"
TPI FIFO1: ETM_ATVALID Position 
.SS "#define TPI_FIFO1_ETM_ATVALID_Pos   26U"
TPI FIFO1: ETM_ATVALID Position 
.SS "#define TPI_FIFO1_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
TPI FIFO1: ETM_bytecount Mask 
.SS "#define TPI_FIFO1_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
TPI FIFO1: ETM_bytecount Mask 
.SS "#define TPI_FIFO1_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
TPI FIFO1: ETM_bytecount Mask 
.SS "#define TPI_FIFO1_ETM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ETM_bytecount_Pos\fP)"
TPI FIFO1: ETM_bytecount Mask 
.SS "#define TPI_FIFO1_ETM_bytecount_Pos   24U"
TPI FIFO1: ETM_bytecount Position 
.SS "#define TPI_FIFO1_ETM_bytecount_Pos   24U"
TPI FIFO1: ETM_bytecount Position 
.SS "#define TPI_FIFO1_ETM_bytecount_Pos   24U"
TPI FIFO1: ETM_bytecount Position 
.SS "#define TPI_FIFO1_ETM_bytecount_Pos   24U"
TPI FIFO1: ETM_bytecount Position 
.SS "#define TPI_FIFO1_ITM0_Msk   (0xFFUL /*<< \fBTPI_FIFO1_ITM0_Pos\fP*/)"
TPI FIFO1: ITM0 Mask 
.SS "#define TPI_FIFO1_ITM0_Msk   (0xFFUL /*<< \fBTPI_FIFO1_ITM0_Pos\fP*/)"
TPI FIFO1: ITM0 Mask 
.SS "#define TPI_FIFO1_ITM0_Msk   (0xFFUL /*<< \fBTPI_FIFO1_ITM0_Pos\fP*/)"
TPI FIFO1: ITM0 Mask 
.SS "#define TPI_FIFO1_ITM0_Msk   (0xFFUL /*<< \fBTPI_FIFO1_ITM0_Pos\fP*/)"
TPI FIFO1: ITM0 Mask 
.SS "#define TPI_FIFO1_ITM0_Pos   0U"
TPI FIFO1: ITM0 Position 
.SS "#define TPI_FIFO1_ITM0_Pos   0U"
TPI FIFO1: ITM0 Position 
.SS "#define TPI_FIFO1_ITM0_Pos   0U"
TPI FIFO1: ITM0 Position 
.SS "#define TPI_FIFO1_ITM0_Pos   0U"
TPI FIFO1: ITM0 Position 
.SS "#define TPI_FIFO1_ITM1_Msk   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
TPI FIFO1: ITM1 Mask 
.SS "#define TPI_FIFO1_ITM1_Msk   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
TPI FIFO1: ITM1 Mask 
.SS "#define TPI_FIFO1_ITM1_Msk   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
TPI FIFO1: ITM1 Mask 
.SS "#define TPI_FIFO1_ITM1_Msk   (0xFFUL << \fBTPI_FIFO1_ITM1_Pos\fP)"
TPI FIFO1: ITM1 Mask 
.SS "#define TPI_FIFO1_ITM1_Pos   8U"
TPI FIFO1: ITM1 Position 
.SS "#define TPI_FIFO1_ITM1_Pos   8U"
TPI FIFO1: ITM1 Position 
.SS "#define TPI_FIFO1_ITM1_Pos   8U"
TPI FIFO1: ITM1 Position 
.SS "#define TPI_FIFO1_ITM1_Pos   8U"
TPI FIFO1: ITM1 Position 
.SS "#define TPI_FIFO1_ITM2_Msk   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
TPI FIFO1: ITM2 Mask 
.SS "#define TPI_FIFO1_ITM2_Msk   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
TPI FIFO1: ITM2 Mask 
.SS "#define TPI_FIFO1_ITM2_Msk   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
TPI FIFO1: ITM2 Mask 
.SS "#define TPI_FIFO1_ITM2_Msk   (0xFFUL << \fBTPI_FIFO1_ITM2_Pos\fP)"
TPI FIFO1: ITM2 Mask 
.SS "#define TPI_FIFO1_ITM2_Pos   16U"
TPI FIFO1: ITM2 Position 
.SS "#define TPI_FIFO1_ITM2_Pos   16U"
TPI FIFO1: ITM2 Position 
.SS "#define TPI_FIFO1_ITM2_Pos   16U"
TPI FIFO1: ITM2 Position 
.SS "#define TPI_FIFO1_ITM2_Pos   16U"
TPI FIFO1: ITM2 Position 
.SS "#define TPI_FIFO1_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
TPI FIFO1: ITM_ATVALID Mask 
.SS "#define TPI_FIFO1_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
TPI FIFO1: ITM_ATVALID Mask 
.SS "#define TPI_FIFO1_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
TPI FIFO1: ITM_ATVALID Mask 
.SS "#define TPI_FIFO1_ITM_ATVALID_Msk   (0x3UL << \fBTPI_FIFO1_ITM_ATVALID_Pos\fP)"
TPI FIFO1: ITM_ATVALID Mask 
.SS "#define TPI_FIFO1_ITM_ATVALID_Pos   29U"
TPI FIFO1: ITM_ATVALID Position 
.SS "#define TPI_FIFO1_ITM_ATVALID_Pos   29U"
TPI FIFO1: ITM_ATVALID Position 
.SS "#define TPI_FIFO1_ITM_ATVALID_Pos   29U"
TPI FIFO1: ITM_ATVALID Position 
.SS "#define TPI_FIFO1_ITM_ATVALID_Pos   29U"
TPI FIFO1: ITM_ATVALID Position 
.SS "#define TPI_FIFO1_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
TPI FIFO1: ITM_bytecount Mask 
.SS "#define TPI_FIFO1_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
TPI FIFO1: ITM_bytecount Mask 
.SS "#define TPI_FIFO1_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
TPI FIFO1: ITM_bytecount Mask 
.SS "#define TPI_FIFO1_ITM_bytecount_Msk   (0x3UL << \fBTPI_FIFO1_ITM_bytecount_Pos\fP)"
TPI FIFO1: ITM_bytecount Mask 
.SS "#define TPI_FIFO1_ITM_bytecount_Pos   27U"
TPI FIFO1: ITM_bytecount Position 
.SS "#define TPI_FIFO1_ITM_bytecount_Pos   27U"
TPI FIFO1: ITM_bytecount Position 
.SS "#define TPI_FIFO1_ITM_bytecount_Pos   27U"
TPI FIFO1: ITM_bytecount Position 
.SS "#define TPI_FIFO1_ITM_bytecount_Pos   27U"
TPI FIFO1: ITM_bytecount Position 
.SS "#define TPI_ITATBCTR0_AFVALID1S_Msk   (0x1UL << \fBTPI_ITATBCTR0_AFVALID1S_Pos\fP)"
TPI ITATBCTR0: AFVALID1SS Mask 
.SS "#define TPI_ITATBCTR0_AFVALID1S_Msk   (0x1UL << \fBTPI_ITATBCTR0_AFVALID1S_Pos\fP)"
TPI ITATBCTR0: AFVALID1SS Mask 
.SS "#define TPI_ITATBCTR0_AFVALID1S_Pos   1U"
TPI ITATBCTR0: AFVALID1S Position 
.SS "#define TPI_ITATBCTR0_AFVALID1S_Pos   1U"
TPI ITATBCTR0: AFVALID1S Position 
.SS "#define TPI_ITATBCTR0_AFVALID2S_Msk   (0x1UL << \fBTPI_ITATBCTR0_AFVALID2S_Pos\fP)"
TPI ITATBCTR0: AFVALID2SS Mask 
.SS "#define TPI_ITATBCTR0_AFVALID2S_Msk   (0x1UL << \fBTPI_ITATBCTR0_AFVALID2S_Pos\fP)"
TPI ITATBCTR0: AFVALID2SS Mask 
.SS "#define TPI_ITATBCTR0_AFVALID2S_Pos   1U"
TPI ITATBCTR0: AFVALID2S Position 
.SS "#define TPI_ITATBCTR0_AFVALID2S_Pos   1U"
TPI ITATBCTR0: AFVALID2S Position 
.SS "#define TPI_ITATBCTR0_ATREADY1_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1_Pos\fP*/)"
TPI ITATBCTR0: ATREADY1 Mask 
.SS "#define TPI_ITATBCTR0_ATREADY1_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1_Pos\fP*/)"
TPI ITATBCTR0: ATREADY1 Mask 
.SS "#define TPI_ITATBCTR0_ATREADY1_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1_Pos\fP*/)"
TPI ITATBCTR0: ATREADY1 Mask 
.SS "#define TPI_ITATBCTR0_ATREADY1_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1_Pos\fP*/)"
TPI ITATBCTR0: ATREADY1 Mask 
.SS "#define TPI_ITATBCTR0_ATREADY1_Pos   0U"
TPI ITATBCTR0: ATREADY1 Position 
.SS "#define TPI_ITATBCTR0_ATREADY1_Pos   0U"
TPI ITATBCTR0: ATREADY1 Position 
.SS "#define TPI_ITATBCTR0_ATREADY1_Pos   0U"
TPI ITATBCTR0: ATREADY1 Position 
.SS "#define TPI_ITATBCTR0_ATREADY1_Pos   0U"
TPI ITATBCTR0: ATREADY1 Position 
.SS "#define TPI_ITATBCTR0_ATREADY1S_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1S_Pos\fP*/)"
TPI ITATBCTR0: ATREADY1S Mask 
.SS "#define TPI_ITATBCTR0_ATREADY1S_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY1S_Pos\fP*/)"
TPI ITATBCTR0: ATREADY1S Mask 
.SS "#define TPI_ITATBCTR0_ATREADY1S_Pos   0U"
TPI ITATBCTR0: ATREADY1S Position 
.SS "#define TPI_ITATBCTR0_ATREADY1S_Pos   0U"
TPI ITATBCTR0: ATREADY1S Position 
.SS "#define TPI_ITATBCTR0_ATREADY2_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2_Pos\fP*/)"
TPI ITATBCTR0: ATREADY2 Mask 
.SS "#define TPI_ITATBCTR0_ATREADY2_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2_Pos\fP*/)"
TPI ITATBCTR0: ATREADY2 Mask 
.SS "#define TPI_ITATBCTR0_ATREADY2_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2_Pos\fP*/)"
TPI ITATBCTR0: ATREADY2 Mask 
.SS "#define TPI_ITATBCTR0_ATREADY2_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2_Pos\fP*/)"
TPI ITATBCTR0: ATREADY2 Mask 
.SS "#define TPI_ITATBCTR0_ATREADY2_Pos   0U"
TPI ITATBCTR0: ATREADY2 Position 
.SS "#define TPI_ITATBCTR0_ATREADY2_Pos   0U"
TPI ITATBCTR0: ATREADY2 Position 
.SS "#define TPI_ITATBCTR0_ATREADY2_Pos   0U"
TPI ITATBCTR0: ATREADY2 Position 
.SS "#define TPI_ITATBCTR0_ATREADY2_Pos   0U"
TPI ITATBCTR0: ATREADY2 Position 
.SS "#define TPI_ITATBCTR0_ATREADY2S_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2S_Pos\fP*/)"
TPI ITATBCTR0: ATREADY2S Mask 
.SS "#define TPI_ITATBCTR0_ATREADY2S_Msk   (0x1UL /*<< \fBTPI_ITATBCTR0_ATREADY2S_Pos\fP*/)"
TPI ITATBCTR0: ATREADY2S Mask 
.SS "#define TPI_ITATBCTR0_ATREADY2S_Pos   0U"
TPI ITATBCTR0: ATREADY2S Position 
.SS "#define TPI_ITATBCTR0_ATREADY2S_Pos   0U"
TPI ITATBCTR0: ATREADY2S Position 
.SS "#define TPI_ITATBCTR2_AFVALID1S_Msk   (0x1UL << \fBTPI_ITATBCTR2_AFVALID1S_Pos\fP)"
TPI ITATBCTR2: AFVALID1SS Mask 
.SS "#define TPI_ITATBCTR2_AFVALID1S_Msk   (0x1UL << \fBTPI_ITATBCTR2_AFVALID1S_Pos\fP)"
TPI ITATBCTR2: AFVALID1SS Mask 
.SS "#define TPI_ITATBCTR2_AFVALID1S_Pos   1U"
TPI ITATBCTR2: AFVALID1S Position 
.SS "#define TPI_ITATBCTR2_AFVALID1S_Pos   1U"
TPI ITATBCTR2: AFVALID1S Position 
.SS "#define TPI_ITATBCTR2_AFVALID2S_Msk   (0x1UL << \fBTPI_ITATBCTR2_AFVALID2S_Pos\fP)"
TPI ITATBCTR2: AFVALID2SS Mask 
.SS "#define TPI_ITATBCTR2_AFVALID2S_Msk   (0x1UL << \fBTPI_ITATBCTR2_AFVALID2S_Pos\fP)"
TPI ITATBCTR2: AFVALID2SS Mask 
.SS "#define TPI_ITATBCTR2_AFVALID2S_Pos   1U"
TPI ITATBCTR2: AFVALID2S Position 
.SS "#define TPI_ITATBCTR2_AFVALID2S_Pos   1U"
TPI ITATBCTR2: AFVALID2S Position 
.SS "#define TPI_ITATBCTR2_ATREADY1_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1_Pos\fP*/)"
TPI ITATBCTR2: ATREADY1 Mask 
.SS "#define TPI_ITATBCTR2_ATREADY1_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1_Pos\fP*/)"
TPI ITATBCTR2: ATREADY1 Mask 
.SS "#define TPI_ITATBCTR2_ATREADY1_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1_Pos\fP*/)"
TPI ITATBCTR2: ATREADY1 Mask 
.SS "#define TPI_ITATBCTR2_ATREADY1_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1_Pos\fP*/)"
TPI ITATBCTR2: ATREADY1 Mask 
.SS "#define TPI_ITATBCTR2_ATREADY1_Pos   0U"
TPI ITATBCTR2: ATREADY1 Position 
.SS "#define TPI_ITATBCTR2_ATREADY1_Pos   0U"
TPI ITATBCTR2: ATREADY1 Position 
.SS "#define TPI_ITATBCTR2_ATREADY1_Pos   0U"
TPI ITATBCTR2: ATREADY1 Position 
.SS "#define TPI_ITATBCTR2_ATREADY1_Pos   0U"
TPI ITATBCTR2: ATREADY1 Position 
.SS "#define TPI_ITATBCTR2_ATREADY1S_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1S_Pos\fP*/)"
TPI ITATBCTR2: ATREADY1S Mask 
.SS "#define TPI_ITATBCTR2_ATREADY1S_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY1S_Pos\fP*/)"
TPI ITATBCTR2: ATREADY1S Mask 
.SS "#define TPI_ITATBCTR2_ATREADY1S_Pos   0U"
TPI ITATBCTR2: ATREADY1S Position 
.SS "#define TPI_ITATBCTR2_ATREADY1S_Pos   0U"
TPI ITATBCTR2: ATREADY1S Position 
.SS "#define TPI_ITATBCTR2_ATREADY2_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2_Pos\fP*/)"
TPI ITATBCTR2: ATREADY2 Mask 
.SS "#define TPI_ITATBCTR2_ATREADY2_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2_Pos\fP*/)"
TPI ITATBCTR2: ATREADY2 Mask 
.SS "#define TPI_ITATBCTR2_ATREADY2_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2_Pos\fP*/)"
TPI ITATBCTR2: ATREADY2 Mask 
.SS "#define TPI_ITATBCTR2_ATREADY2_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2_Pos\fP*/)"
TPI ITATBCTR2: ATREADY2 Mask 
.SS "#define TPI_ITATBCTR2_ATREADY2_Pos   0U"
TPI ITATBCTR2: ATREADY2 Position 
.SS "#define TPI_ITATBCTR2_ATREADY2_Pos   0U"
TPI ITATBCTR2: ATREADY2 Position 
.SS "#define TPI_ITATBCTR2_ATREADY2_Pos   0U"
TPI ITATBCTR2: ATREADY2 Position 
.SS "#define TPI_ITATBCTR2_ATREADY2_Pos   0U"
TPI ITATBCTR2: ATREADY2 Position 
.SS "#define TPI_ITATBCTR2_ATREADY2S_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2S_Pos\fP*/)"
TPI ITATBCTR2: ATREADY2S Mask 
.SS "#define TPI_ITATBCTR2_ATREADY2S_Msk   (0x1UL /*<< \fBTPI_ITATBCTR2_ATREADY2S_Pos\fP*/)"
TPI ITATBCTR2: ATREADY2S Mask 
.SS "#define TPI_ITATBCTR2_ATREADY2S_Pos   0U"
TPI ITATBCTR2: ATREADY2S Position 
.SS "#define TPI_ITATBCTR2_ATREADY2S_Pos   0U"
TPI ITATBCTR2: ATREADY2S Position 
.SS "#define TPI_ITCTRL_Mode_Msk   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
TPI ITCTRL: Mode Mask 
.SS "#define TPI_ITCTRL_Mode_Msk   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
TPI ITCTRL: Mode Mask 
.SS "#define TPI_ITCTRL_Mode_Msk   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
TPI ITCTRL: Mode Mask 
.SS "#define TPI_ITCTRL_Mode_Msk   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
TPI ITCTRL: Mode Mask 
.SS "#define TPI_ITCTRL_Mode_Msk   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
TPI ITCTRL: Mode Mask 
.SS "#define TPI_ITCTRL_Mode_Msk   (0x3UL /*<< \fBTPI_ITCTRL_Mode_Pos\fP*/)"
TPI ITCTRL: Mode Mask 
.SS "#define TPI_ITCTRL_Mode_Pos   0U"
TPI ITCTRL: Mode Position 
.SS "#define TPI_ITCTRL_Mode_Pos   0U"
TPI ITCTRL: Mode Position 
.SS "#define TPI_ITCTRL_Mode_Pos   0U"
TPI ITCTRL: Mode Position 
.SS "#define TPI_ITCTRL_Mode_Pos   0U"
TPI ITCTRL: Mode Position 
.SS "#define TPI_ITCTRL_Mode_Pos   0U"
TPI ITCTRL: Mode Position 
.SS "#define TPI_ITCTRL_Mode_Pos   0U"
TPI ITCTRL: Mode Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_ATVALID_Msk   (0x3UL << \fBTPI_ITFTTD0_ATB_IF1_ATVALID_Pos\fP)"
TPI ITFTTD0: ATB Interface 1 ATVALID Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_ATVALID_Msk   (0x3UL << \fBTPI_ITFTTD0_ATB_IF1_ATVALID_Pos\fP)"
TPI ITFTTD0: ATB Interface 1 ATVALID Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_ATVALID_Pos   26U"
TPI ITFTTD0: ATB Interface 1 ATVALID Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_ATVALID_Pos   26U"
TPI ITFTTD0: ATB Interface 1 ATVALID Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_bytecount_Msk   (0x3UL << \fBTPI_ITFTTD0_ATB_IF1_bytecount_Pos\fP)"
TPI ITFTTD0: ATB Interface 1 byte countt Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_bytecount_Msk   (0x3UL << \fBTPI_ITFTTD0_ATB_IF1_bytecount_Pos\fP)"
TPI ITFTTD0: ATB Interface 1 byte countt Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_bytecount_Pos   24U"
TPI ITFTTD0: ATB Interface 1 byte count Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_bytecount_Pos   24U"
TPI ITFTTD0: ATB Interface 1 byte count Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_data0_Msk   (0xFFUL /*<< \fBTPI_ITFTTD0_ATB_IF1_data0_Pos\fP*/)"
TPI ITFTTD0: ATB Interface 1 data0 Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_data0_Msk   (0xFFUL /*<< \fBTPI_ITFTTD0_ATB_IF1_data0_Pos\fP*/)"
TPI ITFTTD0: ATB Interface 1 data0 Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_data0_Pos   0U"
TPI ITFTTD0: ATB Interface 1 data0 Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_data0_Pos   0U"
TPI ITFTTD0: ATB Interface 1 data0 Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_data1_Msk   (0xFFUL << \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP)"
TPI ITFTTD0: ATB Interface 1 data1 Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_data1_Msk   (0xFFUL << \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP)"
TPI ITFTTD0: ATB Interface 1 data1 Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_data1_Pos   8U"
TPI ITFTTD0: ATB Interface 1 data1 Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_data1_Pos   8U"
TPI ITFTTD0: ATB Interface 1 data1 Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_data2_Msk   (0xFFUL << \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP)"
TPI ITFTTD0: ATB Interface 1 data2 Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_data2_Msk   (0xFFUL << \fBTPI_ITFTTD0_ATB_IF1_data1_Pos\fP)"
TPI ITFTTD0: ATB Interface 1 data2 Mask 
.SS "#define TPI_ITFTTD0_ATB_IF1_data2_Pos   16U"
TPI ITFTTD0: ATB Interface 1 data2 Position 
.SS "#define TPI_ITFTTD0_ATB_IF1_data2_Pos   16U"
TPI ITFTTD0: ATB Interface 1 data2 Position 
.SS "#define TPI_ITFTTD0_ATB_IF2_ATVALID_Msk   (0x3UL << \fBTPI_ITFTTD0_ATB_IF2_ATVALID_Pos\fP)"
TPI ITFTTD0: ATB Interface 2 ATVALID Mask 
.SS "#define TPI_ITFTTD0_ATB_IF2_ATVALID_Msk   (0x3UL << \fBTPI_ITFTTD0_ATB_IF2_ATVALID_Pos\fP)"
TPI ITFTTD0: ATB Interface 2 ATVALID Mask 
.SS "#define TPI_ITFTTD0_ATB_IF2_ATVALID_Pos   29U"
TPI ITFTTD0: ATB Interface 2 ATVALIDPosition 
.SS "#define TPI_ITFTTD0_ATB_IF2_ATVALID_Pos   29U"
TPI ITFTTD0: ATB Interface 2 ATVALIDPosition 
.SS "#define TPI_ITFTTD0_ATB_IF2_bytecount_Msk   (0x3UL << \fBTPI_ITFTTD0_ATB_IF2_bytecount_Pos\fP)"
TPI ITFTTD0: ATB Interface 2 byte count Mask 
.SS "#define TPI_ITFTTD0_ATB_IF2_bytecount_Msk   (0x3UL << \fBTPI_ITFTTD0_ATB_IF2_bytecount_Pos\fP)"
TPI ITFTTD0: ATB Interface 2 byte count Mask 
.SS "#define TPI_ITFTTD0_ATB_IF2_bytecount_Pos   27U"
TPI ITFTTD0: ATB Interface 2 byte count Position 
.SS "#define TPI_ITFTTD0_ATB_IF2_bytecount_Pos   27U"
TPI ITFTTD0: ATB Interface 2 byte count Position 
.SS "#define TPI_ITFTTD1_ATB_IF1_ATVALID_Msk   (0x3UL << \fBTPI_ITFTTD1_ATB_IF1_ATVALID_Pos\fP)"
TPI ITFTTD1: ATB Interface 1 ATVALID Mask 
.SS "#define TPI_ITFTTD1_ATB_IF1_ATVALID_Msk   (0x3UL << \fBTPI_ITFTTD1_ATB_IF1_ATVALID_Pos\fP)"
TPI ITFTTD1: ATB Interface 1 ATVALID Mask 
.SS "#define TPI_ITFTTD1_ATB_IF1_ATVALID_Pos   26U"
TPI ITFTTD1: ATB Interface 1 ATVALID Position 
.SS "#define TPI_ITFTTD1_ATB_IF1_ATVALID_Pos   26U"
TPI ITFTTD1: ATB Interface 1 ATVALID Position 
.SS "#define TPI_ITFTTD1_ATB_IF1_bytecount_Msk   (0x3UL << \fBTPI_ITFTTD1_ATB_IF1_bytecount_Pos\fP)"
TPI ITFTTD1: ATB Interface 1 byte countt Mask 
.SS "#define TPI_ITFTTD1_ATB_IF1_bytecount_Msk   (0x3UL << \fBTPI_ITFTTD1_ATB_IF1_bytecount_Pos\fP)"
TPI ITFTTD1: ATB Interface 1 byte countt Mask 
.SS "#define TPI_ITFTTD1_ATB_IF1_bytecount_Pos   24U"
TPI ITFTTD1: ATB Interface 1 byte count Position 
.SS "#define TPI_ITFTTD1_ATB_IF1_bytecount_Pos   24U"
TPI ITFTTD1: ATB Interface 1 byte count Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_ATVALID_Msk   (0x3UL << \fBTPI_ITFTTD1_ATB_IF2_ATVALID_Pos\fP)"
TPI ITFTTD1: ATB Interface 2 ATVALID Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_ATVALID_Msk   (0x3UL << \fBTPI_ITFTTD1_ATB_IF2_ATVALID_Pos\fP)"
TPI ITFTTD1: ATB Interface 2 ATVALID Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_ATVALID_Pos   29U"
TPI ITFTTD1: ATB Interface 2 ATVALID Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_ATVALID_Pos   29U"
TPI ITFTTD1: ATB Interface 2 ATVALID Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_bytecount_Msk   (0x3UL << \fBTPI_ITFTTD1_ATB_IF2_bytecount_Pos\fP)"
TPI ITFTTD1: ATB Interface 2 byte count Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_bytecount_Msk   (0x3UL << \fBTPI_ITFTTD1_ATB_IF2_bytecount_Pos\fP)"
TPI ITFTTD1: ATB Interface 2 byte count Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_bytecount_Pos   27U"
TPI ITFTTD1: ATB Interface 2 byte count Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_bytecount_Pos   27U"
TPI ITFTTD1: ATB Interface 2 byte count Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_data0_Msk   (0xFFUL /*<< \fBTPI_ITFTTD1_ATB_IF2_data0_Pos\fP*/)"
TPI ITFTTD1: ATB Interface 2 data0 Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_data0_Msk   (0xFFUL /*<< \fBTPI_ITFTTD1_ATB_IF2_data0_Pos\fP*/)"
TPI ITFTTD1: ATB Interface 2 data0 Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_data0_Pos   0U"
TPI ITFTTD1: ATB Interface 2 data0 Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_data0_Pos   0U"
TPI ITFTTD1: ATB Interface 2 data0 Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_data1_Msk   (0xFFUL << \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP)"
TPI ITFTTD1: ATB Interface 2 data1 Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_data1_Msk   (0xFFUL << \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP)"
TPI ITFTTD1: ATB Interface 2 data1 Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_data1_Pos   8U"
TPI ITFTTD1: ATB Interface 2 data1 Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_data1_Pos   8U"
TPI ITFTTD1: ATB Interface 2 data1 Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_data2_Msk   (0xFFUL << \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP)"
TPI ITFTTD1: ATB Interface 2 data2 Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_data2_Msk   (0xFFUL << \fBTPI_ITFTTD1_ATB_IF2_data1_Pos\fP)"
TPI ITFTTD1: ATB Interface 2 data2 Mask 
.SS "#define TPI_ITFTTD1_ATB_IF2_data2_Pos   16U"
TPI ITFTTD1: ATB Interface 2 data2 Position 
.SS "#define TPI_ITFTTD1_ATB_IF2_data2_Pos   16U"
TPI ITFTTD1: ATB Interface 2 data2 Position 
.SS "#define TPI_LSR_nTT_Msk   (0x1UL << \fBTPI_LSR_nTT_Pos\fP)"
TPI LSR: Not thirty-two bit\&. Mask 
.SS "#define TPI_LSR_nTT_Msk   (0x1UL << \fBTPI_LSR_nTT_Pos\fP)"
TPI LSR: Not thirty-two bit\&. Mask 
.SS "#define TPI_LSR_nTT_Pos   1U"
TPI LSR: Not thirty-two bit\&. Position 
.SS "#define TPI_LSR_nTT_Pos   1U"
TPI LSR: Not thirty-two bit\&. Position 
.SS "#define TPI_LSR_SLI_Msk   (0x1UL /*<< \fBTPI_LSR_SLI_Pos\fP*/)"
TPI LSR: Software Lock implemented Mask 
.SS "#define TPI_LSR_SLI_Msk   (0x1UL /*<< \fBTPI_LSR_SLI_Pos\fP*/)"
TPI LSR: Software Lock implemented Mask 
.SS "#define TPI_LSR_SLI_Pos   0U"
TPI LSR: Software Lock implemented Position 
.SS "#define TPI_LSR_SLI_Pos   0U"
TPI LSR: Software Lock implemented Position 
.SS "#define TPI_LSR_SLK_Msk   (0x1UL << \fBTPI_LSR_SLK_Pos\fP)"
TPI LSR: Software Lock status Mask 
.SS "#define TPI_LSR_SLK_Msk   (0x1UL << \fBTPI_LSR_SLK_Pos\fP)"
TPI LSR: Software Lock status Mask 
.SS "#define TPI_LSR_SLK_Pos   1U"
TPI LSR: Software Lock status Position 
.SS "#define TPI_LSR_SLK_Pos   1U"
TPI LSR: Software Lock status Position 
.SS "#define TPI_PSCR_PSCount_Msk   (0x1FUL /*<< \fBTPI_PSCR_PSCount_Pos\fP*/)"
TPI PSCR: TPSCount Mask 
.SS "#define TPI_PSCR_PSCount_Msk   (0x1FUL /*<< \fBTPI_PSCR_PSCount_Pos\fP*/)"
TPI PSCR: TPSCount Mask 
.SS "#define TPI_PSCR_PSCount_Pos   0U"
TPI PSCR: PSCount Position 
.SS "#define TPI_PSCR_PSCount_Pos   0U"
TPI PSCR: PSCount Position 
.SS "#define TPI_SPPR_TXMODE_Msk   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
TPI SPPR: TXMODE Mask 
.SS "#define TPI_SPPR_TXMODE_Msk   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
TPI SPPR: TXMODE Mask 
.SS "#define TPI_SPPR_TXMODE_Msk   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
TPI SPPR: TXMODE Mask 
.SS "#define TPI_SPPR_TXMODE_Msk   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
TPI SPPR: TXMODE Mask 
.SS "#define TPI_SPPR_TXMODE_Msk   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
TPI SPPR: TXMODE Mask 
.SS "#define TPI_SPPR_TXMODE_Msk   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
TPI SPPR: TXMODE Mask 
.SS "#define TPI_SPPR_TXMODE_Msk   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
TPI SPPR: TXMODE Mask 
.SS "#define TPI_SPPR_TXMODE_Msk   (0x3UL /*<< \fBTPI_SPPR_TXMODE_Pos\fP*/)"
TPI SPPR: TXMODE Mask 
.SS "#define TPI_SPPR_TXMODE_Pos   0U"
TPI SPPR: TXMODE Position 
.SS "#define TPI_SPPR_TXMODE_Pos   0U"
TPI SPPR: TXMODE Position 
.SS "#define TPI_SPPR_TXMODE_Pos   0U"
TPI SPPR: TXMODE Position 
.SS "#define TPI_SPPR_TXMODE_Pos   0U"
TPI SPPR: TXMODE Position 
.SS "#define TPI_SPPR_TXMODE_Pos   0U"
TPI SPPR: TXMODE Position 
.SS "#define TPI_SPPR_TXMODE_Pos   0U"
TPI SPPR: TXMODE Position 
.SS "#define TPI_SPPR_TXMODE_Pos   0U"
TPI SPPR: TXMODE Position 
.SS "#define TPI_SPPR_TXMODE_Pos   0U"
TPI SPPR: TXMODE Position 
.SS "#define TPI_TRIGGER_TRIGGER_Msk   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
TPI TRIGGER: TRIGGER Mask 
.SS "#define TPI_TRIGGER_TRIGGER_Msk   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
TPI TRIGGER: TRIGGER Mask 
.SS "#define TPI_TRIGGER_TRIGGER_Msk   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
TPI TRIGGER: TRIGGER Mask 
.SS "#define TPI_TRIGGER_TRIGGER_Msk   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
TPI TRIGGER: TRIGGER Mask 
.SS "#define TPI_TRIGGER_TRIGGER_Msk   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
TPI TRIGGER: TRIGGER Mask 
.SS "#define TPI_TRIGGER_TRIGGER_Msk   (0x1UL /*<< \fBTPI_TRIGGER_TRIGGER_Pos\fP*/)"
TPI TRIGGER: TRIGGER Mask 
.SS "#define TPI_TRIGGER_TRIGGER_Pos   0U"
TPI TRIGGER: TRIGGER Position 
.SS "#define TPI_TRIGGER_TRIGGER_Pos   0U"
TPI TRIGGER: TRIGGER Position 
.SS "#define TPI_TRIGGER_TRIGGER_Pos   0U"
TPI TRIGGER: TRIGGER Position 
.SS "#define TPI_TRIGGER_TRIGGER_Pos   0U"
TPI TRIGGER: TRIGGER Position 
.SS "#define TPI_TRIGGER_TRIGGER_Pos   0U"
TPI TRIGGER: TRIGGER Position 
.SS "#define TPI_TRIGGER_TRIGGER_Pos   0U"
TPI TRIGGER: TRIGGER Position 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
