.TH "CMSIS_core_register" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_core_register \- Type definitions and defines for Cortex-M processor based devices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBStatus and Control Registers\fP"
.br
.RI "Core Register type definitions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Type definitions and defines for Cortex-M processor based devices\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
