.TH "CMSIS_Core_SAUFunctions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_Core_SAUFunctions \- Functions that configure the SAU\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSysTick Functions\fP"
.br
.RI "Functions that configure the System\&. "
.in -1c
.SH "Detailed Description"
.PP 
Functions that configure the SAU\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
