.TH "CORTEX_Exported_Functions_Group1" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CORTEX_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_NVIC_SetPriorityGrouping\fP (uint32_t PriorityGroup)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_SetPriority\fP (\fBIRQn_Type\fP IRQn, uint32_t PreemptPriority, uint32_t SubPriority)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_EnableIRQ\fP (\fBIRQn_Type\fP IRQn)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_DisableIRQ\fP (\fBIRQn_Type\fP IRQn)"
.br
.ti -1c
.RI "void \fBHAL_NVIC_SystemReset\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_SYSTICK_Config\fP (uint32_t TicksNumb)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void HAL_NVIC_DisableIRQ (\fBIRQn_Type\fP IRQn)"

.SS "void HAL_NVIC_EnableIRQ (\fBIRQn_Type\fP IRQn)"

.SS "void HAL_NVIC_SetPriority (\fBIRQn_Type\fP IRQn, uint32_t PreemptPriority, uint32_t SubPriority)"

.SS "void HAL_NVIC_SetPriorityGrouping (uint32_t PriorityGroup)"

.SS "void HAL_NVIC_SystemReset (void)"

.SS "uint32_t HAL_SYSTICK_Config (uint32_t TicksNumb)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
