.TH "DBGMCU_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBGMCU_TypeDef \- Debug MCU\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIDCODE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Debug MCU\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t DBGMCU_TypeDef::CR"

.SS "\fB__IO\fP uint32_t DBGMCU_TypeDef::IDCODE"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
