.TH "deprecated" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBGlobal \fB__ARMv8MBL_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__ARMv8MBL_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__ARMv8MBL_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__ARMv8MML_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__ARMv8MML_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__ARMv8MML_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__CM0_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__CM0_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__CM0_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__CM0PLUS_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__CM0PLUS_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__CM0PLUS_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__CM1_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__CM1_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__CM1_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__CM23_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__CM23_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__CM23_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__CM33_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__CM33_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__CM33_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__CM3_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__CM3_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__CM3_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__CM4_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__CM4_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__CM4_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__CM7_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__CM7_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__CM7_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__SC000_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__SC000_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__SC000_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version  
.IP "\fBGlobal \fB__SC300_CMSIS_VERSION\fP \fP" 1c
CMSIS HAL version number  
.IP "\fBGlobal \fB__SC300_CMSIS_VERSION_MAIN\fP \fP" 1c
[31:16] CMSIS HAL main version  
.IP "\fBGlobal \fB__SC300_CMSIS_VERSION_SUB\fP \fP" 1c
[15:0] CMSIS HAL sub version 
.PP

