.TH "DMA_flag_definitions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_flag_definitions
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_FLAG_GL1\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC1\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT1\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE1\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GL2\fP   0x00000010U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC2\fP   0x00000020U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT2\fP   0x00000040U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE2\fP   0x00000080U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GL3\fP   0x00000100U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC3\fP   0x00000200U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT3\fP   0x00000400U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE3\fP   0x00000800U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GL4\fP   0x00001000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC4\fP   0x00002000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT4\fP   0x00004000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE4\fP   0x00008000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GL5\fP   0x00010000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC5\fP   0x00020000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT5\fP   0x00040000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE5\fP   0x00080000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GL6\fP   0x00100000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC6\fP   0x00200000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT6\fP   0x00400000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE6\fP   0x00800000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_GL7\fP   0x01000000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TC7\fP   0x02000000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_HT7\fP   0x04000000U"
.br
.ti -1c
.RI "#define \fBDMA_FLAG_TE7\fP   0x08000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_FLAG_GL1   0x00000001U"

.SS "#define DMA_FLAG_GL2   0x00000010U"

.SS "#define DMA_FLAG_GL3   0x00000100U"

.SS "#define DMA_FLAG_GL4   0x00001000U"

.SS "#define DMA_FLAG_GL5   0x00010000U"

.SS "#define DMA_FLAG_GL6   0x00100000U"

.SS "#define DMA_FLAG_GL7   0x01000000U"

.SS "#define DMA_FLAG_HT1   0x00000004U"

.SS "#define DMA_FLAG_HT2   0x00000040U"

.SS "#define DMA_FLAG_HT3   0x00000400U"

.SS "#define DMA_FLAG_HT4   0x00004000U"

.SS "#define DMA_FLAG_HT5   0x00040000U"

.SS "#define DMA_FLAG_HT6   0x00400000U"

.SS "#define DMA_FLAG_HT7   0x04000000U"

.SS "#define DMA_FLAG_TC1   0x00000002U"

.SS "#define DMA_FLAG_TC2   0x00000020U"

.SS "#define DMA_FLAG_TC3   0x00000200U"

.SS "#define DMA_FLAG_TC4   0x00002000U"

.SS "#define DMA_FLAG_TC5   0x00020000U"

.SS "#define DMA_FLAG_TC6   0x00200000U"

.SS "#define DMA_FLAG_TC7   0x02000000U"

.SS "#define DMA_FLAG_TE1   0x00000008U"

.SS "#define DMA_FLAG_TE2   0x00000080U"

.SS "#define DMA_FLAG_TE3   0x00000800U"

.SS "#define DMA_FLAG_TE4   0x00008000U"

.SS "#define DMA_FLAG_TE5   0x00080000U"

.SS "#define DMA_FLAG_TE6   0x00800000U"

.SS "#define DMA_FLAG_TE7   0x08000000U"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
