.TH "DMA_Exported_Functions_Group1" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DMA_Init\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DMA_DeInit\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_DMA_DeInit (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "\fBHAL_StatusTypeDef\fP HAL_DMA_Init (\fBDMA_HandleTypeDef\fP * hdma)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
