.TH "DMA_Data_transfer_direction" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Data_transfer_direction
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_PERIPH_TO_MEMORY\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBDMA_MEMORY_TO_PERIPH\fP   ((uint32_t)\fBDMA_CCR_DIR\fP)"
.br
.ti -1c
.RI "#define \fBDMA_MEMORY_TO_MEMORY\fP   ((uint32_t)\fBDMA_CCR_MEM2MEM\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_MEMORY_TO_MEMORY   ((uint32_t)\fBDMA_CCR_MEM2MEM\fP)"
Memory to memory direction 
.br
 
.SS "#define DMA_MEMORY_TO_PERIPH   ((uint32_t)\fBDMA_CCR_DIR\fP)"
Memory to peripheral direction 
.SS "#define DMA_PERIPH_TO_MEMORY   0x00000000U"
Peripheral to memory direction 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
