.TH "DMA_Peripheral_incremented_mode" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Peripheral_incremented_mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_PINC_ENABLE\fP   ((uint32_t)\fBDMA_CCR_PINC\fP)"
.br
.ti -1c
.RI "#define \fBDMA_PINC_DISABLE\fP   0x00000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_PINC_DISABLE   0x00000000U"
Peripheral increment mode Disable 
.SS "#define DMA_PINC_ENABLE   ((uint32_t)\fBDMA_CCR_PINC\fP)"
Peripheral increment mode Enable 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
