.TH "DMA_mode" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_NORMAL\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBDMA_CIRCULAR\fP   ((uint32_t)\fBDMA_CCR_CIRC\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_CIRCULAR   ((uint32_t)\fBDMA_CCR_CIRC\fP)"
Circular mode 
.br
 
.SS "#define DMA_NORMAL   0x00000000U"
Normal mode 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
