.TH "DMA_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_TypeDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBISR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIFCR\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t DMA_TypeDef::IFCR"

.SS "\fB__IO\fP uint32_t DMA_TypeDef::ISR"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
