.TH "DMA_Exported_Constants" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDMA Error Code\fP"
.br
.ti -1c
.RI "\fBDMA Data transfer direction\fP"
.br
.ti -1c
.RI "\fBDMA Peripheral incremented mode\fP"
.br
.ti -1c
.RI "\fBDMA Memory incremented mode\fP"
.br
.ti -1c
.RI "\fBDMA Peripheral data size\fP"
.br
.ti -1c
.RI "\fBDMA Memory data size\fP"
.br
.ti -1c
.RI "\fBDMA mode\fP"
.br
.ti -1c
.RI "\fBDMA Priority level\fP"
.br
.ti -1c
.RI "\fBDMA interrupt enable definitions\fP"
.br
.ti -1c
.RI "\fBDMA flag definitions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
