.TH "DMA_Private_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_DMA_DIRECTION\fP(DIRECTION)"
.br
.ti -1c
.RI "#define \fBIS_DMA_BUFFER_SIZE\fP(SIZE)   (((SIZE) >= 0x1U) && ((SIZE) < 0x10000U))"
.br
.ti -1c
.RI "#define \fBIS_DMA_PERIPHERAL_INC_STATE\fP(STATE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_MEMORY_INC_STATE\fP(STATE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_PERIPHERAL_DATA_SIZE\fP(SIZE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_MEMORY_DATA_SIZE\fP(SIZE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_MODE\fP(MODE)"
.br
.ti -1c
.RI "#define \fBIS_DMA_PRIORITY\fP(PRIORITY)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_DMA_BUFFER_SIZE(SIZE)   (((SIZE) >= 0x1U) && ((SIZE) < 0x10000U))"

.SS "#define IS_DMA_DIRECTION(DIRECTION)"
\fBValue:\fP
.PP
.nf
(((DIRECTION) == DMA_PERIPH_TO_MEMORY ) || \
                                     ((DIRECTION) == DMA_MEMORY_TO_PERIPH)  || \
                                     ((DIRECTION) == DMA_MEMORY_TO_MEMORY))
.fi
.SS "#define IS_DMA_MEMORY_DATA_SIZE(SIZE)"
\fBValue:\fP
.PP
.nf
(((SIZE) == DMA_MDATAALIGN_BYTE)     || \
                                       ((SIZE) == DMA_MDATAALIGN_HALFWORD) || \
                                       ((SIZE) == DMA_MDATAALIGN_WORD ))
.fi
.SS "#define IS_DMA_MEMORY_INC_STATE(STATE)"
\fBValue:\fP
.PP
.nf
(((STATE) == DMA_MINC_ENABLE)  || \
                                        ((STATE) == DMA_MINC_DISABLE))
.fi
.SS "#define IS_DMA_MODE(MODE)"
\fBValue:\fP
.PP
.nf
(((MODE) == DMA_NORMAL )  || \
                           ((MODE) == DMA_CIRCULAR))
.fi
.SS "#define IS_DMA_PERIPHERAL_DATA_SIZE(SIZE)"
\fBValue:\fP
.PP
.nf
(((SIZE) == DMA_PDATAALIGN_BYTE)     || \
                                           ((SIZE) == DMA_PDATAALIGN_HALFWORD) || \
                                           ((SIZE) == DMA_PDATAALIGN_WORD))
.fi
.SS "#define IS_DMA_PERIPHERAL_INC_STATE(STATE)"
\fBValue:\fP
.PP
.nf
(((STATE) == DMA_PINC_ENABLE) || \
                                            ((STATE) == DMA_PINC_DISABLE))
.fi
.SS "#define IS_DMA_PRIORITY(PRIORITY)"
\fBValue:\fP
.PP
.nf
(((PRIORITY) == DMA_PRIORITY_LOW )   || \
                                   ((PRIORITY) == DMA_PRIORITY_MEDIUM) || \
                                   ((PRIORITY) == DMA_PRIORITY_HIGH)   || \
                                   ((PRIORITY) == DMA_PRIORITY_VERY_HIGH))
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
