.TH "EXTI_GPIOSel" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_GPIOSel
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXTI_GPIOA\fP   0x00000000u"
.br
.ti -1c
.RI "#define \fBEXTI_GPIOB\fP   0x00000001u"
.br
.ti -1c
.RI "#define \fBEXTI_GPIOC\fP   0x00000002u"
.br
.ti -1c
.RI "#define \fBEXTI_GPIOD\fP   0x00000003u"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define EXTI_GPIOA   0x00000000u"

.SS "#define EXTI_GPIOB   0x00000001u"

.SS "#define EXTI_GPIOC   0x00000002u"

.SS "#define EXTI_GPIOD   0x00000003u"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
