.TH "EXTI_Private_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_EXTI_LINE\fP(__LINE__)"
.br
.ti -1c
.RI "#define \fBIS_EXTI_MODE\fP(__LINE__)"
.br
.ti -1c
.RI "#define \fBIS_EXTI_TRIGGER\fP(__LINE__)   (((__LINE__) & ~\fBEXTI_TRIGGER_MASK\fP) == 0x00u)"
.br
.ti -1c
.RI "#define \fBIS_EXTI_PENDING_EDGE\fP(__LINE__)   ((__LINE__) == \fBEXTI_TRIGGER_RISING_FALLING\fP)"
.br
.ti -1c
.RI "#define \fBIS_EXTI_CONFIG_LINE\fP(__LINE__)   (((__LINE__) & \fBEXTI_CONFIG\fP) != 0x00u)"
.br
.ti -1c
.RI "#define \fBIS_EXTI_GPIO_PORT\fP(__PORT__)"
.br
.ti -1c
.RI "#define \fBIS_EXTI_GPIO_PIN\fP(__PIN__)   ((__PIN__) < 16u)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_EXTI_CONFIG_LINE(__LINE__)   (((__LINE__) & \fBEXTI_CONFIG\fP) != 0x00u)"

.SS "#define IS_EXTI_GPIO_PIN(__PIN__)   ((__PIN__) < 16u)"

.SS "#define IS_EXTI_GPIO_PORT(__PORT__)"
\fBValue:\fP
.PP
.nf
(((__PORT__) == EXTI_GPIOA) || \
                                         ((__PORT__) == EXTI_GPIOB) || \
                                         ((__PORT__) == EXTI_GPIOC) || \
                                         ((__PORT__) == EXTI_GPIOD))
.fi
.SS "#define IS_EXTI_LINE(__LINE__)"
\fBValue:\fP
.PP
.nf
((((__LINE__) & ~(EXTI_PROPERTY_MASK | EXTI_PIN_MASK)) == 0x00u) && \
                                        ((((__LINE__) & EXTI_PROPERTY_MASK) == EXTI_CONFIG)   || \
                                         (((__LINE__) & EXTI_PROPERTY_MASK) == EXTI_GPIO))    && \
                                         (((__LINE__) & EXTI_PIN_MASK) < EXTI_LINE_NB))
.fi
.SS "#define IS_EXTI_MODE(__LINE__)"
\fBValue:\fP
.PP
.nf
((((__LINE__) & EXTI_MODE_MASK) != 0x00u) && \
                                         (((__LINE__) & ~EXTI_MODE_MASK) == 0x00u))
.fi
.SS "#define IS_EXTI_PENDING_EDGE(__LINE__)   ((__LINE__) == \fBEXTI_TRIGGER_RISING_FALLING\fP)"

.SS "#define IS_EXTI_TRIGGER(__LINE__)   (((__LINE__) & ~\fBEXTI_TRIGGER_MASK\fP) == 0x00u)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
