.TH "EXTI_Mode" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_Mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXTI_MODE_NONE\fP   0x00000000u"
.br
.ti -1c
.RI "#define \fBEXTI_MODE_INTERRUPT\fP   0x00000001u"
.br
.ti -1c
.RI "#define \fBEXTI_MODE_EVENT\fP   0x00000002u"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define EXTI_MODE_EVENT   0x00000002u"

.SS "#define EXTI_MODE_INTERRUPT   0x00000001u"

.SS "#define EXTI_MODE_NONE   0x00000000u"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
