.TH "EXTI_HandleTypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_HandleTypeDef \- EXTI Handle structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f1xx_hal_exti\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBLine\fP"
.br
.ti -1c
.RI "void(* \fBPendingCallback\fP )(void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
EXTI Handle structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t EXTI_HandleTypeDef::Line"
Exti line number 
.SS "void(*  EXTI_HandleTypeDef::PendingCallback) (void)"
Exti pending callback 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
