.TH "EXTI_Trigger" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_Trigger
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXTI_TRIGGER_NONE\fP   0x00000000u"
.br
.ti -1c
.RI "#define \fBEXTI_TRIGGER_RISING\fP   0x00000001u"
.br
.ti -1c
.RI "#define \fBEXTI_TRIGGER_FALLING\fP   0x00000002u"
.br
.ti -1c
.RI "#define \fBEXTI_TRIGGER_RISING_FALLING\fP   (\fBEXTI_TRIGGER_RISING\fP | \fBEXTI_TRIGGER_FALLING\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define EXTI_TRIGGER_FALLING   0x00000002u"

.SS "#define EXTI_TRIGGER_NONE   0x00000000u"

.SS "#define EXTI_TRIGGER_RISING   0x00000001u"

.SS "#define EXTI_TRIGGER_RISING_FALLING   (\fBEXTI_TRIGGER_RISING\fP | \fBEXTI_TRIGGER_FALLING\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
