.TH "FLASHEx_OB_WRP_State" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_OB_WRP_State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_WRPSTATE_DISABLE\fP   0x00U"
.br
.ti -1c
.RI "#define \fBOB_WRPSTATE_ENABLE\fP   0x01U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_WRPSTATE_DISABLE   0x00U"
Disable the write protection of the desired pages 
.SS "#define OB_WRPSTATE_ENABLE   0x01U"
Enable the write protection of the desired pagess 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
