.TH "FLASHEx_OB_nRST_STDBY" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_OB_nRST_STDBY
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOB_STDBY_NO_RST\fP   ((uint16_t)0x0004)"
.br
.ti -1c
.RI "#define \fBOB_STDBY_RST\fP   ((uint16_t)0x0000)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OB_STDBY_NO_RST   ((uint16_t)0x0004)"
No reset generated when entering in STANDBY 
.SS "#define OB_STDBY_RST   ((uint16_t)0x0000)"
Reset generated when entering in STANDBY 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
