.TH "FLASH_Flag_definition" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Flag_definition \- Flag definition\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLASH_FLAG_BSY\fP   \fBFLASH_SR_BSY\fP"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_PGERR\fP   \fBFLASH_SR_PGERR\fP"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_WRPERR\fP   \fBFLASH_SR_WRPRTERR\fP"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_EOP\fP   \fBFLASH_SR_EOP\fP"
.br
.ti -1c
.RI "#define \fBFLASH_FLAG_OPTVERR\fP   ((\fBOBR_REG_INDEX\fP << 8U | \fBFLASH_OBR_OPTERR\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Flag definition\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASH_FLAG_BSY   \fBFLASH_SR_BSY\fP"
FLASH Busy flag 
.br
 
.SS "#define FLASH_FLAG_EOP   \fBFLASH_SR_EOP\fP"
FLASH End of Operation flag 
.br
 
.SS "#define FLASH_FLAG_OPTVERR   ((\fBOBR_REG_INDEX\fP << 8U | \fBFLASH_OBR_OPTERR\fP))"
Option Byte Error 
.br
 
.SS "#define FLASH_FLAG_PGERR   \fBFLASH_SR_PGERR\fP"
FLASH Programming error flag 
.br
 
.SS "#define FLASH_FLAG_WRPERR   \fBFLASH_SR_WRPRTERR\fP"
FLASH Write protected error flag 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
