.TH "FLASH_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_TypeDef \- FLASH Registers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBACR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBKEYR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOPTKEYR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRESERVED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOBR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWRPR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FLASH Registers\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::ACR"

.SS "\fB__IO\fP uint32_t FLASH_TypeDef::AR"

.SS "\fB__IO\fP uint32_t FLASH_TypeDef::CR"

.SS "\fB__IO\fP uint32_t FLASH_TypeDef::KEYR"

.SS "\fB__IO\fP uint32_t FLASH_TypeDef::OBR"

.SS "\fB__IO\fP uint32_t FLASH_TypeDef::OPTKEYR"

.SS "\fB__IO\fP uint32_t FLASH_TypeDef::RESERVED"

.SS "\fB__IO\fP uint32_t FLASH_TypeDef::SR"

.SS "\fB__IO\fP uint32_t FLASH_TypeDef::WRPR"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
