.TH "FLASHEx_OB_Type" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_OB_Type
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPTIONBYTE_WRP\fP   0x01U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_RDP\fP   0x02U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_USER\fP   0x04U"
.br
.ti -1c
.RI "#define \fBOPTIONBYTE_DATA\fP   0x08U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OPTIONBYTE_DATA   0x08U"
DATA option byte configuration 
.SS "#define OPTIONBYTE_RDP   0x02U"
RDP option byte configuration 
.SS "#define OPTIONBYTE_USER   0x04U"
USER option byte configuration 
.SS "#define OPTIONBYTE_WRP   0x01U"
WRP option byte configuration 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
