.TH "FLASH_Error_Codes" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Error_Codes
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_NONE\fP   0x00U"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_PROG\fP   0x01U"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_WRP\fP   0x02U"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_ERROR_OPTV\fP   0x04U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_FLASH_ERROR_NONE   0x00U"
No error 
.SS "#define HAL_FLASH_ERROR_OPTV   0x04U"
Option validity error 
.SS "#define HAL_FLASH_ERROR_PROG   0x01U"
Programming error 
.SS "#define HAL_FLASH_ERROR_WRP   0x02U"
Write protection error 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
