.TH "FLASHEx_Exported_Functions_Group1" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_Erase\fP (\fBFLASH_EraseInitTypeDef\fP *pEraseInit, uint32_t *PageError)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_FLASHEx_Erase_IT\fP (\fBFLASH_EraseInitTypeDef\fP *pEraseInit)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_FLASHEx_Erase (\fBFLASH_EraseInitTypeDef\fP * pEraseInit, uint32_t * PageError)"

.SS "\fBHAL_StatusTypeDef\fP HAL_FLASHEx_Erase_IT (\fBFLASH_EraseInitTypeDef\fP * pEraseInit)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
