.TH "FLASHEx_Private_Constants" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Private_Constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLASH_SIZE_DATA_REGISTER\fP   0x1FFFF7E0U"
.br
.ti -1c
.RI "#define \fBOBR_REG_INDEX\fP   1U"
.br
.ti -1c
.RI "#define \fBSR_FLAG_MASK\fP   ((uint32_t)(\fBFLASH_SR_BSY\fP | \fBFLASH_SR_PGERR\fP | \fBFLASH_SR_WRPRTERR\fP | \fBFLASH_SR_EOP\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASH_SIZE_DATA_REGISTER   0x1FFFF7E0U"

.SS "#define OBR_REG_INDEX   1U"

.SS "#define SR_FLAG_MASK   ((uint32_t)(\fBFLASH_SR_BSY\fP | \fBFLASH_SR_PGERR\fP | \fBFLASH_SR_WRPRTERR\fP | \fBFLASH_SR_EOP\fP))"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
