.TH "FLASHEx_Type_Erase" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASHEx_Type_Erase
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFLASH_TYPEERASE_PAGES\fP   0x00U"
.br
.ti -1c
.RI "#define \fBFLASH_TYPEERASE_MASSERASE\fP   0x02U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASH_TYPEERASE_MASSERASE   0x02U"
Flash mass erase activation 
.SS "#define FLASH_TYPEERASE_PAGES   0x00U"
Pages erase only 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
