.TH "FPU_Type" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FPU_Type \- Structure type to access the Floating Point Unit (FPU)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_cm7\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [1U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBFPCCR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBFPCAR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBFPDSCR\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBMVFR0\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBMVFR1\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBMVFR2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Floating Point Unit (FPU)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
