.TH "GPIOEx_Exported_Constants" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIOEx_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBEVENTOUT Cortex Configuration\fP"
.br
.RI "This section propose definition to use the Cortex EVENTOUT signal\&. "
.ti -1c
.RI "\fBAlternate Function Remapping\fP"
.br
.RI "This section propose definition to remap the alternate function to some other port/pins\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
