.TH "GPIO_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_TypeDef \- General Purpose I/O\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCRH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBODR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBSRR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBRR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLCKR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
General Purpose I/O\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t GPIO_TypeDef::BRR"

.SS "\fB__IO\fP uint32_t GPIO_TypeDef::BSRR"

.SS "\fB__IO\fP uint32_t GPIO_TypeDef::CRH"

.SS "\fB__IO\fP uint32_t GPIO_TypeDef::CRL"

.SS "\fB__IO\fP uint32_t GPIO_TypeDef::IDR"

.SS "\fB__IO\fP uint32_t GPIO_TypeDef::LCKR"

.SS "\fB__IO\fP uint32_t GPIO_TypeDef::ODR"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
