.TH "GPIOEx_EVENTOUT_PIN" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIOEx_EVENTOUT_PIN
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_0\fP   \fBAFIO_EVCR_PIN_PX0\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_1\fP   \fBAFIO_EVCR_PIN_PX1\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_2\fP   \fBAFIO_EVCR_PIN_PX2\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_3\fP   \fBAFIO_EVCR_PIN_PX3\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_4\fP   \fBAFIO_EVCR_PIN_PX4\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_5\fP   \fBAFIO_EVCR_PIN_PX5\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_6\fP   \fBAFIO_EVCR_PIN_PX6\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_7\fP   \fBAFIO_EVCR_PIN_PX7\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_8\fP   \fBAFIO_EVCR_PIN_PX8\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_9\fP   \fBAFIO_EVCR_PIN_PX9\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_10\fP   \fBAFIO_EVCR_PIN_PX10\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_11\fP   \fBAFIO_EVCR_PIN_PX11\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_12\fP   \fBAFIO_EVCR_PIN_PX12\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_13\fP   \fBAFIO_EVCR_PIN_PX13\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_14\fP   \fBAFIO_EVCR_PIN_PX14\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PIN_15\fP   \fBAFIO_EVCR_PIN_PX15\fP"
.br
.ti -1c
.RI "#define \fBIS_AFIO_EVENTOUT_PIN\fP(__PIN__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define AFIO_EVENTOUT_PIN_0   \fBAFIO_EVCR_PIN_PX0\fP"
EVENTOUT on pin 0 
.SS "#define AFIO_EVENTOUT_PIN_1   \fBAFIO_EVCR_PIN_PX1\fP"
EVENTOUT on pin 1 
.SS "#define AFIO_EVENTOUT_PIN_10   \fBAFIO_EVCR_PIN_PX10\fP"
EVENTOUT on pin 10 
.SS "#define AFIO_EVENTOUT_PIN_11   \fBAFIO_EVCR_PIN_PX11\fP"
EVENTOUT on pin 11 
.SS "#define AFIO_EVENTOUT_PIN_12   \fBAFIO_EVCR_PIN_PX12\fP"
EVENTOUT on pin 12 
.SS "#define AFIO_EVENTOUT_PIN_13   \fBAFIO_EVCR_PIN_PX13\fP"
EVENTOUT on pin 13 
.SS "#define AFIO_EVENTOUT_PIN_14   \fBAFIO_EVCR_PIN_PX14\fP"
EVENTOUT on pin 14 
.SS "#define AFIO_EVENTOUT_PIN_15   \fBAFIO_EVCR_PIN_PX15\fP"
EVENTOUT on pin 15 
.SS "#define AFIO_EVENTOUT_PIN_2   \fBAFIO_EVCR_PIN_PX2\fP"
EVENTOUT on pin 2 
.SS "#define AFIO_EVENTOUT_PIN_3   \fBAFIO_EVCR_PIN_PX3\fP"
EVENTOUT on pin 3 
.SS "#define AFIO_EVENTOUT_PIN_4   \fBAFIO_EVCR_PIN_PX4\fP"
EVENTOUT on pin 4 
.SS "#define AFIO_EVENTOUT_PIN_5   \fBAFIO_EVCR_PIN_PX5\fP"
EVENTOUT on pin 5 
.SS "#define AFIO_EVENTOUT_PIN_6   \fBAFIO_EVCR_PIN_PX6\fP"
EVENTOUT on pin 6 
.SS "#define AFIO_EVENTOUT_PIN_7   \fBAFIO_EVCR_PIN_PX7\fP"
EVENTOUT on pin 7 
.SS "#define AFIO_EVENTOUT_PIN_8   \fBAFIO_EVCR_PIN_PX8\fP"
EVENTOUT on pin 8 
.SS "#define AFIO_EVENTOUT_PIN_9   \fBAFIO_EVCR_PIN_PX9\fP"
EVENTOUT on pin 9 
.SS "#define IS_AFIO_EVENTOUT_PIN(__PIN__)"
\fBValue:\fP
.PP
.nf
(((__PIN__) == AFIO_EVENTOUT_PIN_0) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_1) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_2) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_3) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_4) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_5) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_6) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_7) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_8) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_9) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_10) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_11) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_12) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_13) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_14) || \
                                       ((__PIN__) == AFIO_EVENTOUT_PIN_15))
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
