.TH "GPIOEx_EVENTOUT_PORT" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIOEx_EVENTOUT_PORT
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PORT_A\fP   \fBAFIO_EVCR_PORT_PA\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PORT_B\fP   \fBAFIO_EVCR_PORT_PB\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PORT_C\fP   \fBAFIO_EVCR_PORT_PC\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PORT_D\fP   \fBAFIO_EVCR_PORT_PD\fP"
.br
.ti -1c
.RI "#define \fBAFIO_EVENTOUT_PORT_E\fP   \fBAFIO_EVCR_PORT_PE\fP"
.br
.ti -1c
.RI "#define \fBIS_AFIO_EVENTOUT_PORT\fP(__PORT__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define AFIO_EVENTOUT_PORT_A   \fBAFIO_EVCR_PORT_PA\fP"
EVENTOUT on port A 
.SS "#define AFIO_EVENTOUT_PORT_B   \fBAFIO_EVCR_PORT_PB\fP"
EVENTOUT on port B 
.SS "#define AFIO_EVENTOUT_PORT_C   \fBAFIO_EVCR_PORT_PC\fP"
EVENTOUT on port C 
.SS "#define AFIO_EVENTOUT_PORT_D   \fBAFIO_EVCR_PORT_PD\fP"
EVENTOUT on port D 
.SS "#define AFIO_EVENTOUT_PORT_E   \fBAFIO_EVCR_PORT_PE\fP"
EVENTOUT on port E 
.SS "#define IS_AFIO_EVENTOUT_PORT(__PORT__)"
\fBValue:\fP
.PP
.nf
(((__PORT__) == AFIO_EVENTOUT_PORT_A) || \
                                         ((__PORT__) == AFIO_EVENTOUT_PORT_B) || \
                                         ((__PORT__) == AFIO_EVENTOUT_PORT_C) || \
                                         ((__PORT__) == AFIO_EVENTOUT_PORT_D) || \
                                         ((__PORT__) == AFIO_EVENTOUT_PORT_E))
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
