.TH "GPIO_pins_define" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_pins_define
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGPIO_PIN_0\fP   ((uint16_t)0x0001)  /* Pin 0 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_1\fP   ((uint16_t)0x0002)  /* Pin 1 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_2\fP   ((uint16_t)0x0004)  /* Pin 2 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_3\fP   ((uint16_t)0x0008)  /* Pin 3 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_4\fP   ((uint16_t)0x0010)  /* Pin 4 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_5\fP   ((uint16_t)0x0020)  /* Pin 5 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_6\fP   ((uint16_t)0x0040)  /* Pin 6 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_7\fP   ((uint16_t)0x0080)  /* Pin 7 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_8\fP   ((uint16_t)0x0100)  /* Pin 8 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_9\fP   ((uint16_t)0x0200)  /* Pin 9 selected    */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_10\fP   ((uint16_t)0x0400)  /* Pin 10 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_11\fP   ((uint16_t)0x0800)  /* Pin 11 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_12\fP   ((uint16_t)0x1000)  /* Pin 12 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_13\fP   ((uint16_t)0x2000)  /* Pin 13 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_14\fP   ((uint16_t)0x4000)  /* Pin 14 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_15\fP   ((uint16_t)0x8000)  /* Pin 15 selected   */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_All\fP   ((uint16_t)0xFFFF)  /* All pins selected */"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_MASK\fP   0x0000FFFFu /* PIN mask for assert test */"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define GPIO_PIN_0   ((uint16_t)0x0001)  /* Pin 0 selected    */"

.SS "#define GPIO_PIN_1   ((uint16_t)0x0002)  /* Pin 1 selected    */"

.SS "#define GPIO_PIN_10   ((uint16_t)0x0400)  /* Pin 10 selected   */"

.SS "#define GPIO_PIN_11   ((uint16_t)0x0800)  /* Pin 11 selected   */"

.SS "#define GPIO_PIN_12   ((uint16_t)0x1000)  /* Pin 12 selected   */"

.SS "#define GPIO_PIN_13   ((uint16_t)0x2000)  /* Pin 13 selected   */"

.SS "#define GPIO_PIN_14   ((uint16_t)0x4000)  /* Pin 14 selected   */"

.SS "#define GPIO_PIN_15   ((uint16_t)0x8000)  /* Pin 15 selected   */"

.SS "#define GPIO_PIN_2   ((uint16_t)0x0004)  /* Pin 2 selected    */"

.SS "#define GPIO_PIN_3   ((uint16_t)0x0008)  /* Pin 3 selected    */"

.SS "#define GPIO_PIN_4   ((uint16_t)0x0010)  /* Pin 4 selected    */"

.SS "#define GPIO_PIN_5   ((uint16_t)0x0020)  /* Pin 5 selected    */"

.SS "#define GPIO_PIN_6   ((uint16_t)0x0040)  /* Pin 6 selected    */"

.SS "#define GPIO_PIN_7   ((uint16_t)0x0080)  /* Pin 7 selected    */"

.SS "#define GPIO_PIN_8   ((uint16_t)0x0100)  /* Pin 8 selected    */"

.SS "#define GPIO_PIN_9   ((uint16_t)0x0200)  /* Pin 9 selected    */"

.SS "#define GPIO_PIN_All   ((uint16_t)0xFFFF)  /* All pins selected */"

.SS "#define GPIO_PIN_MASK   0x0000FFFFu /* PIN mask for assert test */"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
