.TH "HAL_DMA_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_DMA_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_REMAPDMA_ADC_DMA_CH2\fP   DMA_REMAP_ADC_DMA_CH2"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_USART1_TX_DMA_CH4\fP   DMA_REMAP_USART1_TX_DMA_CH4"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_USART1_RX_DMA_CH5\fP   DMA_REMAP_USART1_RX_DMA_CH5"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM16_DMA_CH4\fP   DMA_REMAP_TIM16_DMA_CH4"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM17_DMA_CH2\fP   DMA_REMAP_TIM17_DMA_CH2"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_USART3_DMA_CH32\fP   DMA_REMAP_USART3_DMA_CH32"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM16_DMA_CH6\fP   DMA_REMAP_TIM16_DMA_CH6"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM17_DMA_CH7\fP   DMA_REMAP_TIM17_DMA_CH7"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_SPI2_DMA_CH67\fP   DMA_REMAP_SPI2_DMA_CH67"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_USART2_DMA_CH67\fP   DMA_REMAP_USART2_DMA_CH67"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_I2C1_DMA_CH76\fP   DMA_REMAP_I2C1_DMA_CH76"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM1_DMA_CH6\fP   DMA_REMAP_TIM1_DMA_CH6"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM2_DMA_CH7\fP   DMA_REMAP_TIM2_DMA_CH7"
.br
.ti -1c
.RI "#define \fBHAL_REMAPDMA_TIM3_DMA_CH6\fP   DMA_REMAP_TIM3_DMA_CH6"
.br
.ti -1c
.RI "#define \fBIS_HAL_REMAPDMA\fP   IS_DMA_REMAP"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPDMA_CHANNEL_ENABLE\fP   __HAL_DMA_REMAP_CHANNEL_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_REMAPDMA_CHANNEL_DISABLE\fP   __HAL_DMA_REMAP_CHANNEL_DISABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_REMAPDMA_CHANNEL_DISABLE   __HAL_DMA_REMAP_CHANNEL_DISABLE"

.SS "#define __HAL_REMAPDMA_CHANNEL_ENABLE   __HAL_DMA_REMAP_CHANNEL_ENABLE"

.SS "#define HAL_REMAPDMA_ADC_DMA_CH2   DMA_REMAP_ADC_DMA_CH2"

.SS "#define HAL_REMAPDMA_I2C1_DMA_CH76   DMA_REMAP_I2C1_DMA_CH76"

.SS "#define HAL_REMAPDMA_SPI2_DMA_CH67   DMA_REMAP_SPI2_DMA_CH67"

.SS "#define HAL_REMAPDMA_TIM16_DMA_CH4   DMA_REMAP_TIM16_DMA_CH4"

.SS "#define HAL_REMAPDMA_TIM16_DMA_CH6   DMA_REMAP_TIM16_DMA_CH6"

.SS "#define HAL_REMAPDMA_TIM17_DMA_CH2   DMA_REMAP_TIM17_DMA_CH2"

.SS "#define HAL_REMAPDMA_TIM17_DMA_CH7   DMA_REMAP_TIM17_DMA_CH7"

.SS "#define HAL_REMAPDMA_TIM1_DMA_CH6   DMA_REMAP_TIM1_DMA_CH6"

.SS "#define HAL_REMAPDMA_TIM2_DMA_CH7   DMA_REMAP_TIM2_DMA_CH7"

.SS "#define HAL_REMAPDMA_TIM3_DMA_CH6   DMA_REMAP_TIM3_DMA_CH6"

.SS "#define HAL_REMAPDMA_USART1_RX_DMA_CH5   DMA_REMAP_USART1_RX_DMA_CH5"

.SS "#define HAL_REMAPDMA_USART1_TX_DMA_CH4   DMA_REMAP_USART1_TX_DMA_CH4"

.SS "#define HAL_REMAPDMA_USART2_DMA_CH67   DMA_REMAP_USART2_DMA_CH67"

.SS "#define HAL_REMAPDMA_USART3_DMA_CH32   DMA_REMAP_USART3_DMA_CH32"

.SS "#define IS_HAL_REMAPDMA   IS_DMA_REMAP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
