.TH "HAL_Exported_Functions_Group1" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_Init\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DeInit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_MspInit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_MspDeInit\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_InitTick\fP (uint32_t TickPriority)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_DeInit (void)"

.SS "\fBHAL_StatusTypeDef\fP HAL_Init (void)"

.SS "\fBHAL_StatusTypeDef\fP HAL_InitTick (uint32_t TickPriority)"

.SS "void HAL_MspDeInit (void)"

.SS "void HAL_MspInit (void)"
File Name : \fBstm32f1xx_hal_msp\&.c\fP Description : This file provides code for the MSP Initialization and de-Initialization codes\&.
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2020 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause Initializes the Global MSP\&. NOJTAG: JTAG-DP Disabled and SW-DP Enabled
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
