.TH "HAL_SMBUS_Aliased_Functions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMBUS_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_SMBUS_Slave_Listen_IT\fP   HAL_SMBUS_EnableListen_IT"
.br
.ti -1c
.RI "#define \fBHAL_SMBUS_SlaveAddrCallback\fP   HAL_SMBUS_AddrCallback"
.br
.ti -1c
.RI "#define \fBHAL_SMBUS_SlaveListenCpltCallback\fP   HAL_SMBUS_ListenCpltCallback"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_SMBUS_Slave_Listen_IT   HAL_SMBUS_EnableListen_IT"

.SS "#define HAL_SMBUS_SlaveAddrCallback   HAL_SMBUS_AddrCallback"

.SS "#define HAL_SMBUS_SlaveListenCpltCallback   HAL_SMBUS_ListenCpltCallback"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
