.TH "HAL_COMP_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_COMP_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOMP_WINDOWMODE_DISABLED\fP   COMP_WINDOWMODE_DISABLE"
.br
.ti -1c
.RI "#define \fBCOMP_WINDOWMODE_ENABLED\fP   COMP_WINDOWMODE_ENABLE"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP1_EVENT\fP   COMP_EXTI_LINE_COMP1"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP2_EVENT\fP   COMP_EXTI_LINE_COMP2"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP3_EVENT\fP   COMP_EXTI_LINE_COMP3"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP4_EVENT\fP   COMP_EXTI_LINE_COMP4"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP5_EVENT\fP   COMP_EXTI_LINE_COMP5"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP6_EVENT\fP   COMP_EXTI_LINE_COMP6"
.br
.ti -1c
.RI "#define \fBCOMP_EXTI_LINE_COMP7_EVENT\fP   COMP_EXTI_LINE_COMP7"
.br
.ti -1c
.RI "#define \fBCOMP_OUTPUT_COMP6TIM2OCREFCLR\fP   COMP_OUTPUT_COMP6_TIM2OCREFCLR"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define COMP_EXTI_LINE_COMP1_EVENT   COMP_EXTI_LINE_COMP1"

.SS "#define COMP_EXTI_LINE_COMP2_EVENT   COMP_EXTI_LINE_COMP2"

.SS "#define COMP_EXTI_LINE_COMP3_EVENT   COMP_EXTI_LINE_COMP3"

.SS "#define COMP_EXTI_LINE_COMP4_EVENT   COMP_EXTI_LINE_COMP4"

.SS "#define COMP_EXTI_LINE_COMP5_EVENT   COMP_EXTI_LINE_COMP5"

.SS "#define COMP_EXTI_LINE_COMP6_EVENT   COMP_EXTI_LINE_COMP6"

.SS "#define COMP_EXTI_LINE_COMP7_EVENT   COMP_EXTI_LINE_COMP7"

.SS "#define COMP_OUTPUT_COMP6TIM2OCREFCLR   COMP_OUTPUT_COMP6_TIM2OCREFCLR"

.SS "#define COMP_WINDOWMODE_DISABLED   COMP_WINDOWMODE_DISABLE"

.SS "#define COMP_WINDOWMODE_ENABLED   COMP_WINDOWMODE_ENABLE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
