.TH "HAL_SAI_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SAI_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSAI_OUTPUTDRIVE_DISABLED\fP   SAI_OUTPUTDRIVE_DISABLE"
.br
.ti -1c
.RI "#define \fBSAI_OUTPUTDRIVE_ENABLED\fP   SAI_OUTPUTDRIVE_ENABLE"
.br
.ti -1c
.RI "#define \fBSAI_MASTERDIVIDER_ENABLED\fP   SAI_MASTERDIVIDER_ENABLE"
.br
.ti -1c
.RI "#define \fBSAI_MASTERDIVIDER_DISABLED\fP   SAI_MASTERDIVIDER_DISABLE"
.br
.ti -1c
.RI "#define \fBSAI_STREOMODE\fP   SAI_STEREOMODE"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_Empty\fP   SAI_FIFOSTATUS_EMPTY"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_Less1QuarterFull\fP   SAI_FIFOSTATUS_LESS1QUARTERFULL"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_1QuarterFull\fP   SAI_FIFOSTATUS_1QUARTERFULL"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_HalfFull\fP   SAI_FIFOSTATUS_HALFFULL"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_3QuartersFull\fP   SAI_FIFOSTATUS_3QUARTERFULL"
.br
.ti -1c
.RI "#define \fBSAI_FIFOStatus_Full\fP   SAI_FIFOSTATUS_FULL"
.br
.ti -1c
.RI "#define \fBIS_SAI_BLOCK_MONO_STREO_MODE\fP   IS_SAI_BLOCK_MONO_STEREO_MODE"
.br
.ti -1c
.RI "#define \fBSAI_SYNCHRONOUS_EXT\fP   SAI_SYNCHRONOUS_EXT_SAI1"
.br
.ti -1c
.RI "#define \fBSAI_SYNCEXT_IN_ENABLE\fP   SAI_SYNCEXT_OUTBLOCKA_ENABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_SAI_BLOCK_MONO_STREO_MODE   IS_SAI_BLOCK_MONO_STEREO_MODE"

.SS "#define SAI_FIFOStatus_1QuarterFull   SAI_FIFOSTATUS_1QUARTERFULL"

.SS "#define SAI_FIFOStatus_3QuartersFull   SAI_FIFOSTATUS_3QUARTERFULL"

.SS "#define SAI_FIFOStatus_Empty   SAI_FIFOSTATUS_EMPTY"

.SS "#define SAI_FIFOStatus_Full   SAI_FIFOSTATUS_FULL"

.SS "#define SAI_FIFOStatus_HalfFull   SAI_FIFOSTATUS_HALFFULL"

.SS "#define SAI_FIFOStatus_Less1QuarterFull   SAI_FIFOSTATUS_LESS1QUARTERFULL"

.SS "#define SAI_MASTERDIVIDER_DISABLED   SAI_MASTERDIVIDER_DISABLE"

.SS "#define SAI_MASTERDIVIDER_ENABLED   SAI_MASTERDIVIDER_ENABLE"

.SS "#define SAI_OUTPUTDRIVE_DISABLED   SAI_OUTPUTDRIVE_DISABLE"

.SS "#define SAI_OUTPUTDRIVE_ENABLED   SAI_OUTPUTDRIVE_ENABLE"

.SS "#define SAI_STREOMODE   SAI_STEREOMODE"

.SS "#define SAI_SYNCEXT_IN_ENABLE   SAI_SYNCEXT_OUTBLOCKA_ENABLE"

.SS "#define SAI_SYNCHRONOUS_EXT   SAI_SYNCHRONOUS_EXT_SAI1"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
