.TH "HAL_TIM_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_TIM_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_TIM_SetICPrescalerValue\fP   \fBTIM_SET_ICPRESCALERVALUE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_ResetICPrescalerValue\fP   \fBTIM_RESET_ICPRESCALERVALUE\fP"
.br
.ti -1c
.RI "#define \fBTIM_GET_ITSTATUS\fP   \fB__HAL_TIM_GET_IT_SOURCE\fP"
.br
.ti -1c
.RI "#define \fBTIM_GET_CLEAR_IT\fP   \fB__HAL_TIM_CLEAR_IT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GET_ITSTATUS\fP   \fB__HAL_TIM_GET_IT_SOURCE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_DIRECTION_STATUS\fP   \fB__HAL_TIM_IS_TIM_COUNTING_DOWN\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_PRESCALER\fP   \fB__HAL_TIM_SET_PRESCALER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetCounter\fP   \fB__HAL_TIM_SET_COUNTER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetCounter\fP   \fB__HAL_TIM_GET_COUNTER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetAutoreload\fP   \fB__HAL_TIM_SET_AUTORELOAD\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetAutoreload\fP   \fB__HAL_TIM_GET_AUTORELOAD\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetClockDivision\fP   \fB__HAL_TIM_SET_CLOCKDIVISION\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetClockDivision\fP   \fB__HAL_TIM_GET_CLOCKDIVISION\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetICPrescaler\fP   \fB__HAL_TIM_SET_ICPRESCALER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetICPrescaler\fP   \fB__HAL_TIM_GET_ICPRESCALER\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_SetCompare\fP   \fB__HAL_TIM_SET_COMPARE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_TIM_GetCompare\fP   \fB__HAL_TIM_GET_COMPARE\fP"
.br
.ti -1c
.RI "#define \fBTIM_BREAKINPUTSOURCE_DFSDM\fP   TIM_BREAKINPUTSOURCE_DFSDM1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_TIM_DIRECTION_STATUS   \fB__HAL_TIM_IS_TIM_COUNTING_DOWN\fP"

.SS "#define __HAL_TIM_GET_ITSTATUS   \fB__HAL_TIM_GET_IT_SOURCE\fP"

.SS "#define __HAL_TIM_GetAutoreload   \fB__HAL_TIM_GET_AUTORELOAD\fP"

.SS "#define __HAL_TIM_GetClockDivision   \fB__HAL_TIM_GET_CLOCKDIVISION\fP"

.SS "#define __HAL_TIM_GetCompare   \fB__HAL_TIM_GET_COMPARE\fP"

.SS "#define __HAL_TIM_GetCounter   \fB__HAL_TIM_GET_COUNTER\fP"

.SS "#define __HAL_TIM_GetICPrescaler   \fB__HAL_TIM_GET_ICPRESCALER\fP"

.SS "#define __HAL_TIM_PRESCALER   \fB__HAL_TIM_SET_PRESCALER\fP"

.SS "#define __HAL_TIM_ResetICPrescalerValue   \fBTIM_RESET_ICPRESCALERVALUE\fP"

.SS "#define __HAL_TIM_SetAutoreload   \fB__HAL_TIM_SET_AUTORELOAD\fP"

.SS "#define __HAL_TIM_SetClockDivision   \fB__HAL_TIM_SET_CLOCKDIVISION\fP"

.SS "#define __HAL_TIM_SetCompare   \fB__HAL_TIM_SET_COMPARE\fP"

.SS "#define __HAL_TIM_SetCounter   \fB__HAL_TIM_SET_COUNTER\fP"

.SS "#define __HAL_TIM_SetICPrescaler   \fB__HAL_TIM_SET_ICPRESCALER\fP"

.SS "#define __HAL_TIM_SetICPrescalerValue   \fBTIM_SET_ICPRESCALERVALUE\fP"

.SS "#define TIM_BREAKINPUTSOURCE_DFSDM   TIM_BREAKINPUTSOURCE_DFSDM1"

.SS "#define TIM_GET_CLEAR_IT   \fB__HAL_TIM_CLEAR_IT\fP"

.SS "#define TIM_GET_ITSTATUS   \fB__HAL_TIM_GET_IT_SOURCE\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
