.TH "HAL_HASH_Aliased_Functions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_HASH_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_HASH_STATETypeDef\fP   HAL_HASH_StateTypeDef"
.br
.ti -1c
.RI "#define \fBHAL_HASHPhaseTypeDef\fP   HAL_HASH_PhaseTypeDef"
.br
.ti -1c
.RI "#define \fBHAL_HMAC_MD5_Finish\fP   HAL_HASH_MD5_Finish"
.br
.ti -1c
.RI "#define \fBHAL_HMAC_SHA1_Finish\fP   HAL_HASH_SHA1_Finish"
.br
.ti -1c
.RI "#define \fBHAL_HMAC_SHA224_Finish\fP   HAL_HASH_SHA224_Finish"
.br
.ti -1c
.RI "#define \fBHAL_HMAC_SHA256_Finish\fP   HAL_HASH_SHA256_Finish"
.br
.ti -1c
.RI "#define \fBHASH_AlgoSelection_SHA1\fP   HASH_ALGOSELECTION_SHA1"
.br
.ti -1c
.RI "#define \fBHASH_AlgoSelection_SHA224\fP   HASH_ALGOSELECTION_SHA224"
.br
.ti -1c
.RI "#define \fBHASH_AlgoSelection_SHA256\fP   HASH_ALGOSELECTION_SHA256"
.br
.ti -1c
.RI "#define \fBHASH_AlgoSelection_MD5\fP   HASH_ALGOSELECTION_MD5"
.br
.ti -1c
.RI "#define \fBHASH_AlgoMode_HASH\fP   HASH_ALGOMODE_HASH"
.br
.ti -1c
.RI "#define \fBHASH_AlgoMode_HMAC\fP   HASH_ALGOMODE_HMAC"
.br
.ti -1c
.RI "#define \fBHASH_HMACKeyType_ShortKey\fP   HASH_HMAC_KEYTYPE_SHORTKEY"
.br
.ti -1c
.RI "#define \fBHASH_HMACKeyType_LongKey\fP   HASH_HMAC_KEYTYPE_LONGKEY"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_HASH_STATETypeDef   HAL_HASH_StateTypeDef"

.SS "#define HAL_HASHPhaseTypeDef   HAL_HASH_PhaseTypeDef"

.SS "#define HAL_HMAC_MD5_Finish   HAL_HASH_MD5_Finish"

.SS "#define HAL_HMAC_SHA1_Finish   HAL_HASH_SHA1_Finish"

.SS "#define HAL_HMAC_SHA224_Finish   HAL_HASH_SHA224_Finish"

.SS "#define HAL_HMAC_SHA256_Finish   HAL_HASH_SHA256_Finish"

.SS "#define HASH_AlgoMode_HASH   HASH_ALGOMODE_HASH"

.SS "#define HASH_AlgoMode_HMAC   HASH_ALGOMODE_HMAC"

.SS "#define HASH_AlgoSelection_MD5   HASH_ALGOSELECTION_MD5"

.SS "#define HASH_AlgoSelection_SHA1   HASH_ALGOSELECTION_SHA1"

.SS "#define HASH_AlgoSelection_SHA224   HASH_ALGOSELECTION_SHA224"

.SS "#define HASH_AlgoSelection_SHA256   HASH_ALGOSELECTION_SHA256"

.SS "#define HASH_HMACKeyType_LongKey   HASH_HMAC_KEYTYPE_LONGKEY"

.SS "#define HASH_HMACKeyType_ShortKey   HASH_HMAC_KEYTYPE_SHORTKEY"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
