.TH "HAL_RTC_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_RTC_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RTC_CLEAR_FLAG\fP   \fB__HAL_RTC_EXTI_CLEAR_FLAG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_RTC_DISABLE_IT\fP   \fB__HAL_RTC_EXTI_DISABLE_IT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_RTC_ENABLE_IT\fP   \fB__HAL_RTC_EXTI_ENABLE_IT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_RTC_EXTI_CLEAR_FLAG\fP(__EXTI_LINE__)"
.br
.ti -1c
.RI "#define \fB__HAL_RTC_EXTI_ENABLE_IT\fP(__EXTI_LINE__)"
.br
.ti -1c
.RI "#define \fB__HAL_RTC_EXTI_DISABLE_IT\fP(__EXTI_LINE__)"
.br
.ti -1c
.RI "#define \fB__HAL_RTC_EXTI_GET_FLAG\fP(__EXTI_LINE__)"
.br
.ti -1c
.RI "#define \fB__HAL_RTC_EXTI_GENERATE_SWIT\fP(__EXTI_LINE__)"
.br
.ti -1c
.RI "#define \fBIS_ALARM\fP   IS_RTC_ALARM"
.br
.ti -1c
.RI "#define \fBIS_ALARM_MASK\fP   IS_RTC_ALARM_MASK"
.br
.ti -1c
.RI "#define \fBIS_TAMPER\fP   IS_RTC_TAMPER"
.br
.ti -1c
.RI "#define \fBIS_TAMPER_ERASE_MODE\fP   IS_RTC_TAMPER_ERASE_MODE"
.br
.ti -1c
.RI "#define \fBIS_TAMPER_FILTER\fP   IS_RTC_TAMPER_FILTER"
.br
.ti -1c
.RI "#define \fBIS_TAMPER_INTERRUPT\fP   IS_RTC_TAMPER_INTERRUPT"
.br
.ti -1c
.RI "#define \fBIS_TAMPER_MASKFLAG_STATE\fP   IS_RTC_TAMPER_MASKFLAG_STATE"
.br
.ti -1c
.RI "#define \fBIS_TAMPER_PRECHARGE_DURATION\fP   IS_RTC_TAMPER_PRECHARGE_DURATION"
.br
.ti -1c
.RI "#define \fBIS_TAMPER_PULLUP_STATE\fP   IS_RTC_TAMPER_PULLUP_STATE"
.br
.ti -1c
.RI "#define \fBIS_TAMPER_SAMPLING_FREQ\fP   IS_RTC_TAMPER_SAMPLING_FREQ"
.br
.ti -1c
.RI "#define \fBIS_TAMPER_TIMESTAMPONTAMPER_DETECTION\fP   IS_RTC_TAMPER_TIMESTAMPONTAMPER_DETECTION"
.br
.ti -1c
.RI "#define \fBIS_TAMPER_TRIGGER\fP   IS_RTC_TAMPER_TRIGGER"
.br
.ti -1c
.RI "#define \fBIS_WAKEUP_CLOCK\fP   IS_RTC_WAKEUP_CLOCK"
.br
.ti -1c
.RI "#define \fBIS_WAKEUP_COUNTER\fP   IS_RTC_WAKEUP_COUNTER"
.br
.ti -1c
.RI "#define \fB__RTC_WRITEPROTECTION_ENABLE\fP   __HAL_RTC_WRITEPROTECTION_ENABLE"
.br
.ti -1c
.RI "#define \fB__RTC_WRITEPROTECTION_DISABLE\fP   __HAL_RTC_WRITEPROTECTION_DISABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RTC_CLEAR_FLAG   \fB__HAL_RTC_EXTI_CLEAR_FLAG\fP"

.SS "#define __HAL_RTC_DISABLE_IT   \fB__HAL_RTC_EXTI_DISABLE_IT\fP"

.SS "#define __HAL_RTC_ENABLE_IT   \fB__HAL_RTC_EXTI_ENABLE_IT\fP"

.SS "#define __HAL_RTC_EXTI_CLEAR_FLAG(__EXTI_LINE__)"
\fBValue:\fP
.PP
.nf
(((__EXTI_LINE__) == RTC_EXTI_LINE_ALARM_EVENT) ? __HAL_RTC_ALARM_EXTI_CLEAR_FLAG() : \
                                                   (((__EXTI_LINE__) == RTC_EXTI_LINE_WAKEUPTIMER_EVENT) ? __HAL_RTC_WAKEUPTIMER_EXTI_CLEAR_FLAG() : \
                                                      __HAL_RTC_TAMPER_TIMESTAMP_EXTI_CLEAR_FLAG()))
.fi
.SS "#define __HAL_RTC_EXTI_DISABLE_IT(__EXTI_LINE__)"
\fBValue:\fP
.PP
.nf
(((__EXTI_LINE__) == RTC_EXTI_LINE_ALARM_EVENT) ? __HAL_RTC_ALARM_EXTI_DISABLE_IT() : \
                                                  (((__EXTI_LINE__) == RTC_EXTI_LINE_WAKEUPTIMER_EVENT) ? __HAL_RTC_WAKEUPTIMER_EXTI_DISABLE_IT() : \
                                                      __HAL_RTC_TAMPER_TIMESTAMP_EXTI_DISABLE_IT()))
.fi
.SS "#define __HAL_RTC_EXTI_ENABLE_IT(__EXTI_LINE__)"
\fBValue:\fP
.PP
.nf
(((__EXTI_LINE__)  == RTC_EXTI_LINE_ALARM_EVENT) ? __HAL_RTC_ALARM_EXTI_ENABLE_IT() : \
                                                  (((__EXTI_LINE__) == RTC_EXTI_LINE_WAKEUPTIMER_EVENT) ? __HAL_RTC_WAKEUPTIMER_EXTI_ENABLE_IT() : \
                                                      __HAL_RTC_TAMPER_TIMESTAMP_EXTI_ENABLE_IT()))
.fi
.SS "#define __HAL_RTC_EXTI_GENERATE_SWIT(__EXTI_LINE__)"
\fBValue:\fP
.PP
.nf
(((__EXTI_LINE__) == RTC_EXTI_LINE_ALARM_EVENT) ? __HAL_RTC_ALARM_EXTI_GENERATE_SWIT() : \
                                                      (((__EXTI_LINE__) == RTC_EXTI_LINE_WAKEUPTIMER_EVENT) ? __HAL_RTC_WAKEUPTIMER_EXTI_GENERATE_SWIT() :  \
                                                          __HAL_RTC_TAMPER_TIMESTAMP_EXTI_GENERATE_SWIT()))
.fi
.SS "#define __HAL_RTC_EXTI_GET_FLAG(__EXTI_LINE__)"
\fBValue:\fP
.PP
.nf
(((__EXTI_LINE__) == RTC_EXTI_LINE_ALARM_EVENT) ? __HAL_RTC_ALARM_EXTI_GET_FLAG() : \
                                                  (((__EXTI_LINE__) == RTC_EXTI_LINE_WAKEUPTIMER_EVENT) ? __HAL_RTC_WAKEUPTIMER_EXTI_GET_FLAG() : \
                                                      __HAL_RTC_TAMPER_TIMESTAMP_EXTI_GET_FLAG()))
.fi
.SS "#define __RTC_WRITEPROTECTION_DISABLE   __HAL_RTC_WRITEPROTECTION_DISABLE"

.SS "#define __RTC_WRITEPROTECTION_ENABLE   __HAL_RTC_WRITEPROTECTION_ENABLE"

.SS "#define IS_ALARM   IS_RTC_ALARM"

.SS "#define IS_ALARM_MASK   IS_RTC_ALARM_MASK"

.SS "#define IS_TAMPER   IS_RTC_TAMPER"

.SS "#define IS_TAMPER_ERASE_MODE   IS_RTC_TAMPER_ERASE_MODE"

.SS "#define IS_TAMPER_FILTER   IS_RTC_TAMPER_FILTER"

.SS "#define IS_TAMPER_INTERRUPT   IS_RTC_TAMPER_INTERRUPT"

.SS "#define IS_TAMPER_MASKFLAG_STATE   IS_RTC_TAMPER_MASKFLAG_STATE"

.SS "#define IS_TAMPER_PRECHARGE_DURATION   IS_RTC_TAMPER_PRECHARGE_DURATION"

.SS "#define IS_TAMPER_PULLUP_STATE   IS_RTC_TAMPER_PULLUP_STATE"

.SS "#define IS_TAMPER_SAMPLING_FREQ   IS_RTC_TAMPER_SAMPLING_FREQ"

.SS "#define IS_TAMPER_TIMESTAMPONTAMPER_DETECTION   IS_RTC_TAMPER_TIMESTAMPONTAMPER_DETECTION"

.SS "#define IS_TAMPER_TRIGGER   IS_RTC_TAMPER_TRIGGER"

.SS "#define IS_WAKEUP_CLOCK   IS_RTC_WAKEUP_CLOCK"

.SS "#define IS_WAKEUP_COUNTER   IS_RTC_WAKEUP_COUNTER"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
