.TH "HAL_NAND_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_NAND_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_NAND_Read_Page\fP   HAL_NAND_Read_Page_8b"
.br
.ti -1c
.RI "#define \fBHAL_NAND_Write_Page\fP   HAL_NAND_Write_Page_8b"
.br
.ti -1c
.RI "#define \fBHAL_NAND_Read_SpareArea\fP   HAL_NAND_Read_SpareArea_8b"
.br
.ti -1c
.RI "#define \fBHAL_NAND_Write_SpareArea\fP   HAL_NAND_Write_SpareArea_8b"
.br
.ti -1c
.RI "#define \fBNAND_AddressTypedef\fP   NAND_AddressTypeDef"
.br
.ti -1c
.RI "#define \fB__ARRAY_ADDRESS\fP   ARRAY_ADDRESS"
.br
.ti -1c
.RI "#define \fB__ADDR_1st_CYCLE\fP   ADDR_1ST_CYCLE"
.br
.ti -1c
.RI "#define \fB__ADDR_2nd_CYCLE\fP   ADDR_2ND_CYCLE"
.br
.ti -1c
.RI "#define \fB__ADDR_3rd_CYCLE\fP   ADDR_3RD_CYCLE"
.br
.ti -1c
.RI "#define \fB__ADDR_4th_CYCLE\fP   ADDR_4TH_CYCLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __ADDR_1st_CYCLE   ADDR_1ST_CYCLE"

.SS "#define __ADDR_2nd_CYCLE   ADDR_2ND_CYCLE"

.SS "#define __ADDR_3rd_CYCLE   ADDR_3RD_CYCLE"

.SS "#define __ADDR_4th_CYCLE   ADDR_4TH_CYCLE"

.SS "#define __ARRAY_ADDRESS   ARRAY_ADDRESS"

.SS "#define HAL_NAND_Read_Page   HAL_NAND_Read_Page_8b"

.SS "#define HAL_NAND_Read_SpareArea   HAL_NAND_Read_SpareArea_8b"

.SS "#define HAL_NAND_Write_Page   HAL_NAND_Write_Page_8b"

.SS "#define HAL_NAND_Write_SpareArea   HAL_NAND_Write_SpareArea_8b"

.SS "#define NAND_AddressTypedef   NAND_AddressTypeDef"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
