.TH "HAL_DCMI_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_DCMI_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_DCMI_ERROR_OVF\fP   HAL_DCMI_ERROR_OVR"
.br
.ti -1c
.RI "#define \fBDCMI_IT_OVF\fP   DCMI_IT_OVR"
.br
.ti -1c
.RI "#define \fBDCMI_FLAG_OVFRI\fP   DCMI_FLAG_OVRRI"
.br
.ti -1c
.RI "#define \fBDCMI_FLAG_OVFMI\fP   DCMI_FLAG_OVRMI"
.br
.ti -1c
.RI "#define \fBHAL_DCMI_ConfigCROP\fP   HAL_DCMI_ConfigCrop"
.br
.ti -1c
.RI "#define \fBHAL_DCMI_EnableCROP\fP   HAL_DCMI_EnableCrop"
.br
.ti -1c
.RI "#define \fBHAL_DCMI_DisableCROP\fP   HAL_DCMI_DisableCrop"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DCMI_FLAG_OVFMI   DCMI_FLAG_OVRMI"

.SS "#define DCMI_FLAG_OVFRI   DCMI_FLAG_OVRRI"

.SS "#define DCMI_IT_OVF   DCMI_IT_OVR"

.SS "#define HAL_DCMI_ConfigCROP   HAL_DCMI_ConfigCrop"

.SS "#define HAL_DCMI_DisableCROP   HAL_DCMI_DisableCrop"

.SS "#define HAL_DCMI_EnableCROP   HAL_DCMI_EnableCrop"

.SS "#define HAL_DCMI_ERROR_OVF   HAL_DCMI_ERROR_OVR"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
