.TH "HAL_DAC_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_DAC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDAC1_CHANNEL_1\fP   DAC_CHANNEL_1"
.br
.ti -1c
.RI "#define \fBDAC1_CHANNEL_2\fP   DAC_CHANNEL_2"
.br
.ti -1c
.RI "#define \fBDAC2_CHANNEL_1\fP   DAC_CHANNEL_1"
.br
.ti -1c
.RI "#define \fBDAC_WAVE_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBDAC_WAVE_NOISE\fP   DAC_CR_WAVE1_0"
.br
.ti -1c
.RI "#define \fBDAC_WAVE_TRIANGLE\fP   DAC_CR_WAVE1_1"
.br
.ti -1c
.RI "#define \fBDAC_WAVEGENERATION_NONE\fP   \fBDAC_WAVE_NONE\fP"
.br
.ti -1c
.RI "#define \fBDAC_WAVEGENERATION_NOISE\fP   \fBDAC_WAVE_NOISE\fP"
.br
.ti -1c
.RI "#define \fBDAC_WAVEGENERATION_TRIANGLE\fP   \fBDAC_WAVE_TRIANGLE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DAC1_CHANNEL_1   DAC_CHANNEL_1"

.SS "#define DAC1_CHANNEL_2   DAC_CHANNEL_2"

.SS "#define DAC2_CHANNEL_1   DAC_CHANNEL_1"

.SS "#define DAC_WAVE_NOISE   DAC_CR_WAVE1_0"

.SS "#define DAC_WAVE_NONE   0x00000000U"

.SS "#define DAC_WAVE_TRIANGLE   DAC_CR_WAVE1_1"

.SS "#define DAC_WAVEGENERATION_NOISE   \fBDAC_WAVE_NOISE\fP"

.SS "#define DAC_WAVEGENERATION_NONE   \fBDAC_WAVE_NONE\fP"

.SS "#define DAC_WAVEGENERATION_TRIANGLE   \fBDAC_WAVE_TRIANGLE\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
