.TH "HAL_DAC_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_DAC_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_DHR12R1_ALIGNEMENT\fP   DAC_DHR12R1_ALIGNMENT"
.br
.ti -1c
.RI "#define \fB__HAL_DHR12R2_ALIGNEMENT\fP   DAC_DHR12R2_ALIGNMENT"
.br
.ti -1c
.RI "#define \fB__HAL_DHR12RD_ALIGNEMENT\fP   DAC_DHR12RD_ALIGNMENT"
.br
.ti -1c
.RI "#define \fBIS_DAC_GENERATE_WAVE\fP   \fBIS_DAC_WAVE\fP"
.br
.ti -1c
.RI "#define \fBIS_DAC_WAVE\fP(WAVE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_DHR12R1_ALIGNEMENT   DAC_DHR12R1_ALIGNMENT"

.SS "#define __HAL_DHR12R2_ALIGNEMENT   DAC_DHR12R2_ALIGNMENT"

.SS "#define __HAL_DHR12RD_ALIGNEMENT   DAC_DHR12RD_ALIGNMENT"

.SS "#define IS_DAC_GENERATE_WAVE   \fBIS_DAC_WAVE\fP"

.SS "#define IS_DAC_WAVE(WAVE)"
\fBValue:\fP
.PP
.nf
(((WAVE) == DAC_WAVE_NONE) || \
                          ((WAVE) == DAC_WAVE_NOISE)|| \
                          ((WAVE) == DAC_WAVE_TRIANGLE))
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
