.TH "HAL_I2S_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2S_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2S_STANDARD_PHILLIPS\fP   I2S_STANDARD_PHILIPS"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define I2S_STANDARD_PHILLIPS   I2S_STANDARD_PHILIPS"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
