.TH "HAL_SMBUS_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMBUS_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_SMBUS_RESET_CR1\fP   SMBUS_RESET_CR1"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_RESET_CR2\fP   SMBUS_RESET_CR2"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GENERATE_START\fP   SMBUS_GENERATE_START"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_ADDR_MATCH\fP   SMBUS_GET_ADDR_MATCH"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_DIR\fP   SMBUS_GET_DIR"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_STOP_MODE\fP   SMBUS_GET_STOP_MODE"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_PEC_MODE\fP   SMBUS_GET_PEC_MODE"
.br
.ti -1c
.RI "#define \fB__HAL_SMBUS_GET_ALERT_ENABLED\fP   SMBUS_GET_ALERT_ENABLED"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_SMBUS_GENERATE_START   SMBUS_GENERATE_START"

.SS "#define __HAL_SMBUS_GET_ADDR_MATCH   SMBUS_GET_ADDR_MATCH"

.SS "#define __HAL_SMBUS_GET_ALERT_ENABLED   SMBUS_GET_ALERT_ENABLED"

.SS "#define __HAL_SMBUS_GET_DIR   SMBUS_GET_DIR"

.SS "#define __HAL_SMBUS_GET_PEC_MODE   SMBUS_GET_PEC_MODE"

.SS "#define __HAL_SMBUS_GET_STOP_MODE   SMBUS_GET_STOP_MODE"

.SS "#define __HAL_SMBUS_RESET_CR1   SMBUS_RESET_CR1"

.SS "#define __HAL_SMBUS_RESET_CR2   SMBUS_RESET_CR2"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
