.TH "HAL_SMARTCARD_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMARTCARD_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSMARTCARD_NACK_ENABLED\fP   SMARTCARD_NACK_ENABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_NACK_DISABLED\fP   SMARTCARD_NACK_DISABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_ONEBIT_SAMPLING_DISABLED\fP   SMARTCARD_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_ONEBIT_SAMPLING_ENABLED\fP   SMARTCARD_ONE_BIT_SAMPLE_ENABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_ONEBIT_SAMPLING_DISABLE\fP   SMARTCARD_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_ONEBIT_SAMPLING_ENABLE\fP   SMARTCARD_ONE_BIT_SAMPLE_ENABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_TIMEOUT_DISABLED\fP   SMARTCARD_TIMEOUT_DISABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_TIMEOUT_ENABLED\fP   SMARTCARD_TIMEOUT_ENABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_LASTBIT_DISABLED\fP   SMARTCARD_LASTBIT_DISABLE"
.br
.ti -1c
.RI "#define \fBSMARTCARD_LASTBIT_ENABLED\fP   SMARTCARD_LASTBIT_ENABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SMARTCARD_LASTBIT_DISABLED   SMARTCARD_LASTBIT_DISABLE"

.SS "#define SMARTCARD_LASTBIT_ENABLED   SMARTCARD_LASTBIT_ENABLE"

.SS "#define SMARTCARD_NACK_DISABLED   SMARTCARD_NACK_DISABLE"

.SS "#define SMARTCARD_NACK_ENABLED   SMARTCARD_NACK_ENABLE"

.SS "#define SMARTCARD_ONEBIT_SAMPLING_DISABLE   SMARTCARD_ONE_BIT_SAMPLE_DISABLE"

.SS "#define SMARTCARD_ONEBIT_SAMPLING_DISABLED   SMARTCARD_ONE_BIT_SAMPLE_DISABLE"

.SS "#define SMARTCARD_ONEBIT_SAMPLING_ENABLE   SMARTCARD_ONE_BIT_SAMPLE_ENABLE"

.SS "#define SMARTCARD_ONEBIT_SAMPLING_ENABLED   SMARTCARD_ONE_BIT_SAMPLE_ENABLE"

.SS "#define SMARTCARD_TIMEOUT_DISABLED   SMARTCARD_TIMEOUT_DISABLE"

.SS "#define SMARTCARD_TIMEOUT_ENABLED   SMARTCARD_TIMEOUT_ENABLE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
