.TH "HAL_OPAMP_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_OPAMP_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXPD\fP   OPAMP_CSR_OPAXPD"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_S3SELX\fP   OPAMP_CSR_S3SELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_S4SELX\fP   OPAMP_CSR_S4SELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_S5SELX\fP   OPAMP_CSR_S5SELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_S6SELX\fP   OPAMP_CSR_S6SELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXCAL_L\fP   OPAMP_CSR_OPAXCAL_L"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXCAL_H\fP   OPAMP_CSR_OPAXCAL_H"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXLPM\fP   OPAMP_CSR_OPAXLPM"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_ALL_SWITCHES\fP   OPAMP_CSR_ALL_SWITCHES"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_ANAWSELX\fP   OPAMP_CSR_ANAWSELX"
.br
.ti -1c
.RI "#define \fB__OPAMP_CSR_OPAXCALOUT\fP   OPAMP_CSR_OPAXCALOUT"
.br
.ti -1c
.RI "#define \fB__OPAMP_OFFSET_TRIM_BITSPOSITION\fP   OPAMP_OFFSET_TRIM_BITSPOSITION"
.br
.ti -1c
.RI "#define \fB__OPAMP_OFFSET_TRIM_SET\fP   OPAMP_OFFSET_TRIM_SET"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __OPAMP_CSR_ALL_SWITCHES   OPAMP_CSR_ALL_SWITCHES"

.SS "#define __OPAMP_CSR_ANAWSELX   OPAMP_CSR_ANAWSELX"

.SS "#define __OPAMP_CSR_OPAXCAL_H   OPAMP_CSR_OPAXCAL_H"

.SS "#define __OPAMP_CSR_OPAXCAL_L   OPAMP_CSR_OPAXCAL_L"

.SS "#define __OPAMP_CSR_OPAXCALOUT   OPAMP_CSR_OPAXCALOUT"

.SS "#define __OPAMP_CSR_OPAXLPM   OPAMP_CSR_OPAXLPM"

.SS "#define __OPAMP_CSR_OPAXPD   OPAMP_CSR_OPAXPD"

.SS "#define __OPAMP_CSR_S3SELX   OPAMP_CSR_S3SELX"

.SS "#define __OPAMP_CSR_S4SELX   OPAMP_CSR_S4SELX"

.SS "#define __OPAMP_CSR_S5SELX   OPAMP_CSR_S5SELX"

.SS "#define __OPAMP_CSR_S6SELX   OPAMP_CSR_S6SELX"

.SS "#define __OPAMP_OFFSET_TRIM_BITSPOSITION   OPAMP_OFFSET_TRIM_BITSPOSITION"

.SS "#define __OPAMP_OFFSET_TRIM_SET   OPAMP_OFFSET_TRIM_SET"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
