.TH "HAL_ETH_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_ETH_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_ENABLE_IT\fP   __HAL_ETH_WAKEUP_EXTI_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_DISABLE_IT\fP   __HAL_ETH_WAKEUP_EXTI_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_GET_FLAG\fP   __HAL_ETH_WAKEUP_EXTI_GET_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_CLEAR_FLAG\fP   __HAL_ETH_WAKEUP_EXTI_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_SET_RISING_EGDE_TRIGGER\fP   __HAL_ETH_WAKEUP_EXTI_ENABLE_RISING_EDGE_TRIGGER"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_SET_FALLING_EGDE_TRIGGER\fP   __HAL_ETH_WAKEUP_EXTI_ENABLE_FALLING_EDGE_TRIGGER"
.br
.ti -1c
.RI "#define \fB__HAL_ETH_EXTI_SET_FALLINGRISING_TRIGGER\fP   __HAL_ETH_WAKEUP_EXTI_ENABLE_FALLINGRISING_TRIGGER"
.br
.ti -1c
.RI "#define \fBETH_PROMISCIOUSMODE_ENABLE\fP   ETH_PROMISCUOUS_MODE_ENABLE"
.br
.ti -1c
.RI "#define \fBETH_PROMISCIOUSMODE_DISABLE\fP   ETH_PROMISCUOUS_MODE_DISABLE"
.br
.ti -1c
.RI "#define \fBIS_ETH_PROMISCIOUS_MODE\fP   IS_ETH_PROMISCUOUS_MODE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_ETH_EXTI_CLEAR_FLAG   __HAL_ETH_WAKEUP_EXTI_CLEAR_FLAG"

.SS "#define __HAL_ETH_EXTI_DISABLE_IT   __HAL_ETH_WAKEUP_EXTI_DISABLE_IT"

.SS "#define __HAL_ETH_EXTI_ENABLE_IT   __HAL_ETH_WAKEUP_EXTI_ENABLE_IT"

.SS "#define __HAL_ETH_EXTI_GET_FLAG   __HAL_ETH_WAKEUP_EXTI_GET_FLAG"

.SS "#define __HAL_ETH_EXTI_SET_FALLING_EGDE_TRIGGER   __HAL_ETH_WAKEUP_EXTI_ENABLE_FALLING_EDGE_TRIGGER"

.SS "#define __HAL_ETH_EXTI_SET_FALLINGRISING_TRIGGER   __HAL_ETH_WAKEUP_EXTI_ENABLE_FALLINGRISING_TRIGGER"

.SS "#define __HAL_ETH_EXTI_SET_RISING_EGDE_TRIGGER   __HAL_ETH_WAKEUP_EXTI_ENABLE_RISING_EDGE_TRIGGER"

.SS "#define ETH_PROMISCIOUSMODE_DISABLE   ETH_PROMISCUOUS_MODE_DISABLE"

.SS "#define ETH_PROMISCIOUSMODE_ENABLE   ETH_PROMISCUOUS_MODE_ENABLE"

.SS "#define IS_ETH_PROMISCIOUS_MODE   IS_ETH_PROMISCUOUS_MODE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
