.TH "HAL_SMBUS_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMBUS_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSMBUS_DUALADDRESS_DISABLED\fP   SMBUS_DUALADDRESS_DISABLE"
.br
.ti -1c
.RI "#define \fBSMBUS_DUALADDRESS_ENABLED\fP   SMBUS_DUALADDRESS_ENABLE"
.br
.ti -1c
.RI "#define \fBSMBUS_GENERALCALL_DISABLED\fP   SMBUS_GENERALCALL_DISABLE"
.br
.ti -1c
.RI "#define \fBSMBUS_GENERALCALL_ENABLED\fP   SMBUS_GENERALCALL_ENABLE"
.br
.ti -1c
.RI "#define \fBSMBUS_NOSTRETCH_DISABLED\fP   SMBUS_NOSTRETCH_DISABLE"
.br
.ti -1c
.RI "#define \fBSMBUS_NOSTRETCH_ENABLED\fP   SMBUS_NOSTRETCH_ENABLE"
.br
.ti -1c
.RI "#define \fBSMBUS_ANALOGFILTER_ENABLED\fP   SMBUS_ANALOGFILTER_ENABLE"
.br
.ti -1c
.RI "#define \fBSMBUS_ANALOGFILTER_DISABLED\fP   SMBUS_ANALOGFILTER_DISABLE"
.br
.ti -1c
.RI "#define \fBSMBUS_PEC_DISABLED\fP   SMBUS_PEC_DISABLE"
.br
.ti -1c
.RI "#define \fBSMBUS_PEC_ENABLED\fP   SMBUS_PEC_ENABLE"
.br
.ti -1c
.RI "#define \fBHAL_SMBUS_STATE_SLAVE_LISTEN\fP   HAL_SMBUS_STATE_LISTEN"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_SMBUS_STATE_SLAVE_LISTEN   HAL_SMBUS_STATE_LISTEN"

.SS "#define SMBUS_ANALOGFILTER_DISABLED   SMBUS_ANALOGFILTER_DISABLE"

.SS "#define SMBUS_ANALOGFILTER_ENABLED   SMBUS_ANALOGFILTER_ENABLE"

.SS "#define SMBUS_DUALADDRESS_DISABLED   SMBUS_DUALADDRESS_DISABLE"

.SS "#define SMBUS_DUALADDRESS_ENABLED   SMBUS_DUALADDRESS_ENABLE"

.SS "#define SMBUS_GENERALCALL_DISABLED   SMBUS_GENERALCALL_DISABLE"

.SS "#define SMBUS_GENERALCALL_ENABLED   SMBUS_GENERALCALL_ENABLE"

.SS "#define SMBUS_NOSTRETCH_DISABLED   SMBUS_NOSTRETCH_DISABLE"

.SS "#define SMBUS_NOSTRETCH_ENABLED   SMBUS_NOSTRETCH_ENABLE"

.SS "#define SMBUS_PEC_DISABLED   SMBUS_PEC_DISABLE"

.SS "#define SMBUS_PEC_ENABLED   SMBUS_PEC_ENABLE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
