.TH "HAL_PWR_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_PWR_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_PVD_EVENT_DISABLE\fP   \fB__HAL_PWR_PVD_EXTI_DISABLE_EVENT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EVENT_ENABLE\fP   \fB__HAL_PWR_PVD_EXTI_ENABLE_EVENT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_FALLINGTRIGGER_DISABLE\fP   \fB__HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_FALLINGTRIGGER_ENABLE\fP   \fB__HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_RISINGTRIGGER_DISABLE\fP   \fB__HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_RISINGTRIGGER_ENABLE\fP   \fB__HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EVENT_DISABLE\fP   __HAL_PWR_PVM_EVENT_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EVENT_ENABLE\fP   __HAL_PWR_PVM_EVENT_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EXTI_FALLINGTRIGGER_DISABLE\fP   __HAL_PWR_PVM_EXTI_FALLINGTRIGGER_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EXTI_FALLINGTRIGGER_ENABLE\fP   __HAL_PWR_PVM_EXTI_FALLINGTRIGGER_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EXTI_RISINGTRIGGER_DISABLE\fP   __HAL_PWR_PVM_EXTI_RISINGTRIGGER_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PVM_EXTI_RISINGTRIGGER_ENABLE\fP   __HAL_PWR_PVM_EXTI_RISINGTRIGGER_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_INTERNALWAKEUP_DISABLE\fP   HAL_PWREx_DisableInternalWakeUpLine"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_INTERNALWAKEUP_ENABLE\fP   HAL_PWREx_EnableInternalWakeUpLine"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PULL_UP_DOWN_CONFIG_DISABLE\fP   HAL_PWREx_DisablePullUpPullDownConfig"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PULL_UP_DOWN_CONFIG_ENABLE\fP   HAL_PWREx_EnablePullUpPullDownConfig"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_CLEAR_EGDE_TRIGGER\fP()   do { \fB__HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE\fP();\fB__HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE\fP(); } while(0)"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_EVENT_DISABLE\fP   \fB__HAL_PWR_PVD_EXTI_DISABLE_EVENT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_EVENT_ENABLE\fP   \fB__HAL_PWR_PVD_EXTI_ENABLE_EVENT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_FALLINGTRIGGER_DISABLE\fP   \fB__HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_FALLINGTRIGGER_ENABLE\fP   \fB__HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_RISINGTRIGGER_DISABLE\fP   \fB__HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_RISINGTRIGGER_ENABLE\fP   \fB__HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_SET_FALLING_EGDE_TRIGGER\fP   \fB__HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVD_EXTI_SET_RISING_EDGE_TRIGGER\fP   \fB__HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVM_DISABLE\fP()   do { HAL_PWREx_DisablePVM1();HAL_PWREx_DisablePVM2();HAL_PWREx_DisablePVM3();HAL_PWREx_DisablePVM4(); } while(0)"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_PVM_ENABLE\fP()   do { HAL_PWREx_EnablePVM1();HAL_PWREx_EnablePVM2();HAL_PWREx_EnablePVM3();HAL_PWREx_EnablePVM4(); } while(0)"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_SRAM2CONTENT_PRESERVE_DISABLE\fP   HAL_PWREx_DisableSRAM2ContentRetention"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_SRAM2CONTENT_PRESERVE_ENABLE\fP   HAL_PWREx_EnableSRAM2ContentRetention"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDIO2_DISABLE\fP   HAL_PWREx_DisableVddIO2"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDIO2_ENABLE\fP   HAL_PWREx_EnableVddIO2"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDIO2_EXTI_CLEAR_EGDE_TRIGGER\fP   __HAL_PWR_VDDIO2_EXTI_DISABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDIO2_EXTI_SET_FALLING_EGDE_TRIGGER\fP   __HAL_PWR_VDDIO2_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDUSB_DISABLE\fP   HAL_PWREx_DisableVddUSB"
.br
.ti -1c
.RI "#define \fB__HAL_PWR_VDDUSB_ENABLE\fP   HAL_PWREx_EnableVddUSB"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_CLEAR_FLAG\fP   \fB__HAL_PWR_PVD_EXTI_CLEAR_FLAG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_DISABLE_IT\fP   \fB__HAL_PWR_PVD_EXTI_DISABLE_IT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_ENABLE_IT\fP   \fB__HAL_PWR_PVD_EXTI_ENABLE_IT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_GENERATE_SWIT\fP   \fB__HAL_PWR_PVD_EXTI_GENERATE_SWIT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_PVD_EXTI_GET_FLAG\fP   \fB__HAL_PWR_PVD_EXTI_GET_FLAG\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_PVD_EVENT_DISABLE   \fB__HAL_PWR_PVD_EXTI_DISABLE_EVENT\fP"

.SS "#define __HAL_PVD_EVENT_ENABLE   \fB__HAL_PWR_PVD_EXTI_ENABLE_EVENT\fP"

.SS "#define __HAL_PVD_EXTI_CLEAR_FLAG   \fB__HAL_PWR_PVD_EXTI_CLEAR_FLAG\fP"

.SS "#define __HAL_PVD_EXTI_DISABLE_IT   \fB__HAL_PWR_PVD_EXTI_DISABLE_IT\fP"

.SS "#define __HAL_PVD_EXTI_ENABLE_IT   \fB__HAL_PWR_PVD_EXTI_ENABLE_IT\fP"

.SS "#define __HAL_PVD_EXTI_FALLINGTRIGGER_DISABLE   \fB__HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE\fP"

.SS "#define __HAL_PVD_EXTI_FALLINGTRIGGER_ENABLE   \fB__HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE\fP"

.SS "#define __HAL_PVD_EXTI_GENERATE_SWIT   \fB__HAL_PWR_PVD_EXTI_GENERATE_SWIT\fP"

.SS "#define __HAL_PVD_EXTI_GET_FLAG   \fB__HAL_PWR_PVD_EXTI_GET_FLAG\fP"

.SS "#define __HAL_PVD_EXTI_RISINGTRIGGER_DISABLE   \fB__HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE\fP"

.SS "#define __HAL_PVD_EXTI_RISINGTRIGGER_ENABLE   \fB__HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE\fP"

.SS "#define __HAL_PVM_EVENT_DISABLE   __HAL_PWR_PVM_EVENT_DISABLE"

.SS "#define __HAL_PVM_EVENT_ENABLE   __HAL_PWR_PVM_EVENT_ENABLE"

.SS "#define __HAL_PVM_EXTI_FALLINGTRIGGER_DISABLE   __HAL_PWR_PVM_EXTI_FALLINGTRIGGER_DISABLE"

.SS "#define __HAL_PVM_EXTI_FALLINGTRIGGER_ENABLE   __HAL_PWR_PVM_EXTI_FALLINGTRIGGER_ENABLE"

.SS "#define __HAL_PVM_EXTI_RISINGTRIGGER_DISABLE   __HAL_PWR_PVM_EXTI_RISINGTRIGGER_DISABLE"

.SS "#define __HAL_PVM_EXTI_RISINGTRIGGER_ENABLE   __HAL_PWR_PVM_EXTI_RISINGTRIGGER_ENABLE"

.SS "#define __HAL_PWR_INTERNALWAKEUP_DISABLE   HAL_PWREx_DisableInternalWakeUpLine"

.SS "#define __HAL_PWR_INTERNALWAKEUP_ENABLE   HAL_PWREx_EnableInternalWakeUpLine"

.SS "#define __HAL_PWR_PULL_UP_DOWN_CONFIG_DISABLE   HAL_PWREx_DisablePullUpPullDownConfig"

.SS "#define __HAL_PWR_PULL_UP_DOWN_CONFIG_ENABLE   HAL_PWREx_EnablePullUpPullDownConfig"

.SS "#define __HAL_PWR_PVD_EXTI_CLEAR_EGDE_TRIGGER()   do { \fB__HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE\fP();\fB__HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE\fP(); } while(0)"

.SS "#define __HAL_PWR_PVD_EXTI_EVENT_DISABLE   \fB__HAL_PWR_PVD_EXTI_DISABLE_EVENT\fP"

.SS "#define __HAL_PWR_PVD_EXTI_EVENT_ENABLE   \fB__HAL_PWR_PVD_EXTI_ENABLE_EVENT\fP"

.SS "#define __HAL_PWR_PVD_EXTI_FALLINGTRIGGER_DISABLE   \fB__HAL_PWR_PVD_EXTI_DISABLE_FALLING_EDGE\fP"

.SS "#define __HAL_PWR_PVD_EXTI_FALLINGTRIGGER_ENABLE   \fB__HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE\fP"

.SS "#define __HAL_PWR_PVD_EXTI_RISINGTRIGGER_DISABLE   \fB__HAL_PWR_PVD_EXTI_DISABLE_RISING_EDGE\fP"

.SS "#define __HAL_PWR_PVD_EXTI_RISINGTRIGGER_ENABLE   \fB__HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE\fP"

.SS "#define __HAL_PWR_PVD_EXTI_SET_FALLING_EGDE_TRIGGER   \fB__HAL_PWR_PVD_EXTI_ENABLE_FALLING_EDGE\fP"

.SS "#define __HAL_PWR_PVD_EXTI_SET_RISING_EDGE_TRIGGER   \fB__HAL_PWR_PVD_EXTI_ENABLE_RISING_EDGE\fP"

.SS "#define __HAL_PWR_PVM_DISABLE()   do { HAL_PWREx_DisablePVM1();HAL_PWREx_DisablePVM2();HAL_PWREx_DisablePVM3();HAL_PWREx_DisablePVM4(); } while(0)"

.SS "#define __HAL_PWR_PVM_ENABLE()   do { HAL_PWREx_EnablePVM1();HAL_PWREx_EnablePVM2();HAL_PWREx_EnablePVM3();HAL_PWREx_EnablePVM4(); } while(0)"

.SS "#define __HAL_PWR_SRAM2CONTENT_PRESERVE_DISABLE   HAL_PWREx_DisableSRAM2ContentRetention"

.SS "#define __HAL_PWR_SRAM2CONTENT_PRESERVE_ENABLE   HAL_PWREx_EnableSRAM2ContentRetention"

.SS "#define __HAL_PWR_VDDIO2_DISABLE   HAL_PWREx_DisableVddIO2"

.SS "#define __HAL_PWR_VDDIO2_ENABLE   HAL_PWREx_EnableVddIO2"

.SS "#define __HAL_PWR_VDDIO2_EXTI_CLEAR_EGDE_TRIGGER   __HAL_PWR_VDDIO2_EXTI_DISABLE_FALLING_EDGE"

.SS "#define __HAL_PWR_VDDIO2_EXTI_SET_FALLING_EGDE_TRIGGER   __HAL_PWR_VDDIO2_EXTI_ENABLE_FALLING_EDGE"

.SS "#define __HAL_PWR_VDDUSB_DISABLE   HAL_PWREx_DisableVddUSB"

.SS "#define __HAL_PWR_VDDUSB_ENABLE   HAL_PWREx_EnableVddUSB"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
