.TH "HAL_HRTIM_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_HRTIM_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DISABLED\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DISABLED"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT1_EEV68\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT1_EEV6"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT2_EEV68\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT2_EEV6"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDBOTH_EEV68\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDBOTH_EEV6"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_BALANCED_EEV68\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_BALANCED_EEV6"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT1_DEEV79\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT1_DEEV7"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT2_DEEV79\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT2_DEEV7"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_DELAYEDBOTH_EEV79\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDBOTH_EEV7"
.br
.ti -1c
.RI "#define \fBHRTIM_TIMDELAYEDPROTECTION_BALANCED_EEV79\fP   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_BALANCED_EEV7"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_SetCounter\fP   __HAL_HRTIM_SETCOUNTER"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_GetCounter\fP   __HAL_HRTIM_GETCOUNTER"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_SetPeriod\fP   __HAL_HRTIM_SETPERIOD"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_GetPeriod\fP   __HAL_HRTIM_GETPERIOD"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_SetClockPrescaler\fP   __HAL_HRTIM_SETCLOCKPRESCALER"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_GetClockPrescaler\fP   __HAL_HRTIM_GETCLOCKPRESCALER"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_SetCompare\fP   __HAL_HRTIM_SETCOMPARE"
.br
.ti -1c
.RI "#define \fB__HAL_HRTIM_GetCompare\fP   __HAL_HRTIM_GETCOMPARE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_HRTIM_GetClockPrescaler   __HAL_HRTIM_GETCLOCKPRESCALER"

.SS "#define __HAL_HRTIM_GetCompare   __HAL_HRTIM_GETCOMPARE"

.SS "#define __HAL_HRTIM_GetCounter   __HAL_HRTIM_GETCOUNTER"

.SS "#define __HAL_HRTIM_GetPeriod   __HAL_HRTIM_GETPERIOD"

.SS "#define __HAL_HRTIM_SetClockPrescaler   __HAL_HRTIM_SETCLOCKPRESCALER"

.SS "#define __HAL_HRTIM_SetCompare   __HAL_HRTIM_SETCOMPARE"

.SS "#define __HAL_HRTIM_SetCounter   __HAL_HRTIM_SETCOUNTER"

.SS "#define __HAL_HRTIM_SetPeriod   __HAL_HRTIM_SETPERIOD"

.SS "#define HRTIM_TIMDELAYEDPROTECTION_BALANCED_EEV68   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_BALANCED_EEV6"

.SS "#define HRTIM_TIMDELAYEDPROTECTION_BALANCED_EEV79   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_BALANCED_EEV7"

.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDBOTH_EEV68   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDBOTH_EEV6"

.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDBOTH_EEV79   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDBOTH_EEV7"

.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT1_DEEV79   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT1_DEEV7"

.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT1_EEV68   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT1_EEV6"

.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT2_DEEV79   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT2_DEEV7"

.SS "#define HRTIM_TIMDELAYEDPROTECTION_DELAYEDOUT2_EEV68   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DELAYEDOUT2_EEV6"

.SS "#define HRTIM_TIMDELAYEDPROTECTION_DISABLED   HRTIM_TIMER_A_B_C_DELAYEDPROTECTION_DISABLED"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
