.TH "HAL_NOR_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_NOR_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNOR_StatusTypedef\fP   HAL_NOR_StatusTypeDef"
.br
.ti -1c
.RI "#define \fBNOR_SUCCESS\fP   HAL_NOR_STATUS_SUCCESS"
.br
.ti -1c
.RI "#define \fBNOR_ONGOING\fP   HAL_NOR_STATUS_ONGOING"
.br
.ti -1c
.RI "#define \fBNOR_ERROR\fP   HAL_NOR_STATUS_ERROR"
.br
.ti -1c
.RI "#define \fBNOR_TIMEOUT\fP   HAL_NOR_STATUS_TIMEOUT"
.br
.ti -1c
.RI "#define \fB__NOR_WRITE\fP   NOR_WRITE"
.br
.ti -1c
.RI "#define \fB__NOR_ADDR_SHIFT\fP   NOR_ADDR_SHIFT"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __NOR_ADDR_SHIFT   NOR_ADDR_SHIFT"

.SS "#define __NOR_WRITE   NOR_WRITE"

.SS "#define NOR_ERROR   HAL_NOR_STATUS_ERROR"

.SS "#define NOR_ONGOING   HAL_NOR_STATUS_ONGOING"

.SS "#define NOR_StatusTypedef   HAL_NOR_StatusTypeDef"

.SS "#define NOR_SUCCESS   HAL_NOR_STATUS_SUCCESS"

.SS "#define NOR_TIMEOUT   HAL_NOR_STATUS_TIMEOUT"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
