.TH "HAL_TIM_Aliased_Functions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_TIM_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_TIM_DMADelayPulseCplt\fP   TIM_DMADelayPulseCplt"
.br
.ti -1c
.RI "#define \fBHAL_TIM_DMAError\fP   \fBTIM_DMAError\fP"
.br
.ti -1c
.RI "#define \fBHAL_TIM_DMACaptureCplt\fP   \fBTIM_DMACaptureCplt\fP"
.br
.ti -1c
.RI "#define \fBHAL_TIMEx_DMACommutationCplt\fP   \fBTIMEx_DMACommutationCplt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_TIM_DMACaptureCplt   \fBTIM_DMACaptureCplt\fP"

.SS "#define HAL_TIM_DMADelayPulseCplt   TIM_DMADelayPulseCplt"

.SS "#define HAL_TIM_DMAError   \fBTIM_DMAError\fP"

.SS "#define HAL_TIMEx_DMACommutationCplt   \fBTIMEx_DMACommutationCplt\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
