.TH "HAL_LPTIM_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_LPTIM_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_DIRECTTRANSISTION\fP   LPTIM_CLOCKSAMPLETIME_DIRECTTRANSITION"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_2TRANSISTIONS\fP   LPTIM_CLOCKSAMPLETIME_2TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_4TRANSISTIONS\fP   LPTIM_CLOCKSAMPLETIME_4TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKSAMPLETIME_8TRANSISTIONS\fP   LPTIM_CLOCKSAMPLETIME_8TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKPOLARITY_RISINGEDGE\fP   LPTIM_CLOCKPOLARITY_RISING"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKPOLARITY_FALLINGEDGE\fP   LPTIM_CLOCKPOLARITY_FALLING"
.br
.ti -1c
.RI "#define \fBLPTIM_CLOCKPOLARITY_BOTHEDGES\fP   LPTIM_CLOCKPOLARITY_RISING_FALLING"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_DIRECTTRANSISTION\fP   LPTIM_TRIGSAMPLETIME_DIRECTTRANSITION"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_2TRANSISTIONS\fP   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_4TRANSISTIONS\fP   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_8TRANSISTIONS\fP   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_2TRANSITION\fP   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_4TRANSITION\fP   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"
.br
.ti -1c
.RI "#define \fBLPTIM_TRIGSAMPLETIME_8TRANSITION\fP   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define LPTIM_CLOCKPOLARITY_BOTHEDGES   LPTIM_CLOCKPOLARITY_RISING_FALLING"

.SS "#define LPTIM_CLOCKPOLARITY_FALLINGEDGE   LPTIM_CLOCKPOLARITY_FALLING"

.SS "#define LPTIM_CLOCKPOLARITY_RISINGEDGE   LPTIM_CLOCKPOLARITY_RISING"

.SS "#define LPTIM_CLOCKSAMPLETIME_2TRANSISTIONS   LPTIM_CLOCKSAMPLETIME_2TRANSITIONS"

.SS "#define LPTIM_CLOCKSAMPLETIME_4TRANSISTIONS   LPTIM_CLOCKSAMPLETIME_4TRANSITIONS"

.SS "#define LPTIM_CLOCKSAMPLETIME_8TRANSISTIONS   LPTIM_CLOCKSAMPLETIME_8TRANSITIONS"

.SS "#define LPTIM_CLOCKSAMPLETIME_DIRECTTRANSISTION   LPTIM_CLOCKSAMPLETIME_DIRECTTRANSITION"

.SS "#define LPTIM_TRIGSAMPLETIME_2TRANSISTIONS   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"

.SS "#define LPTIM_TRIGSAMPLETIME_2TRANSITION   LPTIM_TRIGSAMPLETIME_2TRANSITIONS"

.SS "#define LPTIM_TRIGSAMPLETIME_4TRANSISTIONS   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"

.SS "#define LPTIM_TRIGSAMPLETIME_4TRANSITION   LPTIM_TRIGSAMPLETIME_4TRANSITIONS"

.SS "#define LPTIM_TRIGSAMPLETIME_8TRANSISTIONS   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"

.SS "#define LPTIM_TRIGSAMPLETIME_8TRANSITION   LPTIM_TRIGSAMPLETIME_8TRANSITIONS"

.SS "#define LPTIM_TRIGSAMPLETIME_DIRECTTRANSISTION   LPTIM_TRIGSAMPLETIME_DIRECTTRANSITION"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
