.TH "HAL_USB_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_USB_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSB_EXTI_LINE_WAKEUP\fP   USB_WAKEUP_EXTI_LINE"
.br
.ti -1c
.RI "#define \fBUSB_FS_EXTI_TRIGGER_RISING_EDGE\fP   USB_OTG_FS_WAKEUP_EXTI_RISING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_FS_EXTI_TRIGGER_FALLING_EDGE\fP   USB_OTG_FS_WAKEUP_EXTI_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_FS_EXTI_TRIGGER_BOTH_EDGE\fP   USB_OTG_FS_WAKEUP_EXTI_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_FS_EXTI_LINE_WAKEUP\fP   USB_OTG_FS_WAKEUP_EXTI_LINE"
.br
.ti -1c
.RI "#define \fBUSB_HS_EXTI_TRIGGER_RISING_EDGE\fP   USB_OTG_HS_WAKEUP_EXTI_RISING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_HS_EXTI_TRIGGER_FALLING_EDGE\fP   USB_OTG_HS_WAKEUP_EXTI_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_HS_EXTI_TRIGGER_BOTH_EDGE\fP   USB_OTG_HS_WAKEUP_EXTI_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fBUSB_HS_EXTI_LINE_WAKEUP\fP   USB_OTG_HS_WAKEUP_EXTI_LINE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_ENABLE_IT\fP   __HAL_USB_WAKEUP_EXTI_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_DISABLE_IT\fP   __HAL_USB_WAKEUP_EXTI_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_GET_FLAG\fP   __HAL_USB_WAKEUP_EXTI_GET_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_CLEAR_FLAG\fP   __HAL_USB_WAKEUP_EXTI_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_SET_RISING_EDGE_TRIGGER\fP   __HAL_USB_WAKEUP_EXTI_ENABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_SET_FALLING_EDGE_TRIGGER\fP   __HAL_USB_WAKEUP_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_EXTI_SET_FALLINGRISING_TRIGGER\fP   __HAL_USB_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_ENABLE_IT\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_DISABLE_IT\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_GET_FLAG\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_GET_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_CLEAR_FLAG\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_SET_RISING_EGDE_TRIGGER\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_SET_FALLING_EGDE_TRIGGER\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_SET_FALLINGRISING_TRIGGER\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_FS_EXTI_GENERATE_SWIT\fP   __HAL_USB_OTG_FS_WAKEUP_EXTI_GENERATE_SWIT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_ENABLE_IT\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_DISABLE_IT\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_GET_FLAG\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_GET_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_CLEAR_FLAG\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_CLEAR_FLAG"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_SET_RISING_EGDE_TRIGGER\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_RISING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_SET_FALLING_EGDE_TRIGGER\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_SET_FALLINGRISING_TRIGGER\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"
.br
.ti -1c
.RI "#define \fB__HAL_USB_HS_EXTI_GENERATE_SWIT\fP   __HAL_USB_OTG_HS_WAKEUP_EXTI_GENERATE_SWIT"
.br
.ti -1c
.RI "#define \fBHAL_PCD_ActiveRemoteWakeup\fP   HAL_PCD_ActivateRemoteWakeup"
.br
.ti -1c
.RI "#define \fBHAL_PCD_DeActiveRemoteWakeup\fP   HAL_PCD_DeActivateRemoteWakeup"
.br
.ti -1c
.RI "#define \fBHAL_PCD_SetTxFiFo\fP   HAL_PCDEx_SetTxFiFo"
.br
.ti -1c
.RI "#define \fBHAL_PCD_SetRxFiFo\fP   HAL_PCDEx_SetRxFiFo"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_USB_EXTI_CLEAR_FLAG   __HAL_USB_WAKEUP_EXTI_CLEAR_FLAG"

.SS "#define __HAL_USB_EXTI_DISABLE_IT   __HAL_USB_WAKEUP_EXTI_DISABLE_IT"

.SS "#define __HAL_USB_EXTI_ENABLE_IT   __HAL_USB_WAKEUP_EXTI_ENABLE_IT"

.SS "#define __HAL_USB_EXTI_GET_FLAG   __HAL_USB_WAKEUP_EXTI_GET_FLAG"

.SS "#define __HAL_USB_EXTI_SET_FALLING_EDGE_TRIGGER   __HAL_USB_WAKEUP_EXTI_ENABLE_FALLING_EDGE"

.SS "#define __HAL_USB_EXTI_SET_FALLINGRISING_TRIGGER   __HAL_USB_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"

.SS "#define __HAL_USB_EXTI_SET_RISING_EDGE_TRIGGER   __HAL_USB_WAKEUP_EXTI_ENABLE_RISING_EDGE"

.SS "#define __HAL_USB_FS_EXTI_CLEAR_FLAG   __HAL_USB_OTG_FS_WAKEUP_EXTI_CLEAR_FLAG"

.SS "#define __HAL_USB_FS_EXTI_DISABLE_IT   __HAL_USB_OTG_FS_WAKEUP_EXTI_DISABLE_IT"

.SS "#define __HAL_USB_FS_EXTI_ENABLE_IT   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_IT"

.SS "#define __HAL_USB_FS_EXTI_GENERATE_SWIT   __HAL_USB_OTG_FS_WAKEUP_EXTI_GENERATE_SWIT"

.SS "#define __HAL_USB_FS_EXTI_GET_FLAG   __HAL_USB_OTG_FS_WAKEUP_EXTI_GET_FLAG"

.SS "#define __HAL_USB_FS_EXTI_SET_FALLING_EGDE_TRIGGER   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_FALLING_EDGE"

.SS "#define __HAL_USB_FS_EXTI_SET_FALLINGRISING_TRIGGER   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"

.SS "#define __HAL_USB_FS_EXTI_SET_RISING_EGDE_TRIGGER   __HAL_USB_OTG_FS_WAKEUP_EXTI_ENABLE_RISING_EDGE"

.SS "#define __HAL_USB_HS_EXTI_CLEAR_FLAG   __HAL_USB_OTG_HS_WAKEUP_EXTI_CLEAR_FLAG"

.SS "#define __HAL_USB_HS_EXTI_DISABLE_IT   __HAL_USB_OTG_HS_WAKEUP_EXTI_DISABLE_IT"

.SS "#define __HAL_USB_HS_EXTI_ENABLE_IT   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_IT"

.SS "#define __HAL_USB_HS_EXTI_GENERATE_SWIT   __HAL_USB_OTG_HS_WAKEUP_EXTI_GENERATE_SWIT"

.SS "#define __HAL_USB_HS_EXTI_GET_FLAG   __HAL_USB_OTG_HS_WAKEUP_EXTI_GET_FLAG"

.SS "#define __HAL_USB_HS_EXTI_SET_FALLING_EGDE_TRIGGER   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_FALLING_EDGE"

.SS "#define __HAL_USB_HS_EXTI_SET_FALLINGRISING_TRIGGER   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_RISING_FALLING_EDGE"

.SS "#define __HAL_USB_HS_EXTI_SET_RISING_EGDE_TRIGGER   __HAL_USB_OTG_HS_WAKEUP_EXTI_ENABLE_RISING_EDGE"

.SS "#define HAL_PCD_ActiveRemoteWakeup   HAL_PCD_ActivateRemoteWakeup"

.SS "#define HAL_PCD_DeActiveRemoteWakeup   HAL_PCD_DeActivateRemoteWakeup"

.SS "#define HAL_PCD_SetRxFiFo   HAL_PCDEx_SetRxFiFo"

.SS "#define HAL_PCD_SetTxFiFo   HAL_PCDEx_SetTxFiFo"

.SS "#define USB_EXTI_LINE_WAKEUP   USB_WAKEUP_EXTI_LINE"

.SS "#define USB_FS_EXTI_LINE_WAKEUP   USB_OTG_FS_WAKEUP_EXTI_LINE"

.SS "#define USB_FS_EXTI_TRIGGER_BOTH_EDGE   USB_OTG_FS_WAKEUP_EXTI_RISING_FALLING_EDGE"

.SS "#define USB_FS_EXTI_TRIGGER_FALLING_EDGE   USB_OTG_FS_WAKEUP_EXTI_FALLING_EDGE"

.SS "#define USB_FS_EXTI_TRIGGER_RISING_EDGE   USB_OTG_FS_WAKEUP_EXTI_RISING_EDGE"

.SS "#define USB_HS_EXTI_LINE_WAKEUP   USB_OTG_HS_WAKEUP_EXTI_LINE"

.SS "#define USB_HS_EXTI_TRIGGER_BOTH_EDGE   USB_OTG_HS_WAKEUP_EXTI_RISING_FALLING_EDGE"

.SS "#define USB_HS_EXTI_TRIGGER_FALLING_EDGE   USB_OTG_HS_WAKEUP_EXTI_FALLING_EDGE"

.SS "#define USB_HS_EXTI_TRIGGER_RISING_EDGE   USB_OTG_HS_WAKEUP_EXTI_RISING_EDGE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
