.TH "HAL_IRDA_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_IRDA_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIRDA_ONE_BIT_SAMPLE_DISABLED\fP   IRDA_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBIRDA_ONE_BIT_SAMPLE_ENABLED\fP   IRDA_ONE_BIT_SAMPLE_ENABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IRDA_ONE_BIT_SAMPLE_DISABLED   IRDA_ONE_BIT_SAMPLE_DISABLE"

.SS "#define IRDA_ONE_BIT_SAMPLE_ENABLED   IRDA_ONE_BIT_SAMPLE_ENABLE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
