.TH "HAL_SMARTCARD_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SMARTCARD_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__SMARTCARD_ENABLE_IT\fP   __HAL_SMARTCARD_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_DISABLE_IT\fP   __HAL_SMARTCARD_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_ENABLE\fP   __HAL_SMARTCARD_ENABLE"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_DISABLE\fP   __HAL_SMARTCARD_DISABLE"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_DMA_REQUEST_ENABLE\fP   __HAL_SMARTCARD_DMA_REQUEST_ENABLE"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_DMA_REQUEST_DISABLE\fP   __HAL_SMARTCARD_DMA_REQUEST_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_SMARTCARD_GETCLOCKSOURCE\fP   SMARTCARD_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__SMARTCARD_GETCLOCKSOURCE\fP   SMARTCARD_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fBIS_SMARTCARD_ONEBIT_SAMPLING\fP   IS_SMARTCARD_ONE_BIT_SAMPLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_SMARTCARD_GETCLOCKSOURCE   SMARTCARD_GETCLOCKSOURCE"

.SS "#define __SMARTCARD_DISABLE   __HAL_SMARTCARD_DISABLE"

.SS "#define __SMARTCARD_DISABLE_IT   __HAL_SMARTCARD_DISABLE_IT"

.SS "#define __SMARTCARD_DMA_REQUEST_DISABLE   __HAL_SMARTCARD_DMA_REQUEST_DISABLE"

.SS "#define __SMARTCARD_DMA_REQUEST_ENABLE   __HAL_SMARTCARD_DMA_REQUEST_ENABLE"

.SS "#define __SMARTCARD_ENABLE   __HAL_SMARTCARD_ENABLE"

.SS "#define __SMARTCARD_ENABLE_IT   __HAL_SMARTCARD_ENABLE_IT"

.SS "#define __SMARTCARD_GETCLOCKSOURCE   SMARTCARD_GETCLOCKSOURCE"

.SS "#define IS_SMARTCARD_ONEBIT_SAMPLING   IS_SMARTCARD_ONE_BIT_SAMPLE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
