.TH "HAL_UART_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_UART_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_UART_GETCLOCKSOURCE\fP   UART_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__HAL_UART_MASK_COMPUTATION\fP   UART_MASK_COMPUTATION"
.br
.ti -1c
.RI "#define \fB__UART_GETCLOCKSOURCE\fP   UART_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__UART_MASK_COMPUTATION\fP   UART_MASK_COMPUTATION"
.br
.ti -1c
.RI "#define \fBIS_UART_WAKEUPMETHODE\fP   IS_UART_WAKEUPMETHOD"
.br
.ti -1c
.RI "#define \fBIS_UART_ONEBIT_SAMPLE\fP   IS_UART_ONE_BIT_SAMPLE"
.br
.ti -1c
.RI "#define \fBIS_UART_ONEBIT_SAMPLING\fP   IS_UART_ONE_BIT_SAMPLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_UART_GETCLOCKSOURCE   UART_GETCLOCKSOURCE"

.SS "#define __HAL_UART_MASK_COMPUTATION   UART_MASK_COMPUTATION"

.SS "#define __UART_GETCLOCKSOURCE   UART_GETCLOCKSOURCE"

.SS "#define __UART_MASK_COMPUTATION   UART_MASK_COMPUTATION"

.SS "#define IS_UART_ONEBIT_SAMPLE   IS_UART_ONE_BIT_SAMPLE"

.SS "#define IS_UART_ONEBIT_SAMPLING   IS_UART_ONE_BIT_SAMPLE"

.SS "#define IS_UART_WAKEUPMETHODE   IS_UART_WAKEUPMETHOD"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
