.TH "HAL_I2C_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2C_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2C_DUALADDRESS_DISABLED\fP   I2C_DUALADDRESS_DISABLE"
.br
.ti -1c
.RI "#define \fBI2C_DUALADDRESS_ENABLED\fP   I2C_DUALADDRESS_ENABLE"
.br
.ti -1c
.RI "#define \fBI2C_GENERALCALL_DISABLED\fP   I2C_GENERALCALL_DISABLE"
.br
.ti -1c
.RI "#define \fBI2C_GENERALCALL_ENABLED\fP   I2C_GENERALCALL_ENABLE"
.br
.ti -1c
.RI "#define \fBI2C_NOSTRETCH_DISABLED\fP   I2C_NOSTRETCH_DISABLE"
.br
.ti -1c
.RI "#define \fBI2C_NOSTRETCH_ENABLED\fP   I2C_NOSTRETCH_ENABLE"
.br
.ti -1c
.RI "#define \fBI2C_ANALOGFILTER_ENABLED\fP   I2C_ANALOGFILTER_ENABLE"
.br
.ti -1c
.RI "#define \fBI2C_ANALOGFILTER_DISABLED\fP   I2C_ANALOGFILTER_DISABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define I2C_ANALOGFILTER_DISABLED   I2C_ANALOGFILTER_DISABLE"

.SS "#define I2C_ANALOGFILTER_ENABLED   I2C_ANALOGFILTER_ENABLE"

.SS "#define I2C_DUALADDRESS_DISABLED   I2C_DUALADDRESS_DISABLE"

.SS "#define I2C_DUALADDRESS_ENABLED   I2C_DUALADDRESS_ENABLE"

.SS "#define I2C_GENERALCALL_DISABLED   I2C_GENERALCALL_DISABLE"

.SS "#define I2C_GENERALCALL_ENABLED   I2C_GENERALCALL_ENABLE"

.SS "#define I2C_NOSTRETCH_DISABLED   I2C_NOSTRETCH_DISABLE"

.SS "#define I2C_NOSTRETCH_ENABLED   I2C_NOSTRETCH_ENABLE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
