.TH "HAL_SPI_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SPI_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_TIMODE_DISABLED\fP   SPI_TIMODE_DISABLE"
.br
.ti -1c
.RI "#define \fBSPI_TIMODE_ENABLED\fP   SPI_TIMODE_ENABLE"
.br
.ti -1c
.RI "#define \fBSPI_CRCCALCULATION_DISABLED\fP   SPI_CRCCALCULATION_DISABLE"
.br
.ti -1c
.RI "#define \fBSPI_CRCCALCULATION_ENABLED\fP   SPI_CRCCALCULATION_ENABLE"
.br
.ti -1c
.RI "#define \fBSPI_NSS_PULSE_DISABLED\fP   SPI_NSS_PULSE_DISABLE"
.br
.ti -1c
.RI "#define \fBSPI_NSS_PULSE_ENABLED\fP   SPI_NSS_PULSE_ENABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SPI_CRCCALCULATION_DISABLED   SPI_CRCCALCULATION_DISABLE"

.SS "#define SPI_CRCCALCULATION_ENABLED   SPI_CRCCALCULATION_ENABLE"

.SS "#define SPI_NSS_PULSE_DISABLED   SPI_NSS_PULSE_DISABLE"

.SS "#define SPI_NSS_PULSE_ENABLED   SPI_NSS_PULSE_ENABLE"

.SS "#define SPI_TIMODE_DISABLED   SPI_TIMODE_DISABLE"

.SS "#define SPI_TIMODE_ENABLED   SPI_TIMODE_ENABLE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
