.TH "HAL_FLASH_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_FLASH_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTYPEPROGRAM_BYTE\fP   FLASH_TYPEPROGRAM_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_HALFWORD\fP   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_WORD\fP   \fBFLASH_TYPEPROGRAM_WORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_DOUBLEWORD\fP   \fBFLASH_TYPEPROGRAM_DOUBLEWORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEERASE_SECTORS\fP   FLASH_TYPEERASE_SECTORS"
.br
.ti -1c
.RI "#define \fBTYPEERASE_PAGES\fP   \fBFLASH_TYPEERASE_PAGES\fP"
.br
.ti -1c
.RI "#define \fBTYPEERASE_PAGEERASE\fP   \fBFLASH_TYPEERASE_PAGES\fP"
.br
.ti -1c
.RI "#define \fBTYPEERASE_MASSERASE\fP   \fBFLASH_TYPEERASE_MASSERASE\fP"
.br
.ti -1c
.RI "#define \fBWRPSTATE_DISABLE\fP   \fBOB_WRPSTATE_DISABLE\fP"
.br
.ti -1c
.RI "#define \fBWRPSTATE_ENABLE\fP   \fBOB_WRPSTATE_ENABLE\fP"
.br
.ti -1c
.RI "#define \fBHAL_FLASH_TIMEOUT_VALUE\fP   \fBFLASH_TIMEOUT_VALUE\fP"
.br
.ti -1c
.RI "#define \fBOBEX_PCROP\fP   OPTIONBYTE_PCROP"
.br
.ti -1c
.RI "#define \fBOBEX_BOOTCONFIG\fP   OPTIONBYTE_BOOTCONFIG"
.br
.ti -1c
.RI "#define \fBPCROPSTATE_DISABLE\fP   OB_PCROP_STATE_DISABLE"
.br
.ti -1c
.RI "#define \fBPCROPSTATE_ENABLE\fP   OB_PCROP_STATE_ENABLE"
.br
.ti -1c
.RI "#define \fBTYPEERASEDATA_BYTE\fP   FLASH_TYPEERASEDATA_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEERASEDATA_HALFWORD\fP   FLASH_TYPEERASEDATA_HALFWORD"
.br
.ti -1c
.RI "#define \fBTYPEERASEDATA_WORD\fP   FLASH_TYPEERASEDATA_WORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_BYTE\fP   FLASH_TYPEPROGRAMDATA_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_HALFWORD\fP   FLASH_TYPEPROGRAMDATA_HALFWORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_WORD\fP   FLASH_TYPEPROGRAMDATA_WORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_FASTBYTE\fP   FLASH_TYPEPROGRAMDATA_FASTBYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_FASTHALFWORD\fP   FLASH_TYPEPROGRAMDATA_FASTHALFWORD"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAMDATA_FASTWORD\fP   FLASH_TYPEPROGRAMDATA_FASTWORD"
.br
.ti -1c
.RI "#define \fBPAGESIZE\fP   FLASH_PAGE_SIZE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FASTBYTE\fP   FLASH_TYPEPROGRAM_BYTE"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FASTHALFWORD\fP   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FASTWORD\fP   \fBFLASH_TYPEPROGRAM_WORD\fP"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_1\fP   FLASH_VOLTAGE_RANGE_1"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_2\fP   FLASH_VOLTAGE_RANGE_2"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_3\fP   FLASH_VOLTAGE_RANGE_3"
.br
.ti -1c
.RI "#define \fBVOLTAGE_RANGE_4\fP   FLASH_VOLTAGE_RANGE_4"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FAST\fP   FLASH_TYPEPROGRAM_FAST"
.br
.ti -1c
.RI "#define \fBTYPEPROGRAM_FAST_AND_LAST\fP   FLASH_TYPEPROGRAM_FAST_AND_LAST"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK1_AREAA\fP   OB_WRPAREA_BANK1_AREAA"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK1_AREAB\fP   OB_WRPAREA_BANK1_AREAB"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK2_AREAA\fP   OB_WRPAREA_BANK2_AREAA"
.br
.ti -1c
.RI "#define \fBWRPAREA_BANK2_AREAB\fP   OB_WRPAREA_BANK2_AREAB"
.br
.ti -1c
.RI "#define \fBIWDG_STDBY_FREEZE\fP   OB_IWDG_STDBY_FREEZE"
.br
.ti -1c
.RI "#define \fBIWDG_STDBY_ACTIVE\fP   OB_IWDG_STDBY_RUN"
.br
.ti -1c
.RI "#define \fBIWDG_STOP_FREEZE\fP   OB_IWDG_STOP_FREEZE"
.br
.ti -1c
.RI "#define \fBIWDG_STOP_ACTIVE\fP   OB_IWDG_STOP_RUN"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_NONE\fP   \fBHAL_FLASH_ERROR_NONE\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_RD\fP   HAL_FLASH_ERROR_RD"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PG\fP   \fBHAL_FLASH_ERROR_PROG\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PGP\fP   HAL_FLASH_ERROR_PGS"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_WRP\fP   \fBHAL_FLASH_ERROR_WRP\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OPTV\fP   \fBHAL_FLASH_ERROR_OPTV\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OPTVUSR\fP   HAL_FLASH_ERROR_OPTVUSR"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PROG\fP   \fBHAL_FLASH_ERROR_PROG\fP"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OP\fP   HAL_FLASH_ERROR_OPERATION"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PGA\fP   HAL_FLASH_ERROR_PGA"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_SIZE\fP   HAL_FLASH_ERROR_SIZE"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_SIZ\fP   HAL_FLASH_ERROR_SIZE"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_PGS\fP   HAL_FLASH_ERROR_PGS"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_MIS\fP   HAL_FLASH_ERROR_MIS"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_FAST\fP   HAL_FLASH_ERROR_FAST"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_FWWERR\fP   HAL_FLASH_ERROR_FWWERR"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_NOTZERO\fP   HAL_FLASH_ERROR_NOTZERO"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_OPERATION\fP   HAL_FLASH_ERROR_OPERATION"
.br
.ti -1c
.RI "#define \fBFLASH_ERROR_ERS\fP   HAL_FLASH_ERROR_ERS"
.br
.ti -1c
.RI "#define \fBOB_WDG_SW\fP   \fBOB_IWDG_SW\fP"
.br
.ti -1c
.RI "#define \fBOB_WDG_HW\fP   \fBOB_IWDG_HW\fP"
.br
.ti -1c
.RI "#define \fBOB_SDADC12_VDD_MONITOR_SET\fP   OB_SDACD_VDD_MONITOR_SET"
.br
.ti -1c
.RI "#define \fBOB_SDADC12_VDD_MONITOR_RESET\fP   OB_SDACD_VDD_MONITOR_RESET"
.br
.ti -1c
.RI "#define \fBOB_RAM_PARITY_CHECK_SET\fP   OB_SRAM_PARITY_SET"
.br
.ti -1c
.RI "#define \fBOB_RAM_PARITY_CHECK_RESET\fP   OB_SRAM_PARITY_RESET"
.br
.ti -1c
.RI "#define \fBIS_OB_SDADC12_VDD_MONITOR\fP   IS_OB_SDACD_VDD_MONITOR"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL0\fP   \fBOB_RDP_LEVEL_0\fP"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL1\fP   \fBOB_RDP_LEVEL_1\fP"
.br
.ti -1c
.RI "#define \fBOB_RDP_LEVEL2\fP   OB_RDP_LEVEL_2"
.br
.ti -1c
.RI "#define \fBOB_BOOT_ENTRY_FORCED_NONE\fP   OB_BOOT_LOCK_DISABLE"
.br
.ti -1c
.RI "#define \fBOB_BOOT_ENTRY_FORCED_FLASH\fP   OB_BOOT_LOCK_ENABLE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FLASH_ERROR_ERS   HAL_FLASH_ERROR_ERS"

.SS "#define FLASH_ERROR_FAST   HAL_FLASH_ERROR_FAST"

.SS "#define FLASH_ERROR_FWWERR   HAL_FLASH_ERROR_FWWERR"

.SS "#define FLASH_ERROR_MIS   HAL_FLASH_ERROR_MIS"

.SS "#define FLASH_ERROR_NONE   \fBHAL_FLASH_ERROR_NONE\fP"

.SS "#define FLASH_ERROR_NOTZERO   HAL_FLASH_ERROR_NOTZERO"

.SS "#define FLASH_ERROR_OP   HAL_FLASH_ERROR_OPERATION"

.SS "#define FLASH_ERROR_OPERATION   HAL_FLASH_ERROR_OPERATION"

.SS "#define FLASH_ERROR_OPTV   \fBHAL_FLASH_ERROR_OPTV\fP"

.SS "#define FLASH_ERROR_OPTVUSR   HAL_FLASH_ERROR_OPTVUSR"

.SS "#define FLASH_ERROR_PG   \fBHAL_FLASH_ERROR_PROG\fP"

.SS "#define FLASH_ERROR_PGA   HAL_FLASH_ERROR_PGA"

.SS "#define FLASH_ERROR_PGP   HAL_FLASH_ERROR_PGS"

.SS "#define FLASH_ERROR_PGS   HAL_FLASH_ERROR_PGS"

.SS "#define FLASH_ERROR_PROG   \fBHAL_FLASH_ERROR_PROG\fP"

.SS "#define FLASH_ERROR_RD   HAL_FLASH_ERROR_RD"

.SS "#define FLASH_ERROR_SIZ   HAL_FLASH_ERROR_SIZE"

.SS "#define FLASH_ERROR_SIZE   HAL_FLASH_ERROR_SIZE"

.SS "#define FLASH_ERROR_WRP   \fBHAL_FLASH_ERROR_WRP\fP"

.SS "#define HAL_FLASH_TIMEOUT_VALUE   \fBFLASH_TIMEOUT_VALUE\fP"

.SS "#define IS_OB_SDADC12_VDD_MONITOR   IS_OB_SDACD_VDD_MONITOR"

.SS "#define IWDG_STDBY_ACTIVE   OB_IWDG_STDBY_RUN"

.SS "#define IWDG_STDBY_FREEZE   OB_IWDG_STDBY_FREEZE"

.SS "#define IWDG_STOP_ACTIVE   OB_IWDG_STOP_RUN"

.SS "#define IWDG_STOP_FREEZE   OB_IWDG_STOP_FREEZE"

.SS "#define OB_BOOT_ENTRY_FORCED_FLASH   OB_BOOT_LOCK_ENABLE"

.SS "#define OB_BOOT_ENTRY_FORCED_NONE   OB_BOOT_LOCK_DISABLE"

.SS "#define OB_RAM_PARITY_CHECK_RESET   OB_SRAM_PARITY_RESET"

.SS "#define OB_RAM_PARITY_CHECK_SET   OB_SRAM_PARITY_SET"

.SS "#define OB_RDP_LEVEL0   \fBOB_RDP_LEVEL_0\fP"

.SS "#define OB_RDP_LEVEL1   \fBOB_RDP_LEVEL_1\fP"

.SS "#define OB_RDP_LEVEL2   OB_RDP_LEVEL_2"

.SS "#define OB_SDADC12_VDD_MONITOR_RESET   OB_SDACD_VDD_MONITOR_RESET"

.SS "#define OB_SDADC12_VDD_MONITOR_SET   OB_SDACD_VDD_MONITOR_SET"

.SS "#define OB_WDG_HW   \fBOB_IWDG_HW\fP"

.SS "#define OB_WDG_SW   \fBOB_IWDG_SW\fP"

.SS "#define OBEX_BOOTCONFIG   OPTIONBYTE_BOOTCONFIG"

.SS "#define OBEX_PCROP   OPTIONBYTE_PCROP"

.SS "#define PAGESIZE   FLASH_PAGE_SIZE"

.SS "#define PCROPSTATE_DISABLE   OB_PCROP_STATE_DISABLE"

.SS "#define PCROPSTATE_ENABLE   OB_PCROP_STATE_ENABLE"

.SS "#define TYPEERASE_MASSERASE   \fBFLASH_TYPEERASE_MASSERASE\fP"

.SS "#define TYPEERASE_PAGEERASE   \fBFLASH_TYPEERASE_PAGES\fP"

.SS "#define TYPEERASE_PAGES   \fBFLASH_TYPEERASE_PAGES\fP"

.SS "#define TYPEERASE_SECTORS   FLASH_TYPEERASE_SECTORS"

.SS "#define TYPEERASEDATA_BYTE   FLASH_TYPEERASEDATA_BYTE"

.SS "#define TYPEERASEDATA_HALFWORD   FLASH_TYPEERASEDATA_HALFWORD"

.SS "#define TYPEERASEDATA_WORD   FLASH_TYPEERASEDATA_WORD"

.SS "#define TYPEPROGRAM_BYTE   FLASH_TYPEPROGRAM_BYTE"

.SS "#define TYPEPROGRAM_DOUBLEWORD   \fBFLASH_TYPEPROGRAM_DOUBLEWORD\fP"

.SS "#define TYPEPROGRAM_FAST   FLASH_TYPEPROGRAM_FAST"

.SS "#define TYPEPROGRAM_FAST_AND_LAST   FLASH_TYPEPROGRAM_FAST_AND_LAST"

.SS "#define TYPEPROGRAM_FASTBYTE   FLASH_TYPEPROGRAM_BYTE"

.SS "#define TYPEPROGRAM_FASTHALFWORD   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"

.SS "#define TYPEPROGRAM_FASTWORD   \fBFLASH_TYPEPROGRAM_WORD\fP"

.SS "#define TYPEPROGRAM_HALFWORD   \fBFLASH_TYPEPROGRAM_HALFWORD\fP"

.SS "#define TYPEPROGRAM_WORD   \fBFLASH_TYPEPROGRAM_WORD\fP"

.SS "#define TYPEPROGRAMDATA_BYTE   FLASH_TYPEPROGRAMDATA_BYTE"

.SS "#define TYPEPROGRAMDATA_FASTBYTE   FLASH_TYPEPROGRAMDATA_FASTBYTE"

.SS "#define TYPEPROGRAMDATA_FASTHALFWORD   FLASH_TYPEPROGRAMDATA_FASTHALFWORD"

.SS "#define TYPEPROGRAMDATA_FASTWORD   FLASH_TYPEPROGRAMDATA_FASTWORD"

.SS "#define TYPEPROGRAMDATA_HALFWORD   FLASH_TYPEPROGRAMDATA_HALFWORD"

.SS "#define TYPEPROGRAMDATA_WORD   FLASH_TYPEPROGRAMDATA_WORD"

.SS "#define VOLTAGE_RANGE_1   FLASH_VOLTAGE_RANGE_1"

.SS "#define VOLTAGE_RANGE_2   FLASH_VOLTAGE_RANGE_2"

.SS "#define VOLTAGE_RANGE_3   FLASH_VOLTAGE_RANGE_3"

.SS "#define VOLTAGE_RANGE_4   FLASH_VOLTAGE_RANGE_4"

.SS "#define WRPAREA_BANK1_AREAA   OB_WRPAREA_BANK1_AREAA"

.SS "#define WRPAREA_BANK1_AREAB   OB_WRPAREA_BANK1_AREAB"

.SS "#define WRPAREA_BANK2_AREAA   OB_WRPAREA_BANK2_AREAA"

.SS "#define WRPAREA_BANK2_AREAB   OB_WRPAREA_BANK2_AREAB"

.SS "#define WRPSTATE_DISABLE   \fBOB_WRPSTATE_DISABLE\fP"

.SS "#define WRPSTATE_ENABLE   \fBOB_WRPSTATE_ENABLE\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
