.TH "HAL_ADC_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_ADC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADC_RESOLUTION12b\fP   ADC_RESOLUTION_12B"
.br
.ti -1c
.RI "#define \fBADC_RESOLUTION10b\fP   ADC_RESOLUTION_10B"
.br
.ti -1c
.RI "#define \fBADC_RESOLUTION8b\fP   ADC_RESOLUTION_8B"
.br
.ti -1c
.RI "#define \fBADC_RESOLUTION6b\fP   ADC_RESOLUTION_6B"
.br
.ti -1c
.RI "#define \fBOVR_DATA_OVERWRITTEN\fP   ADC_OVR_DATA_OVERWRITTEN"
.br
.ti -1c
.RI "#define \fBOVR_DATA_PRESERVED\fP   ADC_OVR_DATA_PRESERVED"
.br
.ti -1c
.RI "#define \fBEOC_SINGLE_CONV\fP   ADC_EOC_SINGLE_CONV"
.br
.ti -1c
.RI "#define \fBEOC_SEQ_CONV\fP   ADC_EOC_SEQ_CONV"
.br
.ti -1c
.RI "#define \fBEOC_SINGLE_SEQ_CONV\fP   ADC_EOC_SINGLE_SEQ_CONV"
.br
.ti -1c
.RI "#define \fBREGULAR_GROUP\fP   ADC_REGULAR_GROUP"
.br
.ti -1c
.RI "#define \fBINJECTED_GROUP\fP   ADC_INJECTED_GROUP"
.br
.ti -1c
.RI "#define \fBREGULAR_INJECTED_GROUP\fP   ADC_REGULAR_INJECTED_GROUP"
.br
.ti -1c
.RI "#define \fBAWD_EVENT\fP   ADC_AWD_EVENT"
.br
.ti -1c
.RI "#define \fBAWD1_EVENT\fP   ADC_AWD1_EVENT"
.br
.ti -1c
.RI "#define \fBAWD2_EVENT\fP   ADC_AWD2_EVENT"
.br
.ti -1c
.RI "#define \fBAWD3_EVENT\fP   ADC_AWD3_EVENT"
.br
.ti -1c
.RI "#define \fBOVR_EVENT\fP   ADC_OVR_EVENT"
.br
.ti -1c
.RI "#define \fBJQOVF_EVENT\fP   ADC_JQOVF_EVENT"
.br
.ti -1c
.RI "#define \fBALL_CHANNELS\fP   ADC_ALL_CHANNELS"
.br
.ti -1c
.RI "#define \fBREGULAR_CHANNELS\fP   ADC_REGULAR_CHANNELS"
.br
.ti -1c
.RI "#define \fBINJECTED_CHANNELS\fP   ADC_INJECTED_CHANNELS"
.br
.ti -1c
.RI "#define \fBSYSCFG_FLAG_SENSOR_ADC\fP   ADC_FLAG_SENSOR"
.br
.ti -1c
.RI "#define \fBSYSCFG_FLAG_VREF_ADC\fP   ADC_FLAG_VREFINT"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV1\fP   ADC_CLOCK_SYNC_PCLK_DIV1"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV2\fP   ADC_CLOCK_SYNC_PCLK_DIV2"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV4\fP   ADC_CLOCK_SYNC_PCLK_DIV4"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV6\fP   ADC_CLOCK_SYNC_PCLK_DIV6"
.br
.ti -1c
.RI "#define \fBADC_CLOCKPRESCALER_PCLK_DIV8\fP   ADC_CLOCK_SYNC_PCLK_DIV8"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG0_T6_TRGO\fP   ADC_EXTERNALTRIGCONV_T6_TRGO"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG1_T21_CC2\fP   ADC_EXTERNALTRIGCONV_T21_CC2"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG2_T2_TRGO\fP   ADC_EXTERNALTRIGCONV_T2_TRGO"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG3_T2_CC4\fP   ADC_EXTERNALTRIGCONV_T2_CC4"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG4_T22_TRGO\fP   ADC_EXTERNALTRIGCONV_T22_TRGO"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG7_EXT_IT11\fP   ADC_EXTERNALTRIGCONV_EXT_IT11"
.br
.ti -1c
.RI "#define \fBADC_CLOCK_ASYNC\fP   ADC_CLOCK_ASYNC_DIV1"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG_EDGE_NONE\fP   ADC_EXTERNALTRIGCONVEDGE_NONE"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG_EDGE_RISING\fP   ADC_EXTERNALTRIGCONVEDGE_RISING"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG_EDGE_FALLING\fP   ADC_EXTERNALTRIGCONVEDGE_FALLING"
.br
.ti -1c
.RI "#define \fBADC_EXTERNALTRIG_EDGE_RISINGFALLING\fP   ADC_EXTERNALTRIGCONVEDGE_RISINGFALLING"
.br
.ti -1c
.RI "#define \fBADC_SAMPLETIME_2CYCLE_5\fP   ADC_SAMPLETIME_2CYCLES_5"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_BUSY_REG\fP   HAL_ADC_STATE_REG_BUSY"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_BUSY_INJ\fP   HAL_ADC_STATE_INJ_BUSY"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_EOC_REG\fP   HAL_ADC_STATE_REG_EOC"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_EOC_INJ\fP   HAL_ADC_STATE_INJ_EOC"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_ERROR\fP   HAL_ADC_STATE_ERROR_INTERNAL"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_BUSY\fP   HAL_ADC_STATE_BUSY_INTERNAL"
.br
.ti -1c
.RI "#define \fBHAL_ADC_STATE_AWD\fP   HAL_ADC_STATE_AWD1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_CLOCK_ASYNC   ADC_CLOCK_ASYNC_DIV1"

.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV1   ADC_CLOCK_SYNC_PCLK_DIV1"

.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV2   ADC_CLOCK_SYNC_PCLK_DIV2"

.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV4   ADC_CLOCK_SYNC_PCLK_DIV4"

.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV6   ADC_CLOCK_SYNC_PCLK_DIV6"

.SS "#define ADC_CLOCKPRESCALER_PCLK_DIV8   ADC_CLOCK_SYNC_PCLK_DIV8"

.SS "#define ADC_EXTERNALTRIG0_T6_TRGO   ADC_EXTERNALTRIGCONV_T6_TRGO"

.SS "#define ADC_EXTERNALTRIG1_T21_CC2   ADC_EXTERNALTRIGCONV_T21_CC2"

.SS "#define ADC_EXTERNALTRIG2_T2_TRGO   ADC_EXTERNALTRIGCONV_T2_TRGO"

.SS "#define ADC_EXTERNALTRIG3_T2_CC4   ADC_EXTERNALTRIGCONV_T2_CC4"

.SS "#define ADC_EXTERNALTRIG4_T22_TRGO   ADC_EXTERNALTRIGCONV_T22_TRGO"

.SS "#define ADC_EXTERNALTRIG7_EXT_IT11   ADC_EXTERNALTRIGCONV_EXT_IT11"

.SS "#define ADC_EXTERNALTRIG_EDGE_FALLING   ADC_EXTERNALTRIGCONVEDGE_FALLING"

.SS "#define ADC_EXTERNALTRIG_EDGE_NONE   ADC_EXTERNALTRIGCONVEDGE_NONE"

.SS "#define ADC_EXTERNALTRIG_EDGE_RISING   ADC_EXTERNALTRIGCONVEDGE_RISING"

.SS "#define ADC_EXTERNALTRIG_EDGE_RISINGFALLING   ADC_EXTERNALTRIGCONVEDGE_RISINGFALLING"

.SS "#define ADC_RESOLUTION10b   ADC_RESOLUTION_10B"

.SS "#define ADC_RESOLUTION12b   ADC_RESOLUTION_12B"

.SS "#define ADC_RESOLUTION6b   ADC_RESOLUTION_6B"

.SS "#define ADC_RESOLUTION8b   ADC_RESOLUTION_8B"

.SS "#define ADC_SAMPLETIME_2CYCLE_5   ADC_SAMPLETIME_2CYCLES_5"

.SS "#define ALL_CHANNELS   ADC_ALL_CHANNELS"

.SS "#define AWD1_EVENT   ADC_AWD1_EVENT"

.SS "#define AWD2_EVENT   ADC_AWD2_EVENT"

.SS "#define AWD3_EVENT   ADC_AWD3_EVENT"

.SS "#define AWD_EVENT   ADC_AWD_EVENT"

.SS "#define EOC_SEQ_CONV   ADC_EOC_SEQ_CONV"

.SS "#define EOC_SINGLE_CONV   ADC_EOC_SINGLE_CONV"

.SS "#define EOC_SINGLE_SEQ_CONV   ADC_EOC_SINGLE_SEQ_CONV"

.SS "#define HAL_ADC_STATE_AWD   HAL_ADC_STATE_AWD1"

.SS "#define HAL_ADC_STATE_BUSY   HAL_ADC_STATE_BUSY_INTERNAL"

.SS "#define HAL_ADC_STATE_BUSY_INJ   HAL_ADC_STATE_INJ_BUSY"

.SS "#define HAL_ADC_STATE_BUSY_REG   HAL_ADC_STATE_REG_BUSY"

.SS "#define HAL_ADC_STATE_EOC_INJ   HAL_ADC_STATE_INJ_EOC"

.SS "#define HAL_ADC_STATE_EOC_REG   HAL_ADC_STATE_REG_EOC"

.SS "#define HAL_ADC_STATE_ERROR   HAL_ADC_STATE_ERROR_INTERNAL"

.SS "#define INJECTED_CHANNELS   ADC_INJECTED_CHANNELS"

.SS "#define INJECTED_GROUP   ADC_INJECTED_GROUP"

.SS "#define JQOVF_EVENT   ADC_JQOVF_EVENT"

.SS "#define OVR_DATA_OVERWRITTEN   ADC_OVR_DATA_OVERWRITTEN"

.SS "#define OVR_DATA_PRESERVED   ADC_OVR_DATA_PRESERVED"

.SS "#define OVR_EVENT   ADC_OVR_EVENT"

.SS "#define REGULAR_CHANNELS   ADC_REGULAR_CHANNELS"

.SS "#define REGULAR_GROUP   ADC_REGULAR_GROUP"

.SS "#define REGULAR_INJECTED_GROUP   ADC_REGULAR_INJECTED_GROUP"

.SS "#define SYSCFG_FLAG_SENSOR_ADC   ADC_FLAG_SENSOR"

.SS "#define SYSCFG_FLAG_VREF_ADC   ADC_FLAG_VREFINT"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
