.TH "HAL_TICK_FREQ" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_TICK_FREQ
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHAL_TickFreqTypeDef\fP { \fBHAL_TICK_FREQ_10HZ\fP = 100U, \fBHAL_TICK_FREQ_100HZ\fP = 10U, \fBHAL_TICK_FREQ_1KHZ\fP = 1U, \fBHAL_TICK_FREQ_DEFAULT\fP = HAL_TICK_FREQ_1KHZ }"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBHAL_TickFreqTypeDef\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHAL_TICK_FREQ_10HZ \fP\fP
.TP
\fB\fIHAL_TICK_FREQ_100HZ \fP\fP
.TP
\fB\fIHAL_TICK_FREQ_1KHZ \fP\fP
.TP
\fB\fIHAL_TICK_FREQ_DEFAULT \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
