.TH "HAL_SPI_Aliased_Functions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SPI_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_SPI_FlushRxFifo\fP   HAL_SPIEx_FlushRxFifo"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_SPI_FlushRxFifo   HAL_SPIEx_FlushRxFifo"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
