.TH "HAL_UART_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_UART_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUART_ONEBIT_SAMPLING_DISABLED\fP   UART_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBUART_ONEBIT_SAMPLING_ENABLED\fP   UART_ONE_BIT_SAMPLE_ENABLE"
.br
.ti -1c
.RI "#define \fBUART_ONE_BIT_SAMPLE_DISABLED\fP   UART_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fBUART_ONE_BIT_SAMPLE_ENABLED\fP   UART_ONE_BIT_SAMPLE_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_UART_ONEBIT_ENABLE\fP   __HAL_UART_ONE_BIT_SAMPLE_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_UART_ONEBIT_DISABLE\fP   __HAL_UART_ONE_BIT_SAMPLE_DISABLE"
.br
.ti -1c
.RI "#define \fB__DIV_SAMPLING16\fP   UART_DIV_SAMPLING16"
.br
.ti -1c
.RI "#define \fB__DIVMANT_SAMPLING16\fP   UART_DIVMANT_SAMPLING16"
.br
.ti -1c
.RI "#define \fB__DIVFRAQ_SAMPLING16\fP   UART_DIVFRAQ_SAMPLING16"
.br
.ti -1c
.RI "#define \fB__UART_BRR_SAMPLING16\fP   UART_BRR_SAMPLING16"
.br
.ti -1c
.RI "#define \fB__DIV_SAMPLING8\fP   UART_DIV_SAMPLING8"
.br
.ti -1c
.RI "#define \fB__DIVMANT_SAMPLING8\fP   UART_DIVMANT_SAMPLING8"
.br
.ti -1c
.RI "#define \fB__DIVFRAQ_SAMPLING8\fP   UART_DIVFRAQ_SAMPLING8"
.br
.ti -1c
.RI "#define \fB__UART_BRR_SAMPLING8\fP   UART_BRR_SAMPLING8"
.br
.ti -1c
.RI "#define \fB__DIV_LPUART\fP   UART_DIV_LPUART"
.br
.ti -1c
.RI "#define \fBUART_WAKEUPMETHODE_IDLELINE\fP   UART_WAKEUPMETHOD_IDLELINE"
.br
.ti -1c
.RI "#define \fBUART_WAKEUPMETHODE_ADDRESSMARK\fP   UART_WAKEUPMETHOD_ADDRESSMARK"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __DIV_LPUART   UART_DIV_LPUART"

.SS "#define __DIV_SAMPLING16   UART_DIV_SAMPLING16"

.SS "#define __DIV_SAMPLING8   UART_DIV_SAMPLING8"

.SS "#define __DIVFRAQ_SAMPLING16   UART_DIVFRAQ_SAMPLING16"

.SS "#define __DIVFRAQ_SAMPLING8   UART_DIVFRAQ_SAMPLING8"

.SS "#define __DIVMANT_SAMPLING16   UART_DIVMANT_SAMPLING16"

.SS "#define __DIVMANT_SAMPLING8   UART_DIVMANT_SAMPLING8"

.SS "#define __HAL_UART_ONEBIT_DISABLE   __HAL_UART_ONE_BIT_SAMPLE_DISABLE"

.SS "#define __HAL_UART_ONEBIT_ENABLE   __HAL_UART_ONE_BIT_SAMPLE_ENABLE"

.SS "#define __UART_BRR_SAMPLING16   UART_BRR_SAMPLING16"

.SS "#define __UART_BRR_SAMPLING8   UART_BRR_SAMPLING8"

.SS "#define UART_ONE_BIT_SAMPLE_DISABLED   UART_ONE_BIT_SAMPLE_DISABLE"

.SS "#define UART_ONE_BIT_SAMPLE_ENABLED   UART_ONE_BIT_SAMPLE_ENABLE"

.SS "#define UART_ONEBIT_SAMPLING_DISABLED   UART_ONE_BIT_SAMPLE_DISABLE"

.SS "#define UART_ONEBIT_SAMPLING_ENABLED   UART_ONE_BIT_SAMPLE_ENABLE"

.SS "#define UART_WAKEUPMETHODE_ADDRESSMARK   UART_WAKEUPMETHOD_ADDRESSMARK"

.SS "#define UART_WAKEUPMETHODE_IDLELINE   UART_WAKEUPMETHOD_IDLELINE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
