.TH "HAL_GPIO_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_GPIO_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGET_GPIO_SOURCE\fP   GPIO_GET_INDEX"
.br
.ti -1c
.RI "#define \fBGET_GPIO_INDEX\fP   GPIO_GET_INDEX"
.br
.ti -1c
.RI "#define \fBGPIO_AF0_LPTIM\fP   GPIO_AF0_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF1_LPTIM\fP   GPIO_AF1_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF2_LPTIM\fP   GPIO_AF2_LPTIM1"
.br
.ti -1c
.RI "#define \fBGPIO_AF6_DFSDM\fP   GPIO_AF6_DFSDM1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define GET_GPIO_INDEX   GPIO_GET_INDEX"

.SS "#define GET_GPIO_SOURCE   GPIO_GET_INDEX"

.SS "#define GPIO_AF0_LPTIM   GPIO_AF0_LPTIM1"

.SS "#define GPIO_AF1_LPTIM   GPIO_AF1_LPTIM1"

.SS "#define GPIO_AF2_LPTIM   GPIO_AF2_LPTIM1"

.SS "#define GPIO_AF6_DFSDM   GPIO_AF6_DFSDM1"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
