.TH "HAL_I2C_Aliased_Functions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2C_Aliased_Functions
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_I2CEx_AnalogFilter_Config\fP   HAL_I2CEx_ConfigAnalogFilter"
.br
.ti -1c
.RI "#define \fBHAL_I2CEx_DigitalFilter_Config\fP   HAL_I2CEx_ConfigDigitalFilter"
.br
.ti -1c
.RI "#define \fBHAL_FMPI2CEx_AnalogFilter_Config\fP   HAL_FMPI2CEx_ConfigAnalogFilter"
.br
.ti -1c
.RI "#define \fBHAL_FMPI2CEx_DigitalFilter_Config\fP   HAL_FMPI2CEx_ConfigDigitalFilter"
.br
.ti -1c
.RI "#define \fBHAL_I2CFastModePlusConfig\fP(SYSCFG_I2CFastModePlus,  cmd)   (((cmd)==\fBENABLE\fP)? HAL_I2CEx_EnableFastModePlus(SYSCFG_I2CFastModePlus): HAL_I2CEx_DisableFastModePlus(SYSCFG_I2CFastModePlus))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define HAL_FMPI2CEx_AnalogFilter_Config   HAL_FMPI2CEx_ConfigAnalogFilter"

.SS "#define HAL_FMPI2CEx_DigitalFilter_Config   HAL_FMPI2CEx_ConfigDigitalFilter"

.SS "#define HAL_I2CEx_AnalogFilter_Config   HAL_I2CEx_ConfigAnalogFilter"

.SS "#define HAL_I2CEx_DigitalFilter_Config   HAL_I2CEx_ConfigDigitalFilter"

.SS "#define HAL_I2CFastModePlusConfig(SYSCFG_I2CFastModePlus, cmd)   (((cmd)==\fBENABLE\fP)? HAL_I2CEx_EnableFastModePlus(SYSCFG_I2CFastModePlus): HAL_I2CEx_DisableFastModePlus(SYSCFG_I2CFastModePlus))"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
