.TH "HAL_SD_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_SD_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSD_OCR_CID_CSD_OVERWRIETE\fP   SD_OCR_CID_CSD_OVERWRITE"
.br
.ti -1c
.RI "#define \fBSD_CMD_SD_APP_STAUS\fP   SD_CMD_SD_APP_STATUS"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SD_CMD_SD_APP_STAUS   SD_CMD_SD_APP_STATUS"

.SS "#define SD_OCR_CID_CSD_OVERWRIETE   SD_OCR_CID_CSD_OVERWRITE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
