.TH "HAL_ADC_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_ADC_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__ADC_ENABLE\fP   __HAL_ADC_ENABLE"
.br
.ti -1c
.RI "#define \fB__ADC_DISABLE\fP   __HAL_ADC_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_ENABLING_CONDITIONS\fP   ADC_ENABLING_CONDITIONS"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_DISABLING_CONDITIONS\fP   ADC_DISABLING_CONDITIONS"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_IS_ENABLED\fP   ADC_IS_ENABLE"
.br
.ti -1c
.RI "#define \fB__ADC_IS_ENABLED\fP   ADC_IS_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_IS_SOFTWARE_START_REGULAR\fP   ADC_IS_SOFTWARE_START_REGULAR"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_IS_SOFTWARE_START_INJECTED\fP   ADC_IS_SOFTWARE_START_INJECTED"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_IS_CONVERSION_ONGOING_REGULAR_INJECTED\fP   ADC_IS_CONVERSION_ONGOING_REGULAR_INJECTED"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_IS_CONVERSION_ONGOING_REGULAR\fP   ADC_IS_CONVERSION_ONGOING_REGULAR"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_IS_CONVERSION_ONGOING_INJECTED\fP   ADC_IS_CONVERSION_ONGOING_INJECTED"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_IS_CONVERSION_ONGOING\fP   ADC_IS_CONVERSION_ONGOING"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CLEAR_ERRORCODE\fP   ADC_CLEAR_ERRORCODE"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_GET_RESOLUTION\fP   ADC_GET_RESOLUTION"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_JSQR_RK\fP   ADC_JSQR_RK"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_AWD1CH\fP   ADC_CFGR_AWD1CH_SHIFT"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_AWD23CR\fP   ADC_CFGR_AWD23CR"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_INJECT_AUTO_CONVERSION\fP   ADC_CFGR_INJECT_AUTO_CONVERSION"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_INJECT_CONTEXT_QUEUE\fP   ADC_CFGR_INJECT_CONTEXT_QUEUE"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_INJECT_DISCCONTINUOUS\fP   ADC_CFGR_INJECT_DISCCONTINUOUS"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_REG_DISCCONTINUOUS\fP   ADC_CFGR_REG_DISCCONTINUOUS"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_DISCONTINUOUS_NUM\fP   ADC_CFGR_DISCONTINUOUS_NUM"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_AUTOWAIT\fP   ADC_CFGR_AUTOWAIT"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_CONTINUOUS\fP   ADC_CFGR_CONTINUOUS"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_OVERRUN\fP   ADC_CFGR_OVERRUN"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_DMACONTREQ\fP   ADC_CFGR_DMACONTREQ"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR_EXTSEL\fP   ADC_CFGR_EXTSEL_SET"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_JSQR_JEXTSEL\fP   ADC_JSQR_JEXTSEL_SET"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_OFR_CHANNEL\fP   ADC_OFR_CHANNEL"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_DIFSEL_CHANNEL\fP   ADC_DIFSEL_CHANNEL"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CALFACT_DIFF_SET\fP   ADC_CALFACT_DIFF_SET"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CALFACT_DIFF_GET\fP   ADC_CALFACT_DIFF_GET"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_TRX_HIGHTHRESHOLD\fP   ADC_TRX_HIGHTHRESHOLD"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_OFFSET_SHIFT_RESOLUTION\fP   ADC_OFFSET_SHIFT_RESOLUTION"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_AWD1THRESHOLD_SHIFT_RESOLUTION\fP   ADC_AWD1THRESHOLD_SHIFT_RESOLUTION"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_AWD23THRESHOLD_SHIFT_RESOLUTION\fP   ADC_AWD23THRESHOLD_SHIFT_RESOLUTION"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_COMMON_REGISTER\fP   ADC_COMMON_REGISTER"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_COMMON_CCR_MULTI\fP   ADC_COMMON_CCR_MULTI"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_MULTIMODE_IS_ENABLED\fP   ADC_MULTIMODE_IS_ENABLE"
.br
.ti -1c
.RI "#define \fB__ADC_MULTIMODE_IS_ENABLED\fP   ADC_MULTIMODE_IS_ENABLE"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_NONMULTIMODE_OR_MULTIMODEMASTER\fP   ADC_NONMULTIMODE_OR_MULTIMODEMASTER"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_COMMON_ADC_OTHER\fP   ADC_COMMON_ADC_OTHER"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_MULTI_SLAVE\fP   ADC_MULTI_SLAVE"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_SQR1_L\fP   ADC_SQR1_L_SHIFT"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_JSQR_JL\fP   ADC_JSQR_JL_SHIFT"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_JSQR_RK_JL\fP   ADC_JSQR_RK_JL"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CR1_DISCONTINUOUS_NUM\fP   ADC_CR1_DISCONTINUOUS_NUM"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CR1_SCAN\fP   ADC_CR1_SCAN_SET"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CONVCYCLES_MAX_RANGE\fP   ADC_CONVCYCLES_MAX_RANGE"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CLOCK_PRESCALER_RANGE\fP   ADC_CLOCK_PRESCALER_RANGE"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_GET_CLOCK_PRESCALER\fP   ADC_GET_CLOCK_PRESCALER"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_SQR1\fP   ADC_SQR1"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_SMPR1\fP   ADC_SMPR1"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_SMPR2\fP   ADC_SMPR2"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_SQR3_RK\fP   ADC_SQR3_RK"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_SQR2_RK\fP   ADC_SQR2_RK"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_SQR1_RK\fP   ADC_SQR1_RK"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CR2_CONTINUOUS\fP   ADC_CR2_CONTINUOUS"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CR1_DISCONTINUOUS\fP   ADC_CR1_DISCONTINUOUS"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CR1_SCANCONV\fP   ADC_CR1_SCANCONV"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CR2_EOCSelection\fP   ADC_CR2_EOCSelection"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CR2_DMAContReq\fP   ADC_CR2_DMAContReq"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_JSQR\fP   ADC_JSQR"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CHSELR_CHANNEL\fP   ADC_CHSELR_CHANNEL"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR1_REG_DISCCONTINUOUS\fP   ADC_CFGR1_REG_DISCCONTINUOUS"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR1_AUTOOFF\fP   ADC_CFGR1_AUTOOFF"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR1_AUTOWAIT\fP   ADC_CFGR1_AUTOWAIT"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR1_CONTINUOUS\fP   ADC_CFGR1_CONTINUOUS"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR1_OVERRUN\fP   ADC_CFGR1_OVERRUN"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR1_SCANDIR\fP   ADC_CFGR1_SCANDIR"
.br
.ti -1c
.RI "#define \fB__HAL_ADC_CFGR1_DMACONTREQ\fP   ADC_CFGR1_DMACONTREQ"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __ADC_DISABLE   __HAL_ADC_DISABLE"

.SS "#define __ADC_ENABLE   __HAL_ADC_ENABLE"

.SS "#define __ADC_IS_ENABLED   ADC_IS_ENABLE"

.SS "#define __ADC_MULTIMODE_IS_ENABLED   ADC_MULTIMODE_IS_ENABLE"

.SS "#define __HAL_ADC_AWD1THRESHOLD_SHIFT_RESOLUTION   ADC_AWD1THRESHOLD_SHIFT_RESOLUTION"

.SS "#define __HAL_ADC_AWD23THRESHOLD_SHIFT_RESOLUTION   ADC_AWD23THRESHOLD_SHIFT_RESOLUTION"

.SS "#define __HAL_ADC_CALFACT_DIFF_GET   ADC_CALFACT_DIFF_GET"

.SS "#define __HAL_ADC_CALFACT_DIFF_SET   ADC_CALFACT_DIFF_SET"

.SS "#define __HAL_ADC_CFGR1_AUTOOFF   ADC_CFGR1_AUTOOFF"

.SS "#define __HAL_ADC_CFGR1_AUTOWAIT   ADC_CFGR1_AUTOWAIT"

.SS "#define __HAL_ADC_CFGR1_CONTINUOUS   ADC_CFGR1_CONTINUOUS"

.SS "#define __HAL_ADC_CFGR1_DMACONTREQ   ADC_CFGR1_DMACONTREQ"

.SS "#define __HAL_ADC_CFGR1_OVERRUN   ADC_CFGR1_OVERRUN"

.SS "#define __HAL_ADC_CFGR1_REG_DISCCONTINUOUS   ADC_CFGR1_REG_DISCCONTINUOUS"

.SS "#define __HAL_ADC_CFGR1_SCANDIR   ADC_CFGR1_SCANDIR"

.SS "#define __HAL_ADC_CFGR_AUTOWAIT   ADC_CFGR_AUTOWAIT"

.SS "#define __HAL_ADC_CFGR_AWD1CH   ADC_CFGR_AWD1CH_SHIFT"

.SS "#define __HAL_ADC_CFGR_AWD23CR   ADC_CFGR_AWD23CR"

.SS "#define __HAL_ADC_CFGR_CONTINUOUS   ADC_CFGR_CONTINUOUS"

.SS "#define __HAL_ADC_CFGR_DISCONTINUOUS_NUM   ADC_CFGR_DISCONTINUOUS_NUM"

.SS "#define __HAL_ADC_CFGR_DMACONTREQ   ADC_CFGR_DMACONTREQ"

.SS "#define __HAL_ADC_CFGR_EXTSEL   ADC_CFGR_EXTSEL_SET"

.SS "#define __HAL_ADC_CFGR_INJECT_AUTO_CONVERSION   ADC_CFGR_INJECT_AUTO_CONVERSION"

.SS "#define __HAL_ADC_CFGR_INJECT_CONTEXT_QUEUE   ADC_CFGR_INJECT_CONTEXT_QUEUE"

.SS "#define __HAL_ADC_CFGR_INJECT_DISCCONTINUOUS   ADC_CFGR_INJECT_DISCCONTINUOUS"

.SS "#define __HAL_ADC_CFGR_OVERRUN   ADC_CFGR_OVERRUN"

.SS "#define __HAL_ADC_CFGR_REG_DISCCONTINUOUS   ADC_CFGR_REG_DISCCONTINUOUS"

.SS "#define __HAL_ADC_CHSELR_CHANNEL   ADC_CHSELR_CHANNEL"

.SS "#define __HAL_ADC_CLEAR_ERRORCODE   ADC_CLEAR_ERRORCODE"

.SS "#define __HAL_ADC_CLOCK_PRESCALER_RANGE   ADC_CLOCK_PRESCALER_RANGE"

.SS "#define __HAL_ADC_COMMON_ADC_OTHER   ADC_COMMON_ADC_OTHER"

.SS "#define __HAL_ADC_COMMON_CCR_MULTI   ADC_COMMON_CCR_MULTI"

.SS "#define __HAL_ADC_COMMON_REGISTER   ADC_COMMON_REGISTER"

.SS "#define __HAL_ADC_CONVCYCLES_MAX_RANGE   ADC_CONVCYCLES_MAX_RANGE"

.SS "#define __HAL_ADC_CR1_DISCONTINUOUS   ADC_CR1_DISCONTINUOUS"

.SS "#define __HAL_ADC_CR1_DISCONTINUOUS_NUM   ADC_CR1_DISCONTINUOUS_NUM"

.SS "#define __HAL_ADC_CR1_SCAN   ADC_CR1_SCAN_SET"

.SS "#define __HAL_ADC_CR1_SCANCONV   ADC_CR1_SCANCONV"

.SS "#define __HAL_ADC_CR2_CONTINUOUS   ADC_CR2_CONTINUOUS"

.SS "#define __HAL_ADC_CR2_DMAContReq   ADC_CR2_DMAContReq"

.SS "#define __HAL_ADC_CR2_EOCSelection   ADC_CR2_EOCSelection"

.SS "#define __HAL_ADC_DIFSEL_CHANNEL   ADC_DIFSEL_CHANNEL"

.SS "#define __HAL_ADC_DISABLING_CONDITIONS   ADC_DISABLING_CONDITIONS"

.SS "#define __HAL_ADC_ENABLING_CONDITIONS   ADC_ENABLING_CONDITIONS"

.SS "#define __HAL_ADC_GET_CLOCK_PRESCALER   ADC_GET_CLOCK_PRESCALER"

.SS "#define __HAL_ADC_GET_RESOLUTION   ADC_GET_RESOLUTION"

.SS "#define __HAL_ADC_IS_CONVERSION_ONGOING   ADC_IS_CONVERSION_ONGOING"

.SS "#define __HAL_ADC_IS_CONVERSION_ONGOING_INJECTED   ADC_IS_CONVERSION_ONGOING_INJECTED"

.SS "#define __HAL_ADC_IS_CONVERSION_ONGOING_REGULAR   ADC_IS_CONVERSION_ONGOING_REGULAR"

.SS "#define __HAL_ADC_IS_CONVERSION_ONGOING_REGULAR_INJECTED   ADC_IS_CONVERSION_ONGOING_REGULAR_INJECTED"

.SS "#define __HAL_ADC_IS_ENABLED   ADC_IS_ENABLE"

.SS "#define __HAL_ADC_IS_SOFTWARE_START_INJECTED   ADC_IS_SOFTWARE_START_INJECTED"

.SS "#define __HAL_ADC_IS_SOFTWARE_START_REGULAR   ADC_IS_SOFTWARE_START_REGULAR"

.SS "#define __HAL_ADC_JSQR   ADC_JSQR"

.SS "#define __HAL_ADC_JSQR_JEXTSEL   ADC_JSQR_JEXTSEL_SET"

.SS "#define __HAL_ADC_JSQR_JL   ADC_JSQR_JL_SHIFT"

.SS "#define __HAL_ADC_JSQR_RK   ADC_JSQR_RK"

.SS "#define __HAL_ADC_JSQR_RK_JL   ADC_JSQR_RK_JL"

.SS "#define __HAL_ADC_MULTI_SLAVE   ADC_MULTI_SLAVE"

.SS "#define __HAL_ADC_MULTIMODE_IS_ENABLED   ADC_MULTIMODE_IS_ENABLE"

.SS "#define __HAL_ADC_NONMULTIMODE_OR_MULTIMODEMASTER   ADC_NONMULTIMODE_OR_MULTIMODEMASTER"

.SS "#define __HAL_ADC_OFFSET_SHIFT_RESOLUTION   ADC_OFFSET_SHIFT_RESOLUTION"

.SS "#define __HAL_ADC_OFR_CHANNEL   ADC_OFR_CHANNEL"

.SS "#define __HAL_ADC_SMPR1   ADC_SMPR1"

.SS "#define __HAL_ADC_SMPR2   ADC_SMPR2"

.SS "#define __HAL_ADC_SQR1   ADC_SQR1"

.SS "#define __HAL_ADC_SQR1_L   ADC_SQR1_L_SHIFT"

.SS "#define __HAL_ADC_SQR1_RK   ADC_SQR1_RK"

.SS "#define __HAL_ADC_SQR2_RK   ADC_SQR2_RK"

.SS "#define __HAL_ADC_SQR3_RK   ADC_SQR3_RK"

.SS "#define __HAL_ADC_TRX_HIGHTHRESHOLD   ADC_TRX_HIGHTHRESHOLD"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
