.TH "HAL_DBGMCU_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_DBGMCU_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM1_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM1"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM1_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM1"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM2_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM2\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM2_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM2\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM3_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_TIM3\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM3_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_TIM3\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM4_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM4"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM4_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM4"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM5_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM5"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM5_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM5"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM6_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM6"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM6_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM6"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM7_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM7"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM7_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM7"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM8_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM8"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM8_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM8"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM9_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM9"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM9_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM9"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM10_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM10"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM10_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM10"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM11_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM11"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM11_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM11"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM12_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM12"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM12_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM12"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM13_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM13"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM13_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM13"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM14_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM14"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM14_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM14"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_CAN2_DBGMCU\fP   __HAL_DBGMCU_FREEZE_CAN2"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_CAN2_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_CAN2"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM15_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM15"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM15_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM15"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM16_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM16"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM16_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM16"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_TIM17_DBGMCU\fP   __HAL_DBGMCU_FREEZE_TIM17"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_TIM17_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_TIM17"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_RTC_DBGMCU\fP   __HAL_DBGMCU_FREEZE_RTC"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_RTC_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_RTC"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_WWDG_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_WWDG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_WWDG_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_WWDG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_IWDG_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_IWDG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_IWDG_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_IWDG\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_I2C1_TIMEOUT_DBGMCU\fP   \fB__HAL_DBGMCU_FREEZE_I2C1_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_I2C1_TIMEOUT_DBGMCU\fP   \fB__HAL_DBGMCU_UNFREEZE_I2C1_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_I2C2_TIMEOUT_DBGMCU\fP   __HAL_DBGMCU_FREEZE_I2C2_TIMEOUT"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_I2C2_TIMEOUT_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_I2C2_TIMEOUT"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_I2C3_TIMEOUT_DBGMCU\fP   __HAL_DBGMCU_FREEZE_I2C3_TIMEOUT"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_I2C3_TIMEOUT_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_I2C3_TIMEOUT"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_CAN1_DBGMCU\fP   __HAL_DBGMCU_FREEZE_CAN1"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_CAN1_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_CAN1"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_LPTIM1_DBGMCU\fP   __HAL_DBGMCU_FREEZE_LPTIM1"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_LPTIM1_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_LPTIM1"
.br
.ti -1c
.RI "#define \fB__HAL_FREEZE_LPTIM2_DBGMCU\fP   __HAL_DBGMCU_FREEZE_LPTIM2"
.br
.ti -1c
.RI "#define \fB__HAL_UNFREEZE_LPTIM2_DBGMCU\fP   __HAL_DBGMCU_UNFREEZE_LPTIM2"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_FREEZE_CAN1_DBGMCU   __HAL_DBGMCU_FREEZE_CAN1"

.SS "#define __HAL_FREEZE_CAN2_DBGMCU   __HAL_DBGMCU_FREEZE_CAN2"

.SS "#define __HAL_FREEZE_I2C1_TIMEOUT_DBGMCU   \fB__HAL_DBGMCU_FREEZE_I2C1_TIMEOUT\fP"

.SS "#define __HAL_FREEZE_I2C2_TIMEOUT_DBGMCU   __HAL_DBGMCU_FREEZE_I2C2_TIMEOUT"

.SS "#define __HAL_FREEZE_I2C3_TIMEOUT_DBGMCU   __HAL_DBGMCU_FREEZE_I2C3_TIMEOUT"

.SS "#define __HAL_FREEZE_IWDG_DBGMCU   \fB__HAL_DBGMCU_FREEZE_IWDG\fP"

.SS "#define __HAL_FREEZE_LPTIM1_DBGMCU   __HAL_DBGMCU_FREEZE_LPTIM1"

.SS "#define __HAL_FREEZE_LPTIM2_DBGMCU   __HAL_DBGMCU_FREEZE_LPTIM2"

.SS "#define __HAL_FREEZE_RTC_DBGMCU   __HAL_DBGMCU_FREEZE_RTC"

.SS "#define __HAL_FREEZE_TIM10_DBGMCU   __HAL_DBGMCU_FREEZE_TIM10"

.SS "#define __HAL_FREEZE_TIM11_DBGMCU   __HAL_DBGMCU_FREEZE_TIM11"

.SS "#define __HAL_FREEZE_TIM12_DBGMCU   __HAL_DBGMCU_FREEZE_TIM12"

.SS "#define __HAL_FREEZE_TIM13_DBGMCU   __HAL_DBGMCU_FREEZE_TIM13"

.SS "#define __HAL_FREEZE_TIM14_DBGMCU   __HAL_DBGMCU_FREEZE_TIM14"

.SS "#define __HAL_FREEZE_TIM15_DBGMCU   __HAL_DBGMCU_FREEZE_TIM15"

.SS "#define __HAL_FREEZE_TIM16_DBGMCU   __HAL_DBGMCU_FREEZE_TIM16"

.SS "#define __HAL_FREEZE_TIM17_DBGMCU   __HAL_DBGMCU_FREEZE_TIM17"

.SS "#define __HAL_FREEZE_TIM1_DBGMCU   __HAL_DBGMCU_FREEZE_TIM1"

.SS "#define __HAL_FREEZE_TIM2_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM2\fP"

.SS "#define __HAL_FREEZE_TIM3_DBGMCU   \fB__HAL_DBGMCU_FREEZE_TIM3\fP"

.SS "#define __HAL_FREEZE_TIM4_DBGMCU   __HAL_DBGMCU_FREEZE_TIM4"

.SS "#define __HAL_FREEZE_TIM5_DBGMCU   __HAL_DBGMCU_FREEZE_TIM5"

.SS "#define __HAL_FREEZE_TIM6_DBGMCU   __HAL_DBGMCU_FREEZE_TIM6"

.SS "#define __HAL_FREEZE_TIM7_DBGMCU   __HAL_DBGMCU_FREEZE_TIM7"

.SS "#define __HAL_FREEZE_TIM8_DBGMCU   __HAL_DBGMCU_FREEZE_TIM8"

.SS "#define __HAL_FREEZE_TIM9_DBGMCU   __HAL_DBGMCU_FREEZE_TIM9"

.SS "#define __HAL_FREEZE_WWDG_DBGMCU   \fB__HAL_DBGMCU_FREEZE_WWDG\fP"

.SS "#define __HAL_UNFREEZE_CAN1_DBGMCU   __HAL_DBGMCU_UNFREEZE_CAN1"

.SS "#define __HAL_UNFREEZE_CAN2_DBGMCU   __HAL_DBGMCU_UNFREEZE_CAN2"

.SS "#define __HAL_UNFREEZE_I2C1_TIMEOUT_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_I2C1_TIMEOUT\fP"

.SS "#define __HAL_UNFREEZE_I2C2_TIMEOUT_DBGMCU   __HAL_DBGMCU_UNFREEZE_I2C2_TIMEOUT"

.SS "#define __HAL_UNFREEZE_I2C3_TIMEOUT_DBGMCU   __HAL_DBGMCU_UNFREEZE_I2C3_TIMEOUT"

.SS "#define __HAL_UNFREEZE_IWDG_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_IWDG\fP"

.SS "#define __HAL_UNFREEZE_LPTIM1_DBGMCU   __HAL_DBGMCU_UNFREEZE_LPTIM1"

.SS "#define __HAL_UNFREEZE_LPTIM2_DBGMCU   __HAL_DBGMCU_UNFREEZE_LPTIM2"

.SS "#define __HAL_UNFREEZE_RTC_DBGMCU   __HAL_DBGMCU_UNFREEZE_RTC"

.SS "#define __HAL_UNFREEZE_TIM10_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM10"

.SS "#define __HAL_UNFREEZE_TIM11_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM11"

.SS "#define __HAL_UNFREEZE_TIM12_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM12"

.SS "#define __HAL_UNFREEZE_TIM13_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM13"

.SS "#define __HAL_UNFREEZE_TIM14_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM14"

.SS "#define __HAL_UNFREEZE_TIM15_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM15"

.SS "#define __HAL_UNFREEZE_TIM16_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM16"

.SS "#define __HAL_UNFREEZE_TIM17_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM17"

.SS "#define __HAL_UNFREEZE_TIM1_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM1"

.SS "#define __HAL_UNFREEZE_TIM2_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM2\fP"

.SS "#define __HAL_UNFREEZE_TIM3_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_TIM3\fP"

.SS "#define __HAL_UNFREEZE_TIM4_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM4"

.SS "#define __HAL_UNFREEZE_TIM5_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM5"

.SS "#define __HAL_UNFREEZE_TIM6_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM6"

.SS "#define __HAL_UNFREEZE_TIM7_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM7"

.SS "#define __HAL_UNFREEZE_TIM8_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM8"

.SS "#define __HAL_UNFREEZE_TIM9_DBGMCU   __HAL_DBGMCU_UNFREEZE_TIM9"

.SS "#define __HAL_UNFREEZE_WWDG_DBGMCU   \fB__HAL_DBGMCU_UNFREEZE_WWDG\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
