.TH "HAL_I2S_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2S_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_I2S_INSTANCE\fP   IS_I2S_ALL_INSTANCE"
.br
.ti -1c
.RI "#define \fBIS_I2S_INSTANCE_EXT\fP   IS_I2S_ALL_INSTANCE_EXT"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_I2S_INSTANCE   IS_I2S_ALL_INSTANCE"

.SS "#define IS_I2S_INSTANCE_EXT   IS_I2S_ALL_INSTANCE_EXT"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
