.TH "HAL_PCCARD_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_PCCARD_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCF_DATA\fP   ATA_DATA"
.br
.ti -1c
.RI "#define \fBCF_SECTOR_COUNT\fP   ATA_SECTOR_COUNT"
.br
.ti -1c
.RI "#define \fBCF_SECTOR_NUMBER\fP   ATA_SECTOR_NUMBER"
.br
.ti -1c
.RI "#define \fBCF_CYLINDER_LOW\fP   ATA_CYLINDER_LOW"
.br
.ti -1c
.RI "#define \fBCF_CYLINDER_HIGH\fP   ATA_CYLINDER_HIGH"
.br
.ti -1c
.RI "#define \fBCF_CARD_HEAD\fP   ATA_CARD_HEAD"
.br
.ti -1c
.RI "#define \fBCF_STATUS_CMD\fP   ATA_STATUS_CMD"
.br
.ti -1c
.RI "#define \fBCF_STATUS_CMD_ALTERNATE\fP   ATA_STATUS_CMD_ALTERNATE"
.br
.ti -1c
.RI "#define \fBCF_COMMON_DATA_AREA\fP   ATA_COMMON_DATA_AREA"
.br
.ti -1c
.RI "#define \fBCF_READ_SECTOR_CMD\fP   ATA_READ_SECTOR_CMD"
.br
.ti -1c
.RI "#define \fBCF_WRITE_SECTOR_CMD\fP   ATA_WRITE_SECTOR_CMD"
.br
.ti -1c
.RI "#define \fBCF_ERASE_SECTOR_CMD\fP   ATA_ERASE_SECTOR_CMD"
.br
.ti -1c
.RI "#define \fBCF_IDENTIFY_CMD\fP   ATA_IDENTIFY_CMD"
.br
.ti -1c
.RI "#define \fBPCCARD_StatusTypedef\fP   HAL_PCCARD_StatusTypeDef"
.br
.ti -1c
.RI "#define \fBPCCARD_SUCCESS\fP   HAL_PCCARD_STATUS_SUCCESS"
.br
.ti -1c
.RI "#define \fBPCCARD_ONGOING\fP   HAL_PCCARD_STATUS_ONGOING"
.br
.ti -1c
.RI "#define \fBPCCARD_ERROR\fP   HAL_PCCARD_STATUS_ERROR"
.br
.ti -1c
.RI "#define \fBPCCARD_TIMEOUT\fP   HAL_PCCARD_STATUS_TIMEOUT"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CF_CARD_HEAD   ATA_CARD_HEAD"

.SS "#define CF_COMMON_DATA_AREA   ATA_COMMON_DATA_AREA"

.SS "#define CF_CYLINDER_HIGH   ATA_CYLINDER_HIGH"

.SS "#define CF_CYLINDER_LOW   ATA_CYLINDER_LOW"

.SS "#define CF_DATA   ATA_DATA"

.SS "#define CF_ERASE_SECTOR_CMD   ATA_ERASE_SECTOR_CMD"

.SS "#define CF_IDENTIFY_CMD   ATA_IDENTIFY_CMD"

.SS "#define CF_READ_SECTOR_CMD   ATA_READ_SECTOR_CMD"

.SS "#define CF_SECTOR_COUNT   ATA_SECTOR_COUNT"

.SS "#define CF_SECTOR_NUMBER   ATA_SECTOR_NUMBER"

.SS "#define CF_STATUS_CMD   ATA_STATUS_CMD"

.SS "#define CF_STATUS_CMD_ALTERNATE   ATA_STATUS_CMD_ALTERNATE"

.SS "#define CF_WRITE_SECTOR_CMD   ATA_WRITE_SECTOR_CMD"

.SS "#define PCCARD_ERROR   HAL_PCCARD_STATUS_ERROR"

.SS "#define PCCARD_ONGOING   HAL_PCCARD_STATUS_ONGOING"

.SS "#define PCCARD_StatusTypedef   HAL_PCCARD_StatusTypeDef"

.SS "#define PCCARD_SUCCESS   HAL_PCCARD_STATUS_SUCCESS"

.SS "#define PCCARD_TIMEOUT   HAL_PCCARD_STATUS_TIMEOUT"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
