.TH "HAL_I2C_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_I2C_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_I2C_RESET_CR2\fP   I2C_RESET_CR2"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_GENERATE_START\fP   I2C_GENERATE_START"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_FREQ_RANGE\fP   I2C_FREQ_RANGE"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_RISE_TIME\fP   I2C_RISE_TIME"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_SPEED_STANDARD\fP   I2C_SPEED_STANDARD"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_SPEED_FAST\fP   I2C_SPEED_FAST"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_SPEED\fP   I2C_SPEED"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_7BIT_ADD_WRITE\fP   I2C_7BIT_ADD_WRITE"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_7BIT_ADD_READ\fP   I2C_7BIT_ADD_READ"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_10BIT_ADDRESS\fP   I2C_10BIT_ADDRESS"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_10BIT_HEADER_WRITE\fP   I2C_10BIT_HEADER_WRITE"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_10BIT_HEADER_READ\fP   I2C_10BIT_HEADER_READ"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_MEM_ADD_MSB\fP   I2C_MEM_ADD_MSB"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_MEM_ADD_LSB\fP   I2C_MEM_ADD_LSB"
.br
.ti -1c
.RI "#define \fB__HAL_I2C_FREQRANGE\fP   I2C_FREQRANGE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_I2C_10BIT_ADDRESS   I2C_10BIT_ADDRESS"

.SS "#define __HAL_I2C_10BIT_HEADER_READ   I2C_10BIT_HEADER_READ"

.SS "#define __HAL_I2C_10BIT_HEADER_WRITE   I2C_10BIT_HEADER_WRITE"

.SS "#define __HAL_I2C_7BIT_ADD_READ   I2C_7BIT_ADD_READ"

.SS "#define __HAL_I2C_7BIT_ADD_WRITE   I2C_7BIT_ADD_WRITE"

.SS "#define __HAL_I2C_FREQ_RANGE   I2C_FREQ_RANGE"

.SS "#define __HAL_I2C_FREQRANGE   I2C_FREQRANGE"

.SS "#define __HAL_I2C_GENERATE_START   I2C_GENERATE_START"

.SS "#define __HAL_I2C_MEM_ADD_LSB   I2C_MEM_ADD_LSB"

.SS "#define __HAL_I2C_MEM_ADD_MSB   I2C_MEM_ADD_MSB"

.SS "#define __HAL_I2C_RESET_CR2   I2C_RESET_CR2"

.SS "#define __HAL_I2C_RISE_TIME   I2C_RISE_TIME"

.SS "#define __HAL_I2C_SPEED   I2C_SPEED"

.SS "#define __HAL_I2C_SPEED_FAST   I2C_SPEED_FAST"

.SS "#define __HAL_I2C_SPEED_STANDARD   I2C_SPEED_STANDARD"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
