.TH "HAL_USART_Aliased_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_USART_Aliased_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__USART_ENABLE_IT\fP   __HAL_USART_ENABLE_IT"
.br
.ti -1c
.RI "#define \fB__USART_DISABLE_IT\fP   __HAL_USART_DISABLE_IT"
.br
.ti -1c
.RI "#define \fB__USART_ENABLE\fP   __HAL_USART_ENABLE"
.br
.ti -1c
.RI "#define \fB__USART_DISABLE\fP   __HAL_USART_DISABLE"
.br
.ti -1c
.RI "#define \fB__HAL_USART_GETCLOCKSOURCE\fP   USART_GETCLOCKSOURCE"
.br
.ti -1c
.RI "#define \fB__USART_GETCLOCKSOURCE\fP   USART_GETCLOCKSOURCE"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_USART_GETCLOCKSOURCE   USART_GETCLOCKSOURCE"

.SS "#define __USART_DISABLE   __HAL_USART_DISABLE"

.SS "#define __USART_DISABLE_IT   __HAL_USART_DISABLE_IT"

.SS "#define __USART_ENABLE   __HAL_USART_ENABLE"

.SS "#define __USART_ENABLE_IT   __HAL_USART_ENABLE_IT"

.SS "#define __USART_GETCLOCKSOURCE   USART_GETCLOCKSOURCE"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
