.TH "HAL_RTC_Aliased_Defines" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HAL_RTC_Aliased_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFORMAT_BIN\fP   RTC_FORMAT_BIN"
.br
.ti -1c
.RI "#define \fBFORMAT_BCD\fP   RTC_FORMAT_BCD"
.br
.ti -1c
.RI "#define \fBRTC_ALARMSUBSECONDMASK_None\fP   RTC_ALARMSUBSECONDMASK_NONE"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERERASEBACKUP_DISABLED\fP   RTC_TAMPER_ERASE_BACKUP_DISABLE"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERMASK_FLAG_DISABLED\fP   RTC_TAMPERMASK_FLAG_DISABLE"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERMASK_FLAG_ENABLED\fP   RTC_TAMPERMASK_FLAG_ENABLE"
.br
.ti -1c
.RI "#define \fBRTC_MASKTAMPERFLAG_DISABLED\fP   RTC_TAMPERMASK_FLAG_DISABLE"
.br
.ti -1c
.RI "#define \fBRTC_MASKTAMPERFLAG_ENABLED\fP   RTC_TAMPERMASK_FLAG_ENABLE"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERERASEBACKUP_ENABLED\fP   RTC_TAMPER_ERASE_BACKUP_ENABLE"
.br
.ti -1c
.RI "#define \fBRTC_TAMPER1_2_INTERRUPT\fP   RTC_ALL_TAMPER_INTERRUPT"
.br
.ti -1c
.RI "#define \fBRTC_TAMPER1_2_3_INTERRUPT\fP   RTC_ALL_TAMPER_INTERRUPT"
.br
.ti -1c
.RI "#define \fBRTC_TIMESTAMPPIN_PC13\fP   RTC_TIMESTAMPPIN_DEFAULT"
.br
.ti -1c
.RI "#define \fBRTC_TIMESTAMPPIN_PA0\fP   RTC_TIMESTAMPPIN_POS1"
.br
.ti -1c
.RI "#define \fBRTC_TIMESTAMPPIN_PI8\fP   RTC_TIMESTAMPPIN_POS1"
.br
.ti -1c
.RI "#define \fBRTC_TIMESTAMPPIN_PC1\fP   RTC_TIMESTAMPPIN_POS2"
.br
.ti -1c
.RI "#define \fBRTC_OUTPUT_REMAP_PC13\fP   RTC_OUTPUT_REMAP_NONE"
.br
.ti -1c
.RI "#define \fBRTC_OUTPUT_REMAP_PB14\fP   RTC_OUTPUT_REMAP_POS1"
.br
.ti -1c
.RI "#define \fBRTC_OUTPUT_REMAP_PB2\fP   RTC_OUTPUT_REMAP_POS1"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPIN_PC13\fP   RTC_TAMPERPIN_DEFAULT"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPIN_PA0\fP   RTC_TAMPERPIN_POS1"
.br
.ti -1c
.RI "#define \fBRTC_TAMPERPIN_PI8\fP   RTC_TAMPERPIN_POS1"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FORMAT_BCD   RTC_FORMAT_BCD"

.SS "#define FORMAT_BIN   RTC_FORMAT_BIN"

.SS "#define RTC_ALARMSUBSECONDMASK_None   RTC_ALARMSUBSECONDMASK_NONE"

.SS "#define RTC_MASKTAMPERFLAG_DISABLED   RTC_TAMPERMASK_FLAG_DISABLE"

.SS "#define RTC_MASKTAMPERFLAG_ENABLED   RTC_TAMPERMASK_FLAG_ENABLE"

.SS "#define RTC_OUTPUT_REMAP_PB14   RTC_OUTPUT_REMAP_POS1"

.SS "#define RTC_OUTPUT_REMAP_PB2   RTC_OUTPUT_REMAP_POS1"

.SS "#define RTC_OUTPUT_REMAP_PC13   RTC_OUTPUT_REMAP_NONE"

.SS "#define RTC_TAMPER1_2_3_INTERRUPT   RTC_ALL_TAMPER_INTERRUPT"

.SS "#define RTC_TAMPER1_2_INTERRUPT   RTC_ALL_TAMPER_INTERRUPT"

.SS "#define RTC_TAMPERERASEBACKUP_DISABLED   RTC_TAMPER_ERASE_BACKUP_DISABLE"

.SS "#define RTC_TAMPERERASEBACKUP_ENABLED   RTC_TAMPER_ERASE_BACKUP_ENABLE"

.SS "#define RTC_TAMPERMASK_FLAG_DISABLED   RTC_TAMPERMASK_FLAG_DISABLE"

.SS "#define RTC_TAMPERMASK_FLAG_ENABLED   RTC_TAMPERMASK_FLAG_ENABLE"

.SS "#define RTC_TAMPERPIN_PA0   RTC_TAMPERPIN_POS1"

.SS "#define RTC_TAMPERPIN_PC13   RTC_TAMPERPIN_DEFAULT"

.SS "#define RTC_TAMPERPIN_PI8   RTC_TAMPERPIN_POS1"

.SS "#define RTC_TIMESTAMPPIN_PA0   RTC_TIMESTAMPPIN_POS1"

.SS "#define RTC_TIMESTAMPPIN_PC1   RTC_TIMESTAMPPIN_POS2"

.SS "#define RTC_TIMESTAMPPIN_PC13   RTC_TIMESTAMPPIN_DEFAULT"

.SS "#define RTC_TIMESTAMPPIN_PI8   RTC_TIMESTAMPPIN_POS1"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
