.TH "I2C_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_TypeDef \- Inter Integrated Circuit Interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOAR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOAR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTRISE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Inter Integrated Circuit Interface\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t I2C_TypeDef::CCR"

.SS "\fB__IO\fP uint32_t I2C_TypeDef::CR1"

.SS "\fB__IO\fP uint32_t I2C_TypeDef::CR2"

.SS "\fB__IO\fP uint32_t I2C_TypeDef::DR"

.SS "\fB__IO\fP uint32_t I2C_TypeDef::OAR1"

.SS "\fB__IO\fP uint32_t I2C_TypeDef::OAR2"

.SS "\fB__IO\fP uint32_t I2C_TypeDef::SR1"

.SS "\fB__IO\fP uint32_t I2C_TypeDef::SR2"

.SS "\fB__IO\fP uint32_t I2C_TypeDef::TRISE"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
