.TH "ITM_Type" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ITM_Type \- Structure type to access the Instrumentation Trace Macrocell Register (ITM)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_sc300\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__OM\fP uint8_t \fBITM_Type::u8\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint16_t \fBITM_Type::u16\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint32_t \fBITM_Type::u32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [864U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBTER\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [15U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBTPR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [15U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBTCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [29U]"
.br
.ti -1c
.RI "\fB__OM\fP uint32_t \fBIWR\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBIRR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBIMCR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [43U]"
.br
.ti -1c
.RI "\fB__OM\fP uint32_t \fBLAR\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBLSR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [1U]"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBDEVARCH\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [4U]"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID4\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID5\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID6\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID7\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID0\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID1\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID2\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBPID3\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBCID0\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBCID1\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBCID2\fP"
.br
.ti -1c
.RI "\fB__IM\fP uint32_t \fBCID3\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__OM\fP uint8_t \fBITM_Type::u8\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint16_t \fBITM_Type::u16\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint32_t \fBITM_Type::u32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__OM\fP uint8_t \fBITM_Type::u8\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint16_t \fBITM_Type::u16\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint32_t \fBITM_Type::u32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__OM\fP uint8_t \fBITM_Type::u8\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint16_t \fBITM_Type::u16\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint32_t \fBITM_Type::u32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__OM\fP uint8_t \fBITM_Type::u8\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint16_t \fBITM_Type::u16\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint32_t \fBITM_Type::u32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB__OM\fP uint8_t \fBITM_Type::u8\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint16_t \fBITM_Type::u16\fP"
.br
.ti -1c
.RI "   \fB__OM\fP uint32_t \fBITM_Type::u32\fP"
.br
.ti -1c
.RI "} \fBPORT\fP [32U]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Instrumentation Trace Macrocell Register (ITM)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
