.TH "IWDG_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWDG_TypeDef \- Independent WATCHDOG\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBKR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Independent WATCHDOG\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::KR"
Key register, Address offset: 0x00 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::PR"
Prescaler register, Address offset: 0x04 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::RLR"
Reload register, Address offset: 0x08 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::SR"
Status register, Address offset: 0x0C 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
