.TH "Library_configuration_section" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library_configuration_section
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTM32F1\fP"
.br
.RI "STM32 Family\&. "
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION_MAIN\fP   (0x04)"
.br
.RI "Comment the line below if you will not use the peripherals drivers\&. In this case, these drivers will not be included and the application code will be based on direct access to peripherals registers\&. "
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION_SUB1\fP   (0x03)"
.br
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION_SUB2\fP   (0x02)"
.br
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION_RC\fP   (0x00)"
.br
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __STM32F1_CMSIS_VERSION"
\fBValue:\fP
.PP
.nf
((__STM32F1_CMSIS_VERSION_MAIN << 24)\
                                       |(__STM32F1_CMSIS_VERSION_SUB1 << 16)\
                                       |(__STM32F1_CMSIS_VERSION_SUB2 << 8 )\
                                       |(__STM32F1_CMSIS_VERSION_RC))
.fi
.SS "#define __STM32F1_CMSIS_VERSION_MAIN   (0x04)"

.PP
Comment the line below if you will not use the peripherals drivers\&. In this case, these drivers will not be included and the application code will be based on direct access to peripherals registers\&. < STM32F100C4, STM32F100R4, STM32F100C6, STM32F100R6, STM32F100C8, STM32F100R8, STM32F100V8, STM32F100CB, STM32F100RB and STM32F100VB
.PP
< STM32F100RC, STM32F100VC, STM32F100ZC, STM32F100RD, STM32F100VD, STM32F100ZD, STM32F100RE, STM32F100VE and STM32F100ZE
.PP
< STM32F101C4, STM32F101R4, STM32F101T4, STM32F101C6, STM32F101R6 and STM32F101T6 Devices
.PP
< STM32F101C8, STM32F101R8, STM32F101T8, STM32F101V8, STM32F101CB, STM32F101RB, STM32F101TB and STM32F101VB
.PP
< STM32F101RC, STM32F101VC, STM32F101ZC, STM32F101RD, STM32F101VD, STM32F101ZD, STM32F101RE, STM32F101VE and STM32F101ZE
.PP
< STM32F101RF, STM32F101VF, STM32F101ZF, STM32F101RG, STM32F101VG and STM32F101ZG
.PP
< STM32F102C4, STM32F102R4, STM32F102C6 and STM32F102R6
.PP
< STM32F102C8, STM32F102R8, STM32F102CB and STM32F102RB
.PP
< STM32F103C4, STM32F103R4, STM32F103T4, STM32F103C6, STM32F103R6 and STM32F103T6
.PP
< STM32F103C8, STM32F103R8, STM32F103T8, STM32F103V8, STM32F103CB, STM32F103RB, STM32F103TB and STM32F103VB
.PP
< STM32F103RC, STM32F103VC, STM32F103ZC, STM32F103RD, STM32F103VD, STM32F103ZD, STM32F103RE, STM32F103VE and STM32F103ZE
.PP
< STM32F103RF, STM32F103VF, STM32F103ZF, STM32F103RG, STM32F103VG and STM32F103ZG
.PP
< STM32F105R8, STM32F105V8, STM32F105RB, STM32F105VB, STM32F105RC and STM32F105VC
.PP
< STM32F107RB, STM32F107VB, STM32F107RC and STM32F107VC
.PP
CMSIS Device version number V4\&.3\&.2 [31:24] main version 
.SS "#define __STM32F1_CMSIS_VERSION_RC   (0x00)"
[7:0] release candidate 
.SS "#define __STM32F1_CMSIS_VERSION_SUB1   (0x03)"
[23:16] sub1 version 
.SS "#define __STM32F1_CMSIS_VERSION_SUB2   (0x02)"
[15:8] sub2 version 
.SS "#define STM32F1"

.PP
STM32 Family\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
