.TH "NVIC_Type" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NVIC_Type \- Structure type to access the Nested Vectored Interrupt Controller (NVIC)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_sc300\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBISER\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [16U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBICER\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRSERVED1\fP [16U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBISPR\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP [16U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBICPR\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP [16U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBIABR\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP [16U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBITNS\fP [16U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [16U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBIPR\fP [124U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint8_t \fBIPR\fP [496U]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED6\fP [580U]"
.br
.ti -1c
.RI "\fB__OM\fP uint32_t \fBSTIR\fP"
.br
.ti -1c
.RI "\fB__IOM\fP uint32_t \fBIP\fP [8U]"
.br
.ti -1c
.RI "\fB__IOM\fP uint8_t \fBIP\fP [240U]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure type to access the Nested Vectored Interrupt Controller (NVIC)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
