.TH "OB_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OB_TypeDef \- Option Bytes Registers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRDP\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBUSER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBData0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBData1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Option Bytes Registers\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint16_t OB_TypeDef::Data0"

.SS "\fB__IO\fP uint16_t OB_TypeDef::Data1"

.SS "\fB__IO\fP uint16_t OB_TypeDef::RDP"

.SS "\fB__IO\fP uint16_t OB_TypeDef::USER"

.SS "\fB__IO\fP uint16_t OB_TypeDef::WRP0"

.SS "\fB__IO\fP uint16_t OB_TypeDef::WRP1"

.SS "\fB__IO\fP uint16_t OB_TypeDef::WRP2"

.SS "\fB__IO\fP uint16_t OB_TypeDef::WRP3"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
