.TH "PWR_WakeUp_Pins" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_WakeUp_Pins
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_WAKEUP_PIN1\fP   \fBPWR_CSR_EWUP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_WAKEUP_PIN1   \fBPWR_CSR_EWUP\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
