.TH "PWR_Exported_Constants" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPWR PVD detection level\fP"
.br
.ti -1c
.RI "\fBPWR PVD Mode\fP"
.br
.ti -1c
.RI "\fBPWR WakeUp Pins\fP"
.br
.ti -1c
.RI "\fBPWR Regulator state in SLEEP/STOP mode\fP"
.br
.ti -1c
.RI "\fBPWR SLEEP mode entry\fP"
.br
.ti -1c
.RI "\fBPWR STOP mode entry\fP"
.br
.ti -1c
.RI "\fBPWR Flag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
