.TH "PWR_SLEEP_mode_entry" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_SLEEP_mode_entry
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_SLEEPENTRY_WFI\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBPWR_SLEEPENTRY_WFE\fP   ((uint8_t)0x02)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PWR_SLEEPENTRY_WFE   ((uint8_t)0x02)"

.SS "#define PWR_SLEEPENTRY_WFI   ((uint8_t)0x01)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
