.TH "PWR_Exported_Functions_Group1" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_PWR_DeInit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_EnableBkUpAccess\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_PWR_DisableBkUpAccess\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void HAL_PWR_DeInit (void)"

.SS "void HAL_PWR_DisableBkUpAccess (void)"

.SS "void HAL_PWR_EnableBkUpAccess (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
