.TH "RCC_Register_Offset" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Register_Offset
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_OFFSET\fP   (\fBRCC_BASE\fP \- \fBPERIPH_BASE\fP)"
.br
.ti -1c
.RI "#define \fBRCC_CR_OFFSET\fP   0x00U"
.br
.ti -1c
.RI "#define \fBRCC_CFGR_OFFSET\fP   0x04U"
.br
.ti -1c
.RI "#define \fBRCC_CIR_OFFSET\fP   0x08U"
.br
.ti -1c
.RI "#define \fBRCC_BDCR_OFFSET\fP   0x20U"
.br
.ti -1c
.RI "#define \fBRCC_CSR_OFFSET\fP   0x24U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_BDCR_OFFSET   0x20U"

.SS "#define RCC_CFGR_OFFSET   0x04U"

.SS "#define RCC_CIR_OFFSET   0x08U"

.SS "#define RCC_CR_OFFSET   0x00U"

.SS "#define RCC_CSR_OFFSET   0x24U"

.SS "#define RCC_OFFSET   (\fBRCC_BASE\fP \- \fBPERIPH_BASE\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
