.TH "RCC_APB1_APB2_Clock_Source" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_APB1_APB2_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_HCLK_DIV1\fP   \fBRCC_CFGR_PPRE1_DIV1\fP"
.br
.ti -1c
.RI "#define \fBRCC_HCLK_DIV2\fP   \fBRCC_CFGR_PPRE1_DIV2\fP"
.br
.ti -1c
.RI "#define \fBRCC_HCLK_DIV4\fP   \fBRCC_CFGR_PPRE1_DIV4\fP"
.br
.ti -1c
.RI "#define \fBRCC_HCLK_DIV8\fP   \fBRCC_CFGR_PPRE1_DIV8\fP"
.br
.ti -1c
.RI "#define \fBRCC_HCLK_DIV16\fP   \fBRCC_CFGR_PPRE1_DIV16\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_HCLK_DIV1   \fBRCC_CFGR_PPRE1_DIV1\fP"
HCLK not divided 
.SS "#define RCC_HCLK_DIV16   \fBRCC_CFGR_PPRE1_DIV16\fP"
HCLK divided by 16 
.SS "#define RCC_HCLK_DIV2   \fBRCC_CFGR_PPRE1_DIV2\fP"
HCLK divided by 2 
.SS "#define RCC_HCLK_DIV4   \fBRCC_CFGR_PPRE1_DIV4\fP"
HCLK divided by 4 
.SS "#define RCC_HCLK_DIV8   \fBRCC_CFGR_PPRE1_DIV8\fP"
HCLK divided by 8 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
