.TH "RCC_AHB_Clock_Source" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_AHB_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV1\fP   \fBRCC_CFGR_HPRE_DIV1\fP"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV2\fP   \fBRCC_CFGR_HPRE_DIV2\fP"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV4\fP   \fBRCC_CFGR_HPRE_DIV4\fP"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV8\fP   \fBRCC_CFGR_HPRE_DIV8\fP"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV16\fP   \fBRCC_CFGR_HPRE_DIV16\fP"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV64\fP   \fBRCC_CFGR_HPRE_DIV64\fP"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV128\fP   \fBRCC_CFGR_HPRE_DIV128\fP"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV256\fP   \fBRCC_CFGR_HPRE_DIV256\fP"
.br
.ti -1c
.RI "#define \fBRCC_SYSCLK_DIV512\fP   \fBRCC_CFGR_HPRE_DIV512\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_SYSCLK_DIV1   \fBRCC_CFGR_HPRE_DIV1\fP"
SYSCLK not divided 
.SS "#define RCC_SYSCLK_DIV128   \fBRCC_CFGR_HPRE_DIV128\fP"
SYSCLK divided by 128 
.SS "#define RCC_SYSCLK_DIV16   \fBRCC_CFGR_HPRE_DIV16\fP"
SYSCLK divided by 16 
.SS "#define RCC_SYSCLK_DIV2   \fBRCC_CFGR_HPRE_DIV2\fP"
SYSCLK divided by 2 
.SS "#define RCC_SYSCLK_DIV256   \fBRCC_CFGR_HPRE_DIV256\fP"
SYSCLK divided by 256 
.SS "#define RCC_SYSCLK_DIV4   \fBRCC_CFGR_HPRE_DIV4\fP"
SYSCLK divided by 4 
.SS "#define RCC_SYSCLK_DIV512   \fBRCC_CFGR_HPRE_DIV512\fP"
SYSCLK divided by 512 
.SS "#define RCC_SYSCLK_DIV64   \fBRCC_CFGR_HPRE_DIV64\fP"
SYSCLK divided by 64 
.SS "#define RCC_SYSCLK_DIV8   \fBRCC_CFGR_HPRE_DIV8\fP"
SYSCLK divided by 8 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
