.TH "RCC_APB1_Force_Release_Reset" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_APB1_Force_Release_Reset \- Force or release APB1 peripheral reset\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_APB1_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR = 0xFFFFFFFFU)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM2_FORCE_RESET\fP()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_TIM2RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM3_FORCE_RESET\fP()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_TIM3RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_WWDG_FORCE_RESET\fP()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_WWDGRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART2_FORCE_RESET\fP()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_USART2RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_I2C1_FORCE_RESET\fP()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_I2C1RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_BKP_FORCE_RESET\fP()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_BKPRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_PWR_FORCE_RESET\fP()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_PWRRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_APB1_RELEASE_RESET\fP()   (\fBRCC\fP\->APB1RSTR = 0x00)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM2_RELEASE_RESET\fP()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_TIM2RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM3_RELEASE_RESET\fP()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_TIM3RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_WWDG_RELEASE_RESET\fP()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_WWDGRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART2_RELEASE_RESET\fP()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_USART2RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_I2C1_RELEASE_RESET\fP()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_I2C1RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_BKP_RELEASE_RESET\fP()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_BKPRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_PWR_RELEASE_RESET\fP()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_PWRRST\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Force or release APB1 peripheral reset\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RCC_APB1_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR = 0xFFFFFFFFU)"

.SS "#define __HAL_RCC_APB1_RELEASE_RESET()   (\fBRCC\fP\->APB1RSTR = 0x00)"

.SS "#define __HAL_RCC_BKP_FORCE_RESET()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_BKPRST\fP))"

.SS "#define __HAL_RCC_BKP_RELEASE_RESET()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_BKPRST\fP))"

.SS "#define __HAL_RCC_I2C1_FORCE_RESET()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_I2C1RST\fP))"

.SS "#define __HAL_RCC_I2C1_RELEASE_RESET()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_I2C1RST\fP))"

.SS "#define __HAL_RCC_PWR_FORCE_RESET()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_PWRRST\fP))"

.SS "#define __HAL_RCC_PWR_RELEASE_RESET()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_PWRRST\fP))"

.SS "#define __HAL_RCC_TIM2_FORCE_RESET()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_TIM2RST\fP))"

.SS "#define __HAL_RCC_TIM2_RELEASE_RESET()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_TIM2RST\fP))"

.SS "#define __HAL_RCC_TIM3_FORCE_RESET()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_TIM3RST\fP))"

.SS "#define __HAL_RCC_TIM3_RELEASE_RESET()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_TIM3RST\fP))"

.SS "#define __HAL_RCC_USART2_FORCE_RESET()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_USART2RST\fP))"

.SS "#define __HAL_RCC_USART2_RELEASE_RESET()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_USART2RST\fP))"

.SS "#define __HAL_RCC_WWDG_FORCE_RESET()   (\fBRCC\fP\->APB1RSTR |= (\fBRCC_APB1RSTR_WWDGRST\fP))"

.SS "#define __HAL_RCC_WWDG_RELEASE_RESET()   (\fBRCC\fP\->APB1RSTR &= ~(\fBRCC_APB1RSTR_WWDGRST\fP))"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
