.TH "RCC_LSI_Configuration" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_LSI_Configuration
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_LSI_ENABLE\fP()   (*(\fB__IO\fP uint32_t *) \fBRCC_CSR_LSION_BB\fP = \fBENABLE\fP)"
.br
.RI "Macro to enable the Internal Low Speed oscillator (LSI)\&. "
.ti -1c
.RI "#define \fB__HAL_RCC_LSI_DISABLE\fP()   (*(\fB__IO\fP uint32_t *) \fBRCC_CSR_LSION_BB\fP = \fBDISABLE\fP)"
.br
.RI "Macro to disable the Internal Low Speed oscillator (LSI)\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RCC_LSI_DISABLE()   (*(\fB__IO\fP uint32_t *) \fBRCC_CSR_LSION_BB\fP = \fBDISABLE\fP)"

.PP
Macro to disable the Internal Low Speed oscillator (LSI)\&. 
.PP
\fBNote\fP
.RS 4
LSI can not be disabled if the IWDG is running\&. 
.PP
When the LSI is stopped, LSIRDY flag goes low after 6 LSI oscillator clock cycles\&. 
.RE
.PP

.SS "#define __HAL_RCC_LSI_ENABLE()   (*(\fB__IO\fP uint32_t *) \fBRCC_CSR_LSION_BB\fP = \fBENABLE\fP)"

.PP
Macro to enable the Internal Low Speed oscillator (LSI)\&. 
.PP
\fBNote\fP
.RS 4
After enabling the LSI, the application software should wait on LSIRDY flag to be set indicating that LSI clock is stable and can be used to clock the IWDG and/or the RTC\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
