.TH "RCC_HSE_Configuration" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_HSE_Configuration
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_HSE_CONFIG\fP(__STATE__)"
.br
.RI "Macro to configure the External High Speed oscillator (HSE)\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RCC_HSE_CONFIG(__STATE__)"
\fBValue:\fP
.PP
.nf
do{                                                     \
                      if ((__STATE__) == RCC_HSE_ON)                        \
                      {                                                     \
                        SET_BIT(RCC->CR, RCC_CR_HSEON);                     \
                      }                                                     \
                      else if ((__STATE__) == RCC_HSE_OFF)                  \
                      {                                                     \
                        CLEAR_BIT(RCC->CR, RCC_CR_HSEON);                   \
                        CLEAR_BIT(RCC->CR, RCC_CR_HSEBYP);                  \
                      }                                                     \
                      else if ((__STATE__) == RCC_HSE_BYPASS)               \
                      {                                                     \
                        SET_BIT(RCC->CR, RCC_CR_HSEBYP);                    \
                        SET_BIT(RCC->CR, RCC_CR_HSEON);                     \
                      }                                                     \
                      else                                                  \
                      {                                                     \
                        CLEAR_BIT(RCC->CR, RCC_CR_HSEON);                   \
                        CLEAR_BIT(RCC->CR, RCC_CR_HSEBYP);                  \
                      }                                                     \
                    }while(0U)
.fi
.PP
Macro to configure the External High Speed oscillator (HSE)\&. 
.PP
\fBNote\fP
.RS 4
Transition HSE Bypass to HSE On and HSE On to HSE Bypass are not supported by this macro\&. User should request a transition to HSE Off first and then HSE On or HSE Bypass\&. 
.PP
After enabling the HSE (RCC_HSE_ON or RCC_HSE_Bypass), the application software should wait on HSERDY flag to be set indicating that HSE clock is stable and can be used to clock the PLL and/or system clock\&. 
.PP
HSE state can not be changed if it is used directly or through the PLL as system clock\&. In this case, you have to select another source of the system clock then change the HSE state (ex\&. disable it)\&. 
.PP
The HSE is stopped by hardware when entering STOP and STANDBY modes\&. 
.PP
This function reset the CSSON bit, so if the clock security system(CSS) was previously enabled you have to enable it again after calling this function\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fI<strong>STATE</strong>\fP specifies the new state of the HSE\&. This parameter can be one of the following values: 
.PD 0

.IP "\(bu" 2
\fBRCC_HSE_OFF\fP turn OFF the HSE oscillator, HSERDY flag goes low after 6 HSE oscillator clock cycles\&. 
.IP "\(bu" 2
\fBRCC_HSE_ON\fP turn ON the HSE oscillator 
.IP "\(bu" 2
\fBRCC_HSE_BYPASS\fP HSE oscillator bypassed with external clock 
.PP
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
