.TH "RCC_PeriphCLKInitTypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_PeriphCLKInitTypeDef \- RCC extended clocks structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f1xx_hal_rcc_ex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBPeriphClockSelection\fP"
.br
.ti -1c
.RI "uint32_t \fBRTCClockSelection\fP"
.br
.ti -1c
.RI "uint32_t \fBAdcClockSelection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RCC extended clocks structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t RCC_PeriphCLKInitTypeDef::AdcClockSelection"
ADC clock source This parameter can be a value of \fBADC Prescaler\fP 
.SS "uint32_t RCC_PeriphCLKInitTypeDef::PeriphClockSelection"
The Extended Clock to be configured\&. This parameter can be a value of \fBPeriph Clock Selection\fP 
.SS "uint32_t RCC_PeriphCLKInitTypeDef::RTCClockSelection"
specifies the RTC clock source\&. This parameter can be a value of \fBRTC Clock Source\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
