.TH "RCC_Oscillator_Type" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Oscillator_Type
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_HSE\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_HSI\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_LSE\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBRCC_OSCILLATORTYPE_LSI\fP   0x00000008U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_OSCILLATORTYPE_HSE   0x00000001U"

.SS "#define RCC_OSCILLATORTYPE_HSI   0x00000002U"

.SS "#define RCC_OSCILLATORTYPE_LSE   0x00000004U"

.SS "#define RCC_OSCILLATORTYPE_LSI   0x00000008U"

.SS "#define RCC_OSCILLATORTYPE_NONE   0x00000000U"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
