.TH "RCC_Timeout" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Timeout
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_DBP_TIMEOUT_VALUE\fP   100U    /* 100 ms */"
.br
.ti -1c
.RI "#define \fBRCC_LSE_TIMEOUT_VALUE\fP   \fBLSE_STARTUP_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fBCLOCKSWITCH_TIMEOUT_VALUE\fP   5000    /* 5 s    */"
.br
.ti -1c
.RI "#define \fBHSE_TIMEOUT_VALUE\fP   \fBHSE_STARTUP_TIMEOUT\fP"
.br
.ti -1c
.RI "#define \fBHSI_TIMEOUT_VALUE\fP   2U      /* 2 ms (minimum Tick + 1) */"
.br
.ti -1c
.RI "#define \fBLSI_TIMEOUT_VALUE\fP   2U      /* 2 ms (minimum Tick + 1) */"
.br
.ti -1c
.RI "#define \fBPLL_TIMEOUT_VALUE\fP   2U      /* 2 ms (minimum Tick + 1) */"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CLOCKSWITCH_TIMEOUT_VALUE   5000    /* 5 s    */"

.SS "#define HSE_TIMEOUT_VALUE   \fBHSE_STARTUP_TIMEOUT\fP"

.SS "#define HSI_TIMEOUT_VALUE   2U      /* 2 ms (minimum Tick + 1) */"

.SS "#define LSI_TIMEOUT_VALUE   2U      /* 2 ms (minimum Tick + 1) */"

.SS "#define PLL_TIMEOUT_VALUE   2U      /* 2 ms (minimum Tick + 1) */"

.SS "#define RCC_DBP_TIMEOUT_VALUE   100U    /* 100 ms */"

.SS "#define RCC_LSE_TIMEOUT_VALUE   \fBLSE_STARTUP_TIMEOUT\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
