.TH "RCC_APB2_Peripheral_Clock_Enable_Disable_Status" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_APB2_Peripheral_Clock_Enable_Disable_Status \- Get the enable or disable status of the APB2 peripheral clock\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_AFIO_IS_CLK_ENABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_AFIOEN\fP)) != \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_AFIO_IS_CLK_DISABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_AFIOEN\fP)) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOA_IS_CLK_ENABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPAEN\fP)) != \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOA_IS_CLK_DISABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPAEN\fP)) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOB_IS_CLK_ENABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPBEN\fP)) != \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOB_IS_CLK_DISABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPBEN\fP)) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOC_IS_CLK_ENABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPCEN\fP)) != \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOC_IS_CLK_DISABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPCEN\fP)) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOD_IS_CLK_ENABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPDEN\fP)) != \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOD_IS_CLK_DISABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPDEN\fP)) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_ADC1_IS_CLK_ENABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_ADC1EN\fP)) != \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_ADC1_IS_CLK_DISABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_ADC1EN\fP)) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM1_IS_CLK_ENABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_TIM1EN\fP)) != \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM1_IS_CLK_DISABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_TIM1EN\fP)) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI1_IS_CLK_ENABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_SPI1EN\fP)) != \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI1_IS_CLK_DISABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_SPI1EN\fP)) == \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART1_IS_CLK_ENABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_USART1EN\fP)) != \fBRESET\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART1_IS_CLK_DISABLED\fP()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_USART1EN\fP)) == \fBRESET\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Get the enable or disable status of the APB2 peripheral clock\&. 


.PP
\fBNote\fP
.RS 4
After reset, the peripheral clock (used for registers read/write access) is disabled and the application software has to enable this clock before using it\&. 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RCC_ADC1_IS_CLK_DISABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_ADC1EN\fP)) == \fBRESET\fP)"

.SS "#define __HAL_RCC_ADC1_IS_CLK_ENABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_ADC1EN\fP)) != \fBRESET\fP)"

.SS "#define __HAL_RCC_AFIO_IS_CLK_DISABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_AFIOEN\fP)) == \fBRESET\fP)"

.SS "#define __HAL_RCC_AFIO_IS_CLK_ENABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_AFIOEN\fP)) != \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOA_IS_CLK_DISABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPAEN\fP)) == \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOA_IS_CLK_ENABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPAEN\fP)) != \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOB_IS_CLK_DISABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPBEN\fP)) == \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOB_IS_CLK_ENABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPBEN\fP)) != \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOC_IS_CLK_DISABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPCEN\fP)) == \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOC_IS_CLK_ENABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPCEN\fP)) != \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOD_IS_CLK_DISABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPDEN\fP)) == \fBRESET\fP)"

.SS "#define __HAL_RCC_GPIOD_IS_CLK_ENABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_IOPDEN\fP)) != \fBRESET\fP)"

.SS "#define __HAL_RCC_SPI1_IS_CLK_DISABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_SPI1EN\fP)) == \fBRESET\fP)"

.SS "#define __HAL_RCC_SPI1_IS_CLK_ENABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_SPI1EN\fP)) != \fBRESET\fP)"

.SS "#define __HAL_RCC_TIM1_IS_CLK_DISABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_TIM1EN\fP)) == \fBRESET\fP)"

.SS "#define __HAL_RCC_TIM1_IS_CLK_ENABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_TIM1EN\fP)) != \fBRESET\fP)"

.SS "#define __HAL_RCC_USART1_IS_CLK_DISABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_USART1EN\fP)) == \fBRESET\fP)"

.SS "#define __HAL_RCC_USART1_IS_CLK_ENABLED()   ((\fBRCC\fP\->APB2ENR & (\fBRCC_APB2ENR_USART1EN\fP)) != \fBRESET\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
