.TH "RCC_Alias_For_Legacy" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Alias_For_Legacy
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_SYSCFG_CLK_DISABLE\fP   \fB__HAL_RCC_AFIO_CLK_DISABLE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SYSCFG_CLK_ENABLE\fP   \fB__HAL_RCC_AFIO_CLK_ENABLE\fP"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SYSCFG_FORCE_RESET\fP   \fB__HAL_RCC_AFIO_FORCE_RESET\fP"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SYSCFG_RELEASE_RESET\fP   \fB__HAL_RCC_AFIO_RELEASE_RESET\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RCC_SYSCFG_CLK_DISABLE   \fB__HAL_RCC_AFIO_CLK_DISABLE\fP"

.SS "#define __HAL_RCC_SYSCFG_CLK_ENABLE   \fB__HAL_RCC_AFIO_CLK_ENABLE\fP"

.SS "#define __HAL_RCC_SYSCFG_FORCE_RESET   \fB__HAL_RCC_AFIO_FORCE_RESET\fP"

.SS "#define __HAL_RCC_SYSCFG_RELEASE_RESET   \fB__HAL_RCC_AFIO_RELEASE_RESET\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
