.TH "RCC_PLL_Config" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_PLL_Config
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_PLL_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_PLL_OFF\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBRCC_PLL_ON\fP   0x00000002U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_PLL_NONE   0x00000000U"
PLL is not configured 
.SS "#define RCC_PLL_OFF   0x00000001U"
PLL deactivation 
.SS "#define RCC_PLL_ON   0x00000002U"
PLL activation 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
