.TH "RCC_HSI_Config" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_HSI_Config
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_HSI_OFF\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_HSI_ON\fP   \fBRCC_CR_HSION\fP"
.br
.ti -1c
.RI "#define \fBRCC_HSICALIBRATION_DEFAULT\fP   0x10U         /* Default HSI calibration trimming value */"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_HSI_OFF   0x00000000U"
HSI clock deactivation 
.SS "#define RCC_HSI_ON   \fBRCC_CR_HSION\fP"
HSI clock activation 
.SS "#define RCC_HSICALIBRATION_DEFAULT   0x10U         /* Default HSI calibration trimming value */"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
