.TH "RCC_Exported_Functions_Group1" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_Exported_Functions_Group1
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RCC_DeInit\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RCC_OscConfig\fP (\fBRCC_OscInitTypeDef\fP *RCC_OscInitStruct)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_RCC_ClockConfig\fP (\fBRCC_ClkInitTypeDef\fP *RCC_ClkInitStruct, uint32_t FLatency)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_RCC_ClockConfig (\fBRCC_ClkInitTypeDef\fP * RCC_ClkInitStruct, uint32_t FLatency)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RCC_DeInit (void)"

.SS "\fBHAL_StatusTypeDef\fP HAL_RCC_OscConfig (\fBRCC_OscInitTypeDef\fP * RCC_OscInitStruct)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
