.TH "RCC_APB2_Force_Release_Reset" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_APB2_Force_Release_Reset \- Force or release APB2 peripheral reset\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_RCC_APB2_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR = 0xFFFFFFFFU)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_AFIO_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_AFIORST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOA_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_IOPARST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOB_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_IOPBRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOC_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_IOPCRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOD_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_IOPDRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_ADC1_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_ADC1RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM1_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_TIM1RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI1_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_SPI1RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART1_FORCE_RESET\fP()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_USART1RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_APB2_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR = 0x00)"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_AFIO_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_AFIORST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOA_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_IOPARST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOB_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_IOPBRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOC_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_IOPCRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_GPIOD_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_IOPDRST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_ADC1_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_ADC1RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_TIM1_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_TIM1RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_SPI1_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_SPI1RST\fP))"
.br
.ti -1c
.RI "#define \fB__HAL_RCC_USART1_RELEASE_RESET\fP()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_USART1RST\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Force or release APB2 peripheral reset\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define __HAL_RCC_ADC1_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_ADC1RST\fP))"

.SS "#define __HAL_RCC_ADC1_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_ADC1RST\fP))"

.SS "#define __HAL_RCC_AFIO_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_AFIORST\fP))"

.SS "#define __HAL_RCC_AFIO_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_AFIORST\fP))"

.SS "#define __HAL_RCC_APB2_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR = 0xFFFFFFFFU)"

.SS "#define __HAL_RCC_APB2_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR = 0x00)"

.SS "#define __HAL_RCC_GPIOA_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_IOPARST\fP))"

.SS "#define __HAL_RCC_GPIOA_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_IOPARST\fP))"

.SS "#define __HAL_RCC_GPIOB_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_IOPBRST\fP))"

.SS "#define __HAL_RCC_GPIOB_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_IOPBRST\fP))"

.SS "#define __HAL_RCC_GPIOC_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_IOPCRST\fP))"

.SS "#define __HAL_RCC_GPIOC_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_IOPCRST\fP))"

.SS "#define __HAL_RCC_GPIOD_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_IOPDRST\fP))"

.SS "#define __HAL_RCC_GPIOD_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_IOPDRST\fP))"

.SS "#define __HAL_RCC_SPI1_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_SPI1RST\fP))"

.SS "#define __HAL_RCC_SPI1_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_SPI1RST\fP))"

.SS "#define __HAL_RCC_TIM1_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_TIM1RST\fP))"

.SS "#define __HAL_RCC_TIM1_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_TIM1RST\fP))"

.SS "#define __HAL_RCC_USART1_FORCE_RESET()   (\fBRCC\fP\->APB2RSTR |= (\fBRCC_APB2RSTR_USART1RST\fP))"

.SS "#define __HAL_RCC_USART1_RELEASE_RESET()   (\fBRCC\fP\->APB2RSTR &= ~(\fBRCC_APB2RSTR_USART1RST\fP))"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
