.TH "RCC_System_Clock_Type" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_System_Clock_Type
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_CLOCKTYPE_SYSCLK\fP   0x00000001U"
.br
.ti -1c
.RI "#define \fBRCC_CLOCKTYPE_HCLK\fP   0x00000002U"
.br
.ti -1c
.RI "#define \fBRCC_CLOCKTYPE_PCLK1\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBRCC_CLOCKTYPE_PCLK2\fP   0x00000008U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_CLOCKTYPE_HCLK   0x00000002U"
HCLK to configure 
.SS "#define RCC_CLOCKTYPE_PCLK1   0x00000004U"
PCLK1 to configure 
.SS "#define RCC_CLOCKTYPE_PCLK2   0x00000008U"
PCLK2 to configure 
.SS "#define RCC_CLOCKTYPE_SYSCLK   0x00000001U"
SYSCLK to configure 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
