.TH "RCC_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_TypeDef \- Reset and Clock Control\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCFGR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCIR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB2RSTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB1RSTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAHBENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB2ENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB1ENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBDCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reset and Clock Control\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t RCC_TypeDef::AHBENR"

.SS "\fB__IO\fP uint32_t RCC_TypeDef::APB1ENR"

.SS "\fB__IO\fP uint32_t RCC_TypeDef::APB1RSTR"

.SS "\fB__IO\fP uint32_t RCC_TypeDef::APB2ENR"

.SS "\fB__IO\fP uint32_t RCC_TypeDef::APB2RSTR"

.SS "\fB__IO\fP uint32_t RCC_TypeDef::BDCR"

.SS "\fB__IO\fP uint32_t RCC_TypeDef::CFGR"

.SS "\fB__IO\fP uint32_t RCC_TypeDef::CIR"

.SS "\fB__IO\fP uint32_t RCC_TypeDef::CR"

.SS "\fB__IO\fP uint32_t RCC_TypeDef::CSR"


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
