.TH "RCC_RTC_Clock_Source" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_RTC_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_NO_CLK\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_LSE\fP   \fBRCC_BDCR_RTCSEL_LSE\fP"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_LSI\fP   \fBRCC_BDCR_RTCSEL_LSI\fP"
.br
.ti -1c
.RI "#define \fBRCC_RTCCLKSOURCE_HSE_DIV128\fP   \fBRCC_BDCR_RTCSEL_HSE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_RTCCLKSOURCE_HSE_DIV128   \fBRCC_BDCR_RTCSEL_HSE\fP"
HSE oscillator clock divided by 128 used as RTC clock 
.SS "#define RCC_RTCCLKSOURCE_LSE   \fBRCC_BDCR_RTCSEL_LSE\fP"
LSE oscillator clock used as RTC clock 
.SS "#define RCC_RTCCLKSOURCE_LSI   \fBRCC_BDCR_RTCSEL_LSI\fP"
LSI oscillator clock used as RTC clock 
.SS "#define RCC_RTCCLKSOURCE_NO_CLK   0x00000000U"
No clock 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
