.TH "RCCEx_Private_Macros" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_Private_Macros
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_RCC_HSE_PREDIV\fP(__DIV__)   (((__DIV__) == \fBRCC_HSE_PREDIV_DIV1\fP)  || ((__DIV__) == \fBRCC_HSE_PREDIV_DIV2\fP))"
.br
.ti -1c
.RI "#define \fBIS_RCC_PLL_MUL\fP(__MUL__)"
.br
.ti -1c
.RI "#define \fBIS_RCC_MCO1SOURCE\fP(__SOURCE__)"
.br
.ti -1c
.RI "#define \fBIS_RCC_ADCPLLCLK_DIV\fP(__ADCCLK__)"
.br
.ti -1c
.RI "#define \fBIS_RCC_PERIPHCLOCK\fP(__SELECTION__)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_RCC_ADCPLLCLK_DIV(__ADCCLK__)"
\fBValue:\fP
.PP
.nf
(((__ADCCLK__) == RCC_ADCPCLK2_DIV2)  || ((__ADCCLK__) == RCC_ADCPCLK2_DIV4)   || \
                                          ((__ADCCLK__) == RCC_ADCPCLK2_DIV6)  || ((__ADCCLK__) == RCC_ADCPCLK2_DIV8))
.fi
.SS "#define IS_RCC_HSE_PREDIV(__DIV__)   (((__DIV__) == \fBRCC_HSE_PREDIV_DIV1\fP)  || ((__DIV__) == \fBRCC_HSE_PREDIV_DIV2\fP))"

.SS "#define IS_RCC_MCO1SOURCE(__SOURCE__)"
\fBValue:\fP
.PP
.nf
(((__SOURCE__) == RCC_MCO1SOURCE_SYSCLK)  || ((__SOURCE__) == RCC_MCO1SOURCE_HSI) \
                                    || ((__SOURCE__) == RCC_MCO1SOURCE_HSE)     || ((__SOURCE__) == RCC_MCO1SOURCE_PLLCLK) \
                                    || ((__SOURCE__) == RCC_MCO1SOURCE_NOCLOCK))
.fi
.SS "#define IS_RCC_PERIPHCLOCK(__SELECTION__)"
\fBValue:\fP
.PP
.nf
((((__SELECTION__) & RCC_PERIPHCLK_RTC)  == RCC_PERIPHCLK_RTC)  || \
                (((__SELECTION__) & RCC_PERIPHCLK_ADC)  == RCC_PERIPHCLK_ADC))
.fi
.SS "#define IS_RCC_PLL_MUL(__MUL__)"
\fBValue:\fP
.PP
.nf
(((__MUL__) == RCC_PLL_MUL2)  || ((__MUL__) == RCC_PLL_MUL3)  || \
                                 ((__MUL__) == RCC_PLL_MUL4)  || ((__MUL__) == RCC_PLL_MUL5)  || \
                                 ((__MUL__) == RCC_PLL_MUL6)  || ((__MUL__) == RCC_PLL_MUL7)  || \
                                 ((__MUL__) == RCC_PLL_MUL8)  || ((__MUL__) == RCC_PLL_MUL9)  || \
                                 ((__MUL__) == RCC_PLL_MUL10) || ((__MUL__) == RCC_PLL_MUL11) || \
                                 ((__MUL__) == RCC_PLL_MUL12) || ((__MUL__) == RCC_PLL_MUL13) || \
                                 ((__MUL__) == RCC_PLL_MUL14) || ((__MUL__) == RCC_PLL_MUL15) || \
                                 ((__MUL__) == RCC_PLL_MUL16))
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
