.TH "RCCEx_AHB1_Peripheral_Clock_Enable_Disable_Status" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_AHB1_Peripheral_Clock_Enable_Disable_Status \- Get the enable or disable status of the AHB1 peripheral clock\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Get the enable or disable status of the AHB1 peripheral clock\&. 


.PP
\fBNote\fP
.RS 4
After reset, the peripheral clock (used for registers read/write access) is disabled and the application software has to enable this clock before using it\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
