.TH "RCCEx_ADC_Prescaler" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCCEx_ADC_Prescaler
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_ADCPCLK2_DIV2\fP   \fBRCC_CFGR_ADCPRE_DIV2\fP"
.br
.ti -1c
.RI "#define \fBRCC_ADCPCLK2_DIV4\fP   \fBRCC_CFGR_ADCPRE_DIV4\fP"
.br
.ti -1c
.RI "#define \fBRCC_ADCPCLK2_DIV6\fP   \fBRCC_CFGR_ADCPRE_DIV6\fP"
.br
.ti -1c
.RI "#define \fBRCC_ADCPCLK2_DIV8\fP   \fBRCC_CFGR_ADCPRE_DIV8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define RCC_ADCPCLK2_DIV2   \fBRCC_CFGR_ADCPRE_DIV2\fP"

.SS "#define RCC_ADCPCLK2_DIV4   \fBRCC_CFGR_ADCPRE_DIV4\fP"

.SS "#define RCC_ADCPCLK2_DIV6   \fBRCC_CFGR_ADCPRE_DIV6\fP"

.SS "#define RCC_ADCPCLK2_DIV8   \fBRCC_CFGR_ADCPRE_DIV8\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
