.TH "Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal.h" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal.h \- This file contains all the functions prototypes for the HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx_hal_conf\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM2\fP()   \fBSET_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_TIM2_STOP\fP)"
.br
.RI "TIM2 Peripherals Debug mode\&. "
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM2\fP()   \fBCLEAR_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_TIM2_STOP\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_TIM3\fP()   \fBSET_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_TIM3_STOP\fP)"
.br
.RI "TIM3 Peripherals Debug mode\&. "
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_TIM3\fP()   \fBCLEAR_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_TIM3_STOP\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_WWDG\fP()   \fBSET_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_WWDG_STOP\fP)"
.br
.RI "WWDG Peripherals Debug mode\&. "
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_WWDG\fP()   \fBCLEAR_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_WWDG_STOP\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_IWDG\fP()   \fBSET_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_IWDG_STOP\fP)"
.br
.RI "IWDG Peripherals Debug mode\&. "
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_IWDG\fP()   \fBCLEAR_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_IWDG_STOP\fP)"
.br
.ti -1c
.RI "#define \fB__HAL_DBGMCU_FREEZE_I2C1_TIMEOUT\fP()   \fBSET_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_I2C1_SMBUS_TIMEOUT\fP)"
.br
.RI "I2C1 Peripherals Debug mode\&. "
.ti -1c
.RI "#define \fB__HAL_DBGMCU_UNFREEZE_I2C1_TIMEOUT\fP()   \fBCLEAR_BIT\fP(\fBDBGMCU\fP\->CR, \fBDBGMCU_CR_DBG_I2C1_SMBUS_TIMEOUT\fP)"
.br
.ti -1c
.RI "#define \fBIS_TICKFREQ\fP(FREQ)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHAL_TickFreqTypeDef\fP { \fBHAL_TICK_FREQ_10HZ\fP = 100U, \fBHAL_TICK_FREQ_100HZ\fP = 10U, \fBHAL_TICK_FREQ_1KHZ\fP = 1U, \fBHAL_TICK_FREQ_DEFAULT\fP = HAL_TICK_FREQ_1KHZ }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_Init\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_DeInit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_MspInit\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_MspDeInit\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_InitTick\fP (uint32_t TickPriority)"
.br
.ti -1c
.RI "void \fBHAL_IncTick\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_Delay\fP (uint32_t Delay)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetTick\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetTickPrio\fP (void)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_SetTickFreq\fP (\fBHAL_TickFreqTypeDef\fP Freq)"
.br
.ti -1c
.RI "\fBHAL_TickFreqTypeDef\fP \fBHAL_GetTickFreq\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_SuspendTick\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_ResumeTick\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetHalVersion\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetREVID\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetDEVID\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetUIDw0\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetUIDw1\fP (void)"
.br
.ti -1c
.RI "uint32_t \fBHAL_GetUIDw2\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_EnableDBGSleepMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_DisableDBGSleepMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_EnableDBGStopMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_DisableDBGStopMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_EnableDBGStandbyMode\fP (void)"
.br
.ti -1c
.RI "void \fBHAL_DBGMCU_DisableDBGStandbyMode\fP (void)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBuwTick\fP"
.br
.ti -1c
.RI "uint32_t \fBuwTickPrio\fP"
.br
.ti -1c
.RI "\fBHAL_TickFreqTypeDef\fP \fBuwTickFreq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains all the functions prototypes for the HAL module driver\&. 


.PP
\fBAuthor\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2017 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
