.TH "Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c \- GPIO Extension HAL module driver\&. This file provides firmware functions to manage the following functionalities of the General Purpose Input/Output (GPIO) extension peripheral\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx_hal\&.h'\fP
.br

.SH "Detailed Description"
.PP 
GPIO Extension HAL module driver\&. This file provides firmware functions to manage the following functionalities of the General Purpose Input/Output (GPIO) extension peripheral\&. 


.PP
\fBAuthor\fP
.RS 4
MCD Application Team
.IP "\(bu" 2
Extended features functions
.PP
.RE
.PP
.PP
.nf
==============================================================================
                  ##### GPIO Peripheral extension features #####
==============================================================================
[..] GPIO module on STM32F1 family, manage also the AFIO register:
     (+) Possibility to use the EVENTOUT Cortex feature

                   ##### How to use this driver #####
==============================================================================
[..] This driver provides functions to use EVENTOUT Cortex feature
  (#) Configure EVENTOUT Cortex feature using the function HAL_GPIOEx_ConfigEventout()
  (#) Activate EVENTOUT Cortex feature using the HAL_GPIOEx_EnableEventout()
  (#) Deactivate EVENTOUT Cortex feature using the HAL_GPIOEx_DisableEventout().fi
.PP
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
