.TH "Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_dma_ex.h" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_dma_ex.h \- Header file of DMA HAL extension module\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx_hal_def\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__HAL_DMA_GET_TC_FLAG_INDEX\fP(__HANDLE__)"
.br
.RI "Returns the current DMA Channel transfer complete flag\&. "
.ti -1c
.RI "#define \fB__HAL_DMA_GET_HT_FLAG_INDEX\fP(__HANDLE__)"
.br
.RI "Return the current DMA Channel half transfer complete flag\&. "
.ti -1c
.RI "#define \fB__HAL_DMA_GET_TE_FLAG_INDEX\fP(__HANDLE__)"
.br
.RI "Return the current DMA Channel transfer error flag\&. "
.ti -1c
.RI "#define \fB__HAL_DMA_GET_GI_FLAG_INDEX\fP(__HANDLE__)"
.br
.RI "Return the current DMA Channel Global interrupt flag\&. "
.ti -1c
.RI "#define \fB__HAL_DMA_GET_FLAG\fP(__HANDLE__,  __FLAG__)   (\fBDMA1\fP\->ISR & (__FLAG__))"
.br
.RI "Get the DMA Channel pending flags\&. "
.ti -1c
.RI "#define \fB__HAL_DMA_CLEAR_FLAG\fP(__HANDLE__,  __FLAG__)   (\fBDMA1\fP\->IFCR = (__FLAG__))"
.br
.RI "Clear the DMA Channel pending flags\&. "
.in -1c
.SH "Detailed Description"
.PP 
Header file of DMA HAL extension module\&. 


.PP
\fBAuthor\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
