.TH "Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c \- HAL module driver\&. This is the common part of the HAL initialization\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx_hal\&.h'\fP
.br

.SH "Detailed Description"
.PP 
HAL module driver\&. This is the common part of the HAL initialization\&. 


.PP
\fBAuthor\fP
.RS 4
MCD Application Team 
.PP
.nf
==============================================================================
                   ##### How to use this driver #####
==============================================================================
  [..]
  The common HAL driver contains a set of generic and common APIs that can be
  used by the PPP peripheral drivers and the user to start using the HAL.
  [..]
  The HAL contains two APIs' categories:
       (+) Common HAL APIs
       (+) Services HAL APIs
.fi
.PP
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
