.TH "Drivers/CMSIS/Device/ST/STM32F1xx/Include/stm32f1xx.h" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/CMSIS/Device/ST/STM32F1xx/Include/stm32f1xx.h \- CMSIS STM32F1xx Device Peripheral Access Layer Header File\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTM32F1\fP"
.br
.RI "STM32 Family\&. "
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION_MAIN\fP   (0x04)"
.br
.RI "Comment the line below if you will not use the peripherals drivers\&. In this case, these drivers will not be included and the application code will be based on direct access to peripherals registers\&. "
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION_SUB1\fP   (0x03)"
.br
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION_SUB2\fP   (0x02)"
.br
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION_RC\fP   (0x00)"
.br
.ti -1c
.RI "#define \fB__STM32F1_CMSIS_VERSION\fP"
.br
.ti -1c
.RI "#define \fBIS_FUNCTIONAL_STATE\fP(STATE)   (((STATE) == \fBDISABLE\fP) || ((STATE) == \fBENABLE\fP))"
.br
.ti -1c
.RI "#define \fBSET_BIT\fP(REG,  BIT)   ((REG) |= (BIT))"
.br
.ti -1c
.RI "#define \fBCLEAR_BIT\fP(REG,  BIT)   ((REG) &= ~(BIT))"
.br
.ti -1c
.RI "#define \fBREAD_BIT\fP(REG,  BIT)   ((REG) & (BIT))"
.br
.ti -1c
.RI "#define \fBCLEAR_REG\fP(REG)   ((REG) = (0x0))"
.br
.ti -1c
.RI "#define \fBWRITE_REG\fP(REG,  VAL)   ((REG) = (VAL))"
.br
.ti -1c
.RI "#define \fBREAD_REG\fP(REG)   ((REG))"
.br
.ti -1c
.RI "#define \fBMODIFY_REG\fP(REG,  CLEARMASK,  SETMASK)   \fBWRITE_REG\fP((REG), (((\fBREAD_REG\fP(REG)) & (~(CLEARMASK))) | (SETMASK)))"
.br
.ti -1c
.RI "#define \fBPOSITION_VAL\fP(VAL)   (\fB__CLZ\fP(\fB__RBIT\fP(VAL)))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBFlagStatus\fP \fBITStatus\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFlagStatus\fP { \fBRESET\fP = 0, \fBSET\fP = !RESET }"
.br
.ti -1c
.RI "enum \fBFunctionalState\fP { \fBDISABLE\fP = 0, \fBENABLE\fP = !DISABLE }"
.br
.ti -1c
.RI "enum \fBErrorStatus\fP { \fBSUCCESS\fP = 0U, \fBERROR\fP = !SUCCESS }"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS STM32F1xx Device Peripheral Access Layer Header File\&. 


.PP
\fBAuthor\fP
.RS 4
MCD Application Team 
.PP
.nf
     The file is the unique include file that the application programmer
     is using in the C source code, usually in main.c. This file contains:
       - Configuration section that allows to select:
         - The STM32F1xx device used in the target application
         - To use or not the peripheral’s drivers in application code(i.e. 
           code will be based on direct access to peripheral’s registers 
           rather than drivers API), this option is controlled by 
           "#define USE_HAL_DRIVER"

.fi
.PP
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2017 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
