.TH "Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_def.h" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_def.h \- This file contains HAL common defines, enumeration, macros and structures definitions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx\&.h'\fP
.br
\fC#include 'Legacy/stm32_hal_legacy\&.h'\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAL_MAX_DELAY\fP   0xFFFFFFFFU"
.br
.ti -1c
.RI "#define \fBHAL_IS_BIT_SET\fP(REG,  BIT)   (((REG) & (BIT)) != 0U)"
.br
.ti -1c
.RI "#define \fBHAL_IS_BIT_CLR\fP(REG,  BIT)   (((REG) & (BIT)) == 0U)"
.br
.ti -1c
.RI "#define \fB__HAL_LINKDMA\fP(__HANDLE__,  __PPP_DMA_FIELD__,  __DMA_HANDLE__)"
.br
.ti -1c
.RI "#define \fBUNUSED\fP(X)   (void)X      /* To avoid gcc/g++ warnings */"
.br
.ti -1c
.RI "#define \fB__HAL_RESET_HANDLE_STATE\fP(__HANDLE__)   ((__HANDLE__)\->State = 0U)"
.br
.RI "Reset the Handle's State field\&. "
.ti -1c
.RI "#define \fB__HAL_LOCK\fP(__HANDLE__)"
.br
.ti -1c
.RI "#define \fB__HAL_UNLOCK\fP(__HANDLE__)"
.br
.ti -1c
.RI "#define \fB__ALIGN_END\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHAL_StatusTypeDef\fP { \fBHAL_OK\fP = 0x00U, \fBHAL_ERROR\fP = 0x01U, \fBHAL_BUSY\fP = 0x02U, \fBHAL_TIMEOUT\fP = 0x03U }"
.br
.RI "HAL Status structures definition\&. "
.ti -1c
.RI "enum \fBHAL_LockTypeDef\fP { \fBHAL_UNLOCKED\fP = 0x00U, \fBHAL_LOCKED\fP = 0x01U }"
.br
.RI "HAL Lock structures definition\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains HAL common defines, enumeration, macros and structures definitions\&. 


.PP
\fBAuthor\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2017 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Macro Definition Documentation"
.PP 
.SS "#define __ALIGN_END"

.SS "#define __HAL_LINKDMA(__HANDLE__, __PPP_DMA_FIELD__, __DMA_HANDLE__)"
\fBValue:\fP
.PP
.nf
do{                                                      \
                              (__HANDLE__)->__PPP_DMA_FIELD__ = &(__DMA_HANDLE__); \
                              (__DMA_HANDLE__)\&.Parent = (__HANDLE__);             \
                          } while(0U)
.fi
.SS "#define __HAL_LOCK(__HANDLE__)"
\fBValue:\fP
.PP
.nf
do{                                        \
                                    if((__HANDLE__)->Lock == HAL_LOCKED)   \
                                    {                                      \
                                       return HAL_BUSY;                    \
                                    }                                      \
                                    else                                   \
                                    {                                      \
                                       (__HANDLE__)->Lock = HAL_LOCKED;    \
                                    }                                      \
                                  }while (0U)
.fi
.SS "#define __HAL_RESET_HANDLE_STATE(__HANDLE__)   ((__HANDLE__)\->State = 0U)"

.PP
Reset the Handle's State field\&. 
.PP
\fBParameters\fP
.RS 4
\fI<strong>HANDLE</strong>\fP specifies the Peripheral Handle\&. 
.RE
.PP
\fBNote\fP
.RS 4
This macro can be used for the following purpose:
.IP "\(bu" 2
When the Handle is declared as local variable; before passing it as parameter to HAL_PPP_Init() for the first time, it is mandatory to use this macro to set to 0 the Handle's 'State' field\&. Otherwise, 'State' field may have any random value and the first time the function HAL_PPP_Init() is called, the low level hardware initialization will be missed (i\&.e\&. HAL_PPP_MspInit() will not be executed)\&.
.IP "\(bu" 2
When there is a need to reconfigure the low level hardware: instead of calling HAL_PPP_DeInit() then HAL_PPP_Init(), user can make a call to this macro then HAL_PPP_Init()\&. In this later function, when the Handle's 'State' field is set to 0, it will execute the function HAL_PPP_MspInit() which will reconfigure the low level hardware\&. 
.PP
.RE
.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SS "#define __HAL_UNLOCK(__HANDLE__)"
\fBValue:\fP
.PP
.nf
do{                                       \
                                      (__HANDLE__)->Lock = HAL_UNLOCKED;    \
                                    }while (0U)
.fi
.SS "#define HAL_IS_BIT_CLR(REG, BIT)   (((REG) & (BIT)) == 0U)"

.SS "#define HAL_IS_BIT_SET(REG, BIT)   (((REG) & (BIT)) != 0U)"

.SS "#define HAL_MAX_DELAY   0xFFFFFFFFU"

.SS "#define UNUSED(X)   (void)X      /* To avoid gcc/g++ warnings */"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBHAL_LockTypeDef\fP"

.PP
HAL Lock structures definition\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHAL_UNLOCKED \fP\fP
.TP
\fB\fIHAL_LOCKED \fP\fP
.SS "enum \fBHAL_StatusTypeDef\fP"

.PP
HAL Status structures definition\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHAL_OK \fP\fP
.TP
\fB\fIHAL_ERROR \fP\fP
.TP
\fB\fIHAL_BUSY \fP\fP
.TP
\fB\fIHAL_TIMEOUT \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
