.TH "Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c \- PWR HAL module driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx_hal\&.h'\fP
.br

.SH "Detailed Description"
.PP 
PWR HAL module driver\&. 


.PP
\fBAuthor\fP
.RS 4
MCD Application Team 
.PP
.nf
     This file provides firmware functions to manage the following
     functionalities of the Power Controller (PWR) peripheral:
      + Initialization/de-initialization functions
      + Peripheral Control functions 

.fi
.PP
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2016 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
