.TH "STM32F1xx_System_Private_Variables" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F1xx_System_Private_Variables
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP = 16000000"
.br
.ti -1c
.RI "const uint8_t \fBAHBPrescTable\fP [16U] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}"
.br
.ti -1c
.RI "const uint8_t \fBAPBPrescTable\fP [8U] = {0, 0, 0, 0, 1, 2, 3, 4}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Variable Documentation"
.PP 
.SS "const uint8_t AHBPrescTable[16U] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}"
AHB prescalers table values 
.SS "const uint8_t APBPrescTable[8U] = {0, 0, 0, 0, 1, 2, 3, 4}"
APB prescalers table values 
.SS "uint32_t SystemCoreClock = 16000000"
System Clock Frequency (Core Clock) 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
