.TH "stm32f103x6" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stm32f103x6
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBConfiguration_section_for_CMSIS\fP"
.br
.ti -1c
.RI "\fBPeripheral_interrupt_number_definition\fP"
.br
.ti -1c
.RI "\fBPeripheral_registers_structures\fP"
.br
.ti -1c
.RI "\fBPeripheral_memory_map\fP"
.br
.ti -1c
.RI "\fBPeripheral_declaration\fP"
.br
.ti -1c
.RI "\fBExported_constants\fP"
.br
.ti -1c
.RI "\fBExported_macro\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADC1_IRQn\fP   \fBADC1_2_IRQn\fP"
.br
.ti -1c
.RI "#define \fBTIM1_BRK_TIM9_IRQn\fP   \fBTIM1_BRK_IRQn\fP"
.br
.ti -1c
.RI "#define \fBTIM1_BRK_TIM15_IRQn\fP   \fBTIM1_BRK_IRQn\fP"
.br
.ti -1c
.RI "#define \fBTIM9_IRQn\fP   \fBTIM1_BRK_IRQn\fP"
.br
.ti -1c
.RI "#define \fBTIM11_IRQn\fP   \fBTIM1_TRG_COM_IRQn\fP"
.br
.ti -1c
.RI "#define \fBTIM1_TRG_COM_TIM17_IRQn\fP   \fBTIM1_TRG_COM_IRQn\fP"
.br
.ti -1c
.RI "#define \fBTIM1_TRG_COM_TIM11_IRQn\fP   \fBTIM1_TRG_COM_IRQn\fP"
.br
.ti -1c
.RI "#define \fBTIM1_UP_TIM16_IRQn\fP   \fBTIM1_UP_IRQn\fP"
.br
.ti -1c
.RI "#define \fBTIM1_UP_TIM10_IRQn\fP   \fBTIM1_UP_IRQn\fP"
.br
.ti -1c
.RI "#define \fBTIM10_IRQn\fP   \fBTIM1_UP_IRQn\fP"
.br
.ti -1c
.RI "#define \fBOTG_FS_WKUP_IRQn\fP   \fBUSBWakeUp_IRQn\fP"
.br
.ti -1c
.RI "#define \fBCEC_IRQn\fP   \fBUSBWakeUp_IRQn\fP"
.br
.ti -1c
.RI "#define \fBUSB_HP_IRQn\fP   \fBUSB_HP_CAN1_TX_IRQn\fP"
.br
.ti -1c
.RI "#define \fBCAN1_TX_IRQn\fP   \fBUSB_HP_CAN1_TX_IRQn\fP"
.br
.ti -1c
.RI "#define \fBUSB_LP_IRQn\fP   \fBUSB_LP_CAN1_RX0_IRQn\fP"
.br
.ti -1c
.RI "#define \fBCAN1_RX0_IRQn\fP   \fBUSB_LP_CAN1_RX0_IRQn\fP"
.br
.ti -1c
.RI "#define \fBADC1_IRQHandler\fP   ADC1_2_IRQHandler"
.br
.ti -1c
.RI "#define \fBTIM1_BRK_TIM9_IRQHandler\fP   TIM1_BRK_IRQHandler"
.br
.ti -1c
.RI "#define \fBTIM1_BRK_TIM15_IRQHandler\fP   TIM1_BRK_IRQHandler"
.br
.ti -1c
.RI "#define \fBTIM9_IRQHandler\fP   TIM1_BRK_IRQHandler"
.br
.ti -1c
.RI "#define \fBTIM11_IRQHandler\fP   TIM1_TRG_COM_IRQHandler"
.br
.ti -1c
.RI "#define \fBTIM1_TRG_COM_TIM17_IRQHandler\fP   TIM1_TRG_COM_IRQHandler"
.br
.ti -1c
.RI "#define \fBTIM1_TRG_COM_TIM11_IRQHandler\fP   TIM1_TRG_COM_IRQHandler"
.br
.ti -1c
.RI "#define \fBTIM1_UP_TIM16_IRQHandler\fP   TIM1_UP_IRQHandler"
.br
.ti -1c
.RI "#define \fBTIM1_UP_TIM10_IRQHandler\fP   TIM1_UP_IRQHandler"
.br
.ti -1c
.RI "#define \fBTIM10_IRQHandler\fP   TIM1_UP_IRQHandler"
.br
.ti -1c
.RI "#define \fBOTG_FS_WKUP_IRQHandler\fP   USBWakeUp_IRQHandler"
.br
.ti -1c
.RI "#define \fBCEC_IRQHandler\fP   USBWakeUp_IRQHandler"
.br
.ti -1c
.RI "#define \fBUSB_HP_IRQHandler\fP   USB_HP_CAN1_TX_IRQHandler"
.br
.ti -1c
.RI "#define \fBCAN1_TX_IRQHandler\fP   USB_HP_CAN1_TX_IRQHandler"
.br
.ti -1c
.RI "#define \fBUSB_LP_IRQHandler\fP   USB_LP_CAN1_RX0_IRQHandler"
.br
.ti -1c
.RI "#define \fBCAN1_RX0_IRQHandler\fP   USB_LP_CAN1_RX0_IRQHandler"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC1_IRQHandler   ADC1_2_IRQHandler"

.SS "#define ADC1_IRQn   \fBADC1_2_IRQn\fP"

.SS "#define CAN1_RX0_IRQHandler   USB_LP_CAN1_RX0_IRQHandler"

.SS "#define CAN1_RX0_IRQn   \fBUSB_LP_CAN1_RX0_IRQn\fP"

.SS "#define CAN1_TX_IRQHandler   USB_HP_CAN1_TX_IRQHandler"

.SS "#define CAN1_TX_IRQn   \fBUSB_HP_CAN1_TX_IRQn\fP"

.SS "#define CEC_IRQHandler   USBWakeUp_IRQHandler"

.SS "#define CEC_IRQn   \fBUSBWakeUp_IRQn\fP"

.SS "#define OTG_FS_WKUP_IRQHandler   USBWakeUp_IRQHandler"

.SS "#define OTG_FS_WKUP_IRQn   \fBUSBWakeUp_IRQn\fP"

.SS "#define TIM10_IRQHandler   TIM1_UP_IRQHandler"

.SS "#define TIM10_IRQn   \fBTIM1_UP_IRQn\fP"

.SS "#define TIM11_IRQHandler   TIM1_TRG_COM_IRQHandler"

.SS "#define TIM11_IRQn   \fBTIM1_TRG_COM_IRQn\fP"

.SS "#define TIM1_BRK_TIM15_IRQHandler   TIM1_BRK_IRQHandler"

.SS "#define TIM1_BRK_TIM15_IRQn   \fBTIM1_BRK_IRQn\fP"

.SS "#define TIM1_BRK_TIM9_IRQHandler   TIM1_BRK_IRQHandler"

.SS "#define TIM1_BRK_TIM9_IRQn   \fBTIM1_BRK_IRQn\fP"

.SS "#define TIM1_TRG_COM_TIM11_IRQHandler   TIM1_TRG_COM_IRQHandler"

.SS "#define TIM1_TRG_COM_TIM11_IRQn   \fBTIM1_TRG_COM_IRQn\fP"

.SS "#define TIM1_TRG_COM_TIM17_IRQHandler   TIM1_TRG_COM_IRQHandler"

.SS "#define TIM1_TRG_COM_TIM17_IRQn   \fBTIM1_TRG_COM_IRQn\fP"

.SS "#define TIM1_UP_TIM10_IRQHandler   TIM1_UP_IRQHandler"

.SS "#define TIM1_UP_TIM10_IRQn   \fBTIM1_UP_IRQn\fP"

.SS "#define TIM1_UP_TIM16_IRQHandler   TIM1_UP_IRQHandler"

.SS "#define TIM1_UP_TIM16_IRQn   \fBTIM1_UP_IRQn\fP"

.SS "#define TIM9_IRQHandler   TIM1_BRK_IRQHandler"

.SS "#define TIM9_IRQn   \fBTIM1_BRK_IRQn\fP"

.SS "#define USB_HP_IRQHandler   USB_HP_CAN1_TX_IRQHandler"

.SS "#define USB_HP_IRQn   \fBUSB_HP_CAN1_TX_IRQn\fP"

.SS "#define USB_LP_IRQHandler   USB_LP_CAN1_RX0_IRQHandler"

.SS "#define USB_LP_IRQn   \fBUSB_LP_CAN1_RX0_IRQn\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
