.TH "Core/Src/stm32f1xx_hal_msp.c" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/stm32f1xx_hal_msp.c
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_MspInit\fP (void)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
