.TH "Core/Src/system_stm32f1xx.c" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core/Src/system_stm32f1xx.c \- CMSIS Cortex-M3 Device Peripheral Access Layer System Source File\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSE_VALUE\fP   8000000U"
.br
.ti -1c
.RI "#define \fBHSI_VALUE\fP   8000000U"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSystemInit\fP (void)"
.br
.RI "Setup the microcontroller system Initialize the Embedded Flash Interface, the PLL and update the SystemCoreClock variable\&. "
.ti -1c
.RI "void \fBSystemCoreClockUpdate\fP (void)"
.br
.RI "Update SystemCoreClock variable according to Clock Register Values\&. The SystemCoreClock variable contains the core clock (HCLK), it can be used by the user application to setup the SysTick timer or configure other parameters\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP = 16000000"
.br
.ti -1c
.RI "const uint8_t \fBAHBPrescTable\fP [16U] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}"
.br
.ti -1c
.RI "const uint8_t \fBAPBPrescTable\fP [8U] = {0, 0, 0, 0, 1, 2, 3, 4}"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Cortex-M3 Device Peripheral Access Layer System Source File\&. 


.PP
\fBAuthor\fP
.RS 4
MCD Application Team
.IP "1." 4
This file provides two functions and one global variable to be called from user application:
.IP "  \(bu" 4
\fBSystemInit()\fP: Setups the system clock (System clock source, PLL Multiplier factors, AHB/APBx prescalers and Flash settings)\&. This function is called at startup just after reset and before branch to main program\&. This call is made inside the 'startup_stm32f1xx_xx\&.s' file\&.
.IP "  \(bu" 4
SystemCoreClock variable: Contains the core clock (HCLK), it can be used by the user application to setup the SysTick timer or configure other parameters\&.
.IP "  \(bu" 4
\fBSystemCoreClockUpdate()\fP: Updates the variable SystemCoreClock and must be called whenever the core clock is changed during program execution\&.
.PP

.IP "2." 4
After each device reset the HSI (8 MHz) is used as system clock source\&. Then \fBSystemInit()\fP function is called, in 'startup_stm32f1xx_xx\&.s' file, to configure the system clock before to branch to main program\&.
.IP "4." 4
The default value of HSE crystal is set to 8 MHz (or 25 MHz, depending on the product used), refer to 'HSE_VALUE'\&. When HSE is used as system clock source, directly or through PLL, and you are using different crystal you have to adapt the HSE value to your own configuration\&.
.PP
.RE
.PP
\fBAttention\fP
.RS 4
.RE
.PP
.SS "(C) Copyright (c) 2017 STMicroelectronics\&. All rights reserved\&."
.PP
This software component is licensed by ST under BSD 3-Clause license, the 'License'; You may not use this file except in compliance with the License\&. You may obtain a copy of the License at: opensource\&.org/licenses/BSD-3-Clause 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
