.TH "TIM_Exported_Functions_Group5" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group5 \- TIM One Pulse functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OnePulse_Init\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OnePulseMode)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OnePulse_DeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_OnePulse_MspInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_OnePulse_MspDeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OnePulse_Start\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OnePulse_Stop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OnePulse_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_OnePulse_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t OutputChannel)"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM One Pulse functions\&. 


.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OnePulse_DeInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OnePulse_Init (\fBTIM_HandleTypeDef\fP * htim, uint32_t OnePulseMode)"

.SS "void HAL_TIM_OnePulse_MspDeInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_OnePulse_MspInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OnePulse_Start (\fBTIM_HandleTypeDef\fP * htim, uint32_t OutputChannel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OnePulse_Start_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t OutputChannel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OnePulse_Stop (\fBTIM_HandleTypeDef\fP * htim, uint32_t OutputChannel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_OnePulse_Stop_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t OutputChannel)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
