.TH "TIM_Clock_Source" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Clock_Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ETRMODE2\fP   \fBTIM_SMCR_ETPS_1\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_INTERNAL\fP   \fBTIM_SMCR_ETPS_0\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ITR0\fP   \fBTIM_TS_ITR0\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ITR1\fP   \fBTIM_TS_ITR1\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ITR2\fP   \fBTIM_TS_ITR2\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ITR3\fP   \fBTIM_TS_ITR3\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_TI1ED\fP   \fBTIM_TS_TI1F_ED\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_TI1\fP   \fBTIM_TS_TI1FP1\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_TI2\fP   \fBTIM_TS_TI2FP2\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKSOURCE_ETRMODE1\fP   \fBTIM_TS_ETRF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_CLOCKSOURCE_ETRMODE1   \fBTIM_TS_ETRF\fP"
External clock source mode 1 (ETRF) 
.br
 
.SS "#define TIM_CLOCKSOURCE_ETRMODE2   \fBTIM_SMCR_ETPS_1\fP"
External clock source mode 2 
.br
 
.SS "#define TIM_CLOCKSOURCE_INTERNAL   \fBTIM_SMCR_ETPS_0\fP"
Internal clock source 
.br
 
.SS "#define TIM_CLOCKSOURCE_ITR0   \fBTIM_TS_ITR0\fP"
External clock source mode 1 (ITR0) 
.br
 
.SS "#define TIM_CLOCKSOURCE_ITR1   \fBTIM_TS_ITR1\fP"
External clock source mode 1 (ITR1) 
.br
 
.SS "#define TIM_CLOCKSOURCE_ITR2   \fBTIM_TS_ITR2\fP"
External clock source mode 1 (ITR2) 
.br
 
.SS "#define TIM_CLOCKSOURCE_ITR3   \fBTIM_TS_ITR3\fP"
External clock source mode 1 (ITR3) 
.br
 
.SS "#define TIM_CLOCKSOURCE_TI1   \fBTIM_TS_TI1FP1\fP"
External clock source mode 1 (TTI1FP1) 
.br
 
.SS "#define TIM_CLOCKSOURCE_TI1ED   \fBTIM_TS_TI1F_ED\fP"
External clock source mode 1 (TTI1FP1 + edge detect\&.) 
.SS "#define TIM_CLOCKSOURCE_TI2   \fBTIM_TS_TI2FP2\fP"
External clock source mode 1 (TTI2FP2) 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
