.TH "TIM_ClearInput_Prescaler" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_ClearInput_Prescaler
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLEARINPUTPRESCALER_DIV1\fP   \fBTIM_ETRPRESCALER_DIV1\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLEARINPUTPRESCALER_DIV2\fP   \fBTIM_ETRPRESCALER_DIV2\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLEARINPUTPRESCALER_DIV4\fP   \fBTIM_ETRPRESCALER_DIV4\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLEARINPUTPRESCALER_DIV8\fP   \fBTIM_ETRPRESCALER_DIV8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_CLEARINPUTPRESCALER_DIV1   \fBTIM_ETRPRESCALER_DIV1\fP"
No prescaler is used 
.br
 
.SS "#define TIM_CLEARINPUTPRESCALER_DIV2   \fBTIM_ETRPRESCALER_DIV2\fP"
Prescaler for External ETR pin: Capture performed once every 2 events\&. 
.SS "#define TIM_CLEARINPUTPRESCALER_DIV4   \fBTIM_ETRPRESCALER_DIV4\fP"
Prescaler for External ETR pin: Capture performed once every 4 events\&. 
.SS "#define TIM_CLEARINPUTPRESCALER_DIV8   \fBTIM_ETRPRESCALER_DIV8\fP"
Prescaler for External ETR pin: Capture performed once every 8 events\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
