.TH "TIM_Input_Capture_Polarity" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Input_Capture_Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_ICPOLARITY_RISING\fP   \fBTIM_INPUTCHANNELPOLARITY_RISING\fP"
.br
.ti -1c
.RI "#define \fBTIM_ICPOLARITY_FALLING\fP   \fBTIM_INPUTCHANNELPOLARITY_FALLING\fP"
.br
.ti -1c
.RI "#define \fBTIM_ICPOLARITY_BOTHEDGE\fP   \fBTIM_INPUTCHANNELPOLARITY_BOTHEDGE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_ICPOLARITY_BOTHEDGE   \fBTIM_INPUTCHANNELPOLARITY_BOTHEDGE\fP"
Capture triggered by both rising and falling edges on timer input 
.SS "#define TIM_ICPOLARITY_FALLING   \fBTIM_INPUTCHANNELPOLARITY_FALLING\fP"
Capture triggered by falling edge on timer input 
.br
 
.SS "#define TIM_ICPOLARITY_RISING   \fBTIM_INPUTCHANNELPOLARITY_RISING\fP"
Capture triggered by rising edge on timer input 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
