.TH "TIM_Master_Mode_Selection" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Master_Mode_Selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_TRGO_RESET\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_ENABLE\fP   \fBTIM_CR2_MMS_0\fP"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_UPDATE\fP   \fBTIM_CR2_MMS_1\fP"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC1\fP   (\fBTIM_CR2_MMS_1\fP | \fBTIM_CR2_MMS_0\fP)"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC1REF\fP   \fBTIM_CR2_MMS_2\fP"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC2REF\fP   (\fBTIM_CR2_MMS_2\fP | \fBTIM_CR2_MMS_0\fP)"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC3REF\fP   (\fBTIM_CR2_MMS_2\fP | \fBTIM_CR2_MMS_1\fP)"
.br
.ti -1c
.RI "#define \fBTIM_TRGO_OC4REF\fP   (\fBTIM_CR2_MMS_2\fP | \fBTIM_CR2_MMS_1\fP | \fBTIM_CR2_MMS_0\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_TRGO_ENABLE   \fBTIM_CR2_MMS_0\fP"
TIMx_CR1\&.CEN bit is used as trigger output (TRGO) 
.br
 
.SS "#define TIM_TRGO_OC1   (\fBTIM_CR2_MMS_1\fP | \fBTIM_CR2_MMS_0\fP)"
Capture or a compare match 1 is used as trigger output (TRGO) 
.SS "#define TIM_TRGO_OC1REF   \fBTIM_CR2_MMS_2\fP"
OC1REF signal is used as trigger output (TRGO) 
.br
 
.SS "#define TIM_TRGO_OC2REF   (\fBTIM_CR2_MMS_2\fP | \fBTIM_CR2_MMS_0\fP)"
OC2REF signal is used as trigger output(TRGO) 
.br
 
.SS "#define TIM_TRGO_OC3REF   (\fBTIM_CR2_MMS_2\fP | \fBTIM_CR2_MMS_1\fP)"
OC3REF signal is used as trigger output(TRGO) 
.br
 
.SS "#define TIM_TRGO_OC4REF   (\fBTIM_CR2_MMS_2\fP | \fBTIM_CR2_MMS_1\fP | \fBTIM_CR2_MMS_0\fP)"
OC4REF signal is used as trigger output(TRGO) 
.br
 
.SS "#define TIM_TRGO_RESET   0x00000000U"
TIMx_EGR\&.UG bit is used as trigger output (TRGO) 
.br
 
.SS "#define TIM_TRGO_UPDATE   \fBTIM_CR2_MMS_1\fP"
Update event is used as trigger output (TRGO) 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
