.TH "TIM_OnePulse_InitTypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_OnePulse_InitTypeDef \- TIM One Pulse Mode Configuration Structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f1xx_hal_tim\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBOCMode\fP"
.br
.ti -1c
.RI "uint32_t \fBPulse\fP"
.br
.ti -1c
.RI "uint32_t \fBOCPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBOCNPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBOCIdleState\fP"
.br
.ti -1c
.RI "uint32_t \fBOCNIdleState\fP"
.br
.ti -1c
.RI "uint32_t \fBICPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBICSelection\fP"
.br
.ti -1c
.RI "uint32_t \fBICFilter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM One Pulse Mode Configuration Structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t TIM_OnePulse_InitTypeDef::ICFilter"
Specifies the input capture filter\&. This parameter can be a number between Min_Data = 0x0 and Max_Data = 0xF 
.SS "uint32_t TIM_OnePulse_InitTypeDef::ICPolarity"
Specifies the active edge of the input signal\&. This parameter can be a value of \fBTIM Input Capture Polarity\fP 
.SS "uint32_t TIM_OnePulse_InitTypeDef::ICSelection"
Specifies the input\&. This parameter can be a value of \fBTIM Input Capture Selection\fP 
.SS "uint32_t TIM_OnePulse_InitTypeDef::OCIdleState"
Specifies the TIM Output Compare pin state during Idle state\&. This parameter can be a value of \fBTIM Output Compare Idle State\fP 
.PP
\fBNote\fP
.RS 4
This parameter is valid only for timer instances supporting break feature\&. 
.RE
.PP

.SS "uint32_t TIM_OnePulse_InitTypeDef::OCMode"
Specifies the TIM mode\&. This parameter can be a value of \fBTIM Output Compare and PWM Modes\fP 
.SS "uint32_t TIM_OnePulse_InitTypeDef::OCNIdleState"
Specifies the TIM Output Compare pin state during Idle state\&. This parameter can be a value of \fBTIM Complementary Output Compare Idle State\fP 
.PP
\fBNote\fP
.RS 4
This parameter is valid only for timer instances supporting break feature\&. 
.RE
.PP

.SS "uint32_t TIM_OnePulse_InitTypeDef::OCNPolarity"
Specifies the complementary output polarity\&. This parameter can be a value of \fBTIM Complementary Output Compare Polarity\fP 
.PP
\fBNote\fP
.RS 4
This parameter is valid only for timer instances supporting break feature\&. 
.RE
.PP

.SS "uint32_t TIM_OnePulse_InitTypeDef::OCPolarity"
Specifies the output polarity\&. This parameter can be a value of \fBTIM Output Compare Polarity\fP 
.SS "uint32_t TIM_OnePulse_InitTypeDef::Pulse"
Specifies the pulse value to be loaded into the Capture Compare Register\&. This parameter can be a number between Min_Data = 0x0000 and Max_Data = 0xFFFF 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
