.TH "TIM_Flag_definition" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Flag_definition
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_FLAG_UPDATE\fP   \fBTIM_SR_UIF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC1\fP   \fBTIM_SR_CC1IF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC2\fP   \fBTIM_SR_CC2IF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC3\fP   \fBTIM_SR_CC3IF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC4\fP   \fBTIM_SR_CC4IF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_COM\fP   \fBTIM_SR_COMIF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_TRIGGER\fP   \fBTIM_SR_TIF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_BREAK\fP   \fBTIM_SR_BIF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC1OF\fP   \fBTIM_SR_CC1OF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC2OF\fP   \fBTIM_SR_CC2OF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC3OF\fP   \fBTIM_SR_CC3OF\fP"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC4OF\fP   \fBTIM_SR_CC4OF\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_FLAG_BREAK   \fBTIM_SR_BIF\fP"
Break interrupt flag 
.br
 
.SS "#define TIM_FLAG_CC1   \fBTIM_SR_CC1IF\fP"
Capture/Compare 1 interrupt flag 
.SS "#define TIM_FLAG_CC1OF   \fBTIM_SR_CC1OF\fP"
Capture 1 overcapture flag 
.br
 
.SS "#define TIM_FLAG_CC2   \fBTIM_SR_CC2IF\fP"
Capture/Compare 2 interrupt flag 
.SS "#define TIM_FLAG_CC2OF   \fBTIM_SR_CC2OF\fP"
Capture 2 overcapture flag 
.br
 
.SS "#define TIM_FLAG_CC3   \fBTIM_SR_CC3IF\fP"
Capture/Compare 3 interrupt flag 
.SS "#define TIM_FLAG_CC3OF   \fBTIM_SR_CC3OF\fP"
Capture 3 overcapture flag 
.br
 
.SS "#define TIM_FLAG_CC4   \fBTIM_SR_CC4IF\fP"
Capture/Compare 4 interrupt flag 
.SS "#define TIM_FLAG_CC4OF   \fBTIM_SR_CC4OF\fP"
Capture 4 overcapture flag 
.br
 
.SS "#define TIM_FLAG_COM   \fBTIM_SR_COMIF\fP"
Commutation interrupt flag 
.br
 
.SS "#define TIM_FLAG_TRIGGER   \fBTIM_SR_TIF\fP"
Trigger interrupt flag 
.br
 
.SS "#define TIM_FLAG_UPDATE   \fBTIM_SR_UIF\fP"
Update interrupt flag 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
