.TH "TIM_ETR_Polarity" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_ETR_Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_ETRPOLARITY_INVERTED\fP   \fBTIM_SMCR_ETP\fP"
.br
.ti -1c
.RI "#define \fBTIM_ETRPOLARITY_NONINVERTED\fP   0x00000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_ETRPOLARITY_INVERTED   \fBTIM_SMCR_ETP\fP"
Polarity for ETR source 
.SS "#define TIM_ETRPOLARITY_NONINVERTED   0x00000000U"
Polarity for ETR source 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
