.TH "TIM_Master_Slave_Mode" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Master_Slave_Mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_MASTERSLAVEMODE_ENABLE\fP   \fBTIM_SMCR_MSM\fP"
.br
.ti -1c
.RI "#define \fBTIM_MASTERSLAVEMODE_DISABLE\fP   0x00000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_MASTERSLAVEMODE_DISABLE   0x00000000U"
Master/slave mode is selected 
.SS "#define TIM_MASTERSLAVEMODE_ENABLE   \fBTIM_SMCR_MSM\fP"
No action 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
