.TH "TIM_Channel" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Channel
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CHANNEL_1\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_CHANNEL_2\fP   0x00000004U"
.br
.ti -1c
.RI "#define \fBTIM_CHANNEL_3\fP   0x00000008U"
.br
.ti -1c
.RI "#define \fBTIM_CHANNEL_4\fP   0x0000000CU"
.br
.ti -1c
.RI "#define \fBTIM_CHANNEL_ALL\fP   0x0000003CU"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_CHANNEL_1   0x00000000U"
Capture/compare channel 1 identifier 
.br
 
.SS "#define TIM_CHANNEL_2   0x00000004U"
Capture/compare channel 2 identifier 
.br
 
.SS "#define TIM_CHANNEL_3   0x00000008U"
Capture/compare channel 3 identifier 
.br
 
.SS "#define TIM_CHANNEL_4   0x0000000CU"
Capture/compare channel 4 identifier 
.br
 
.SS "#define TIM_CHANNEL_ALL   0x0000003CU"
Global Capture/compare channel identifier 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
