.TH "TIM_HallSensor_InitTypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_HallSensor_InitTypeDef \- TIM Hall sensor Configuration Structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f1xx_hal_tim_ex\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBIC1Polarity\fP"
.br
.ti -1c
.RI "uint32_t \fBIC1Prescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBIC1Filter\fP"
.br
.ti -1c
.RI "uint32_t \fBCommutation_Delay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM Hall sensor Configuration Structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t TIM_HallSensor_InitTypeDef::Commutation_Delay"
Specifies the pulse value to be loaded into the Capture Compare Register\&. This parameter can be a number between Min_Data = 0x0000 and Max_Data = 0xFFFF 
.SS "uint32_t TIM_HallSensor_InitTypeDef::IC1Filter"
Specifies the input capture filter\&. This parameter can be a number between Min_Data = 0x0 and Max_Data = 0xF 
.SS "uint32_t TIM_HallSensor_InitTypeDef::IC1Polarity"
Specifies the active edge of the input signal\&. This parameter can be a value of \fBTIM Input Capture Polarity\fP 
.SS "uint32_t TIM_HallSensor_InitTypeDef::IC1Prescaler"
Specifies the Input Capture Prescaler\&. This parameter can be a value of \fBTIM Input Capture Prescaler\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
