.TH "TIM_Counter_Mode" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Counter_Mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_COUNTERMODE_UP\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_COUNTERMODE_DOWN\fP   \fBTIM_CR1_DIR\fP"
.br
.ti -1c
.RI "#define \fBTIM_COUNTERMODE_CENTERALIGNED1\fP   \fBTIM_CR1_CMS_0\fP"
.br
.ti -1c
.RI "#define \fBTIM_COUNTERMODE_CENTERALIGNED2\fP   \fBTIM_CR1_CMS_1\fP"
.br
.ti -1c
.RI "#define \fBTIM_COUNTERMODE_CENTERALIGNED3\fP   \fBTIM_CR1_CMS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_COUNTERMODE_CENTERALIGNED1   \fBTIM_CR1_CMS_0\fP"
Center-aligned mode 1 
.br
 
.SS "#define TIM_COUNTERMODE_CENTERALIGNED2   \fBTIM_CR1_CMS_1\fP"
Center-aligned mode 2 
.br
 
.SS "#define TIM_COUNTERMODE_CENTERALIGNED3   \fBTIM_CR1_CMS\fP"
Center-aligned mode 3 
.br
 
.SS "#define TIM_COUNTERMODE_DOWN   \fBTIM_CR1_DIR\fP"
Counter used as down-counter 
.SS "#define TIM_COUNTERMODE_UP   0x00000000U"
Counter used as up-counter 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
