.TH "TIM_Break_Input_enable_disable" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Break_Input_enable_disable
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_BREAK_ENABLE\fP   \fBTIM_BDTR_BKE\fP"
.br
.ti -1c
.RI "#define \fBTIM_BREAK_DISABLE\fP   0x00000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_BREAK_DISABLE   0x00000000U"
Break input BRK is disabled 
.SS "#define TIM_BREAK_ENABLE   \fBTIM_BDTR_BKE\fP"
Break input BRK is enabled 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
