.TH "TIM_Encoder_InitTypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Encoder_InitTypeDef \- TIM Encoder Configuration Structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f1xx_hal_tim\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBEncoderMode\fP"
.br
.ti -1c
.RI "uint32_t \fBIC1Polarity\fP"
.br
.ti -1c
.RI "uint32_t \fBIC1Selection\fP"
.br
.ti -1c
.RI "uint32_t \fBIC1Prescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBIC1Filter\fP"
.br
.ti -1c
.RI "uint32_t \fBIC2Polarity\fP"
.br
.ti -1c
.RI "uint32_t \fBIC2Selection\fP"
.br
.ti -1c
.RI "uint32_t \fBIC2Prescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBIC2Filter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM Encoder Configuration Structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t TIM_Encoder_InitTypeDef::EncoderMode"
Specifies the active edge of the input signal\&. This parameter can be a value of \fBTIM Encoder Mode\fP 
.SS "uint32_t TIM_Encoder_InitTypeDef::IC1Filter"
Specifies the input capture filter\&. This parameter can be a number between Min_Data = 0x0 and Max_Data = 0xF 
.SS "uint32_t TIM_Encoder_InitTypeDef::IC1Polarity"
Specifies the active edge of the input signal\&. This parameter can be a value of \fBTIM Encoder Input Polarity\fP 
.SS "uint32_t TIM_Encoder_InitTypeDef::IC1Prescaler"
Specifies the Input Capture Prescaler\&. This parameter can be a value of \fBTIM Input Capture Prescaler\fP 
.SS "uint32_t TIM_Encoder_InitTypeDef::IC1Selection"
Specifies the input\&. This parameter can be a value of \fBTIM Input Capture Selection\fP 
.SS "uint32_t TIM_Encoder_InitTypeDef::IC2Filter"
Specifies the input capture filter\&. This parameter can be a number between Min_Data = 0x0 and Max_Data = 0xF 
.SS "uint32_t TIM_Encoder_InitTypeDef::IC2Polarity"
Specifies the active edge of the input signal\&. This parameter can be a value of \fBTIM Encoder Input Polarity\fP 
.SS "uint32_t TIM_Encoder_InitTypeDef::IC2Prescaler"
Specifies the Input Capture Prescaler\&. This parameter can be a value of \fBTIM Input Capture Prescaler\fP 
.SS "uint32_t TIM_Encoder_InitTypeDef::IC2Selection"
Specifies the input\&. This parameter can be a value of \fBTIM Input Capture Selection\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
