.TH "TIM_Output_Compare_Polarity" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Output_Compare_Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OCPOLARITY_HIGH\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_OCPOLARITY_LOW\fP   \fBTIM_CCER_CC1P\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_OCPOLARITY_HIGH   0x00000000U"
Capture/Compare output polarity 
.br
 
.SS "#define TIM_OCPOLARITY_LOW   \fBTIM_CCER_CC1P\fP"
Capture/Compare output polarity 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
