.TH "TIM_ClearInputConfigTypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_ClearInputConfigTypeDef \- TIM Clear Input Configuration Handle Structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f1xx_hal_tim\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBClearInputState\fP"
.br
.ti -1c
.RI "uint32_t \fBClearInputSource\fP"
.br
.ti -1c
.RI "uint32_t \fBClearInputPolarity\fP"
.br
.ti -1c
.RI "uint32_t \fBClearInputPrescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBClearInputFilter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM Clear Input Configuration Handle Structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t TIM_ClearInputConfigTypeDef::ClearInputFilter"
TIM Clear Input filter This parameter can be a number between Min_Data = 0x0 and Max_Data = 0xF 
.SS "uint32_t TIM_ClearInputConfigTypeDef::ClearInputPolarity"
TIM Clear Input polarity This parameter can be a value of \fBTIM Clear Input Polarity\fP 
.SS "uint32_t TIM_ClearInputConfigTypeDef::ClearInputPrescaler"
TIM Clear Input prescaler This parameter must be 0: When OCRef clear feature is used with ETR source, ETR prescaler must be off 
.SS "uint32_t TIM_ClearInputConfigTypeDef::ClearInputSource"
TIM clear Input sources This parameter can be a value of \fBTIM Clear Input Source\fP 
.SS "uint32_t TIM_ClearInputConfigTypeDef::ClearInputState"
TIM clear Input state This parameter can be ENABLE or DISABLE 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
