.TH "TIM_Interrupt_definition" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Interrupt_definition
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_IT_UPDATE\fP   \fBTIM_DIER_UIE\fP"
.br
.ti -1c
.RI "#define \fBTIM_IT_CC1\fP   \fBTIM_DIER_CC1IE\fP"
.br
.ti -1c
.RI "#define \fBTIM_IT_CC2\fP   \fBTIM_DIER_CC2IE\fP"
.br
.ti -1c
.RI "#define \fBTIM_IT_CC3\fP   \fBTIM_DIER_CC3IE\fP"
.br
.ti -1c
.RI "#define \fBTIM_IT_CC4\fP   \fBTIM_DIER_CC4IE\fP"
.br
.ti -1c
.RI "#define \fBTIM_IT_COM\fP   \fBTIM_DIER_COMIE\fP"
.br
.ti -1c
.RI "#define \fBTIM_IT_TRIGGER\fP   \fBTIM_DIER_TIE\fP"
.br
.ti -1c
.RI "#define \fBTIM_IT_BREAK\fP   \fBTIM_DIER_BIE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_IT_BREAK   \fBTIM_DIER_BIE\fP"
Break interrupt 
.br
 
.SS "#define TIM_IT_CC1   \fBTIM_DIER_CC1IE\fP"
Capture/Compare 1 interrupt 
.SS "#define TIM_IT_CC2   \fBTIM_DIER_CC2IE\fP"
Capture/Compare 2 interrupt 
.SS "#define TIM_IT_CC3   \fBTIM_DIER_CC3IE\fP"
Capture/Compare 3 interrupt 
.SS "#define TIM_IT_CC4   \fBTIM_DIER_CC4IE\fP"
Capture/Compare 4 interrupt 
.SS "#define TIM_IT_COM   \fBTIM_DIER_COMIE\fP"
Commutation interrupt 
.br
 
.SS "#define TIM_IT_TRIGGER   \fBTIM_DIER_TIE\fP"
Trigger interrupt 
.br
 
.SS "#define TIM_IT_UPDATE   \fBTIM_DIER_UIE\fP"
Update interrupt 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
