.TH "TIM_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_TypeDef \- TIM Timers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSMCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDIER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEGR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCMR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCMR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCNT\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPSC\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBARR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBDTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDMAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM Timers\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::ARR"
TIM auto-reload register, Address offset: 0x2C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::BDTR"
TIM break and dead-time register, Address offset: 0x44 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCER"
TIM capture/compare enable register, Address offset: 0x20 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCMR1"
TIM capture/compare mode register 1, Address offset: 0x18 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCMR2"
TIM capture/compare mode register 2, Address offset: 0x1C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR1"
TIM capture/compare register 1, Address offset: 0x34 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR2"
TIM capture/compare register 2, Address offset: 0x38 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR3"
TIM capture/compare register 3, Address offset: 0x3C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CCR4"
TIM capture/compare register 4, Address offset: 0x40 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CNT"
TIM counter register, Address offset: 0x24 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CR1"
TIM control register 1, Address offset: 0x00 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::CR2"
TIM control register 2, Address offset: 0x04 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::DCR"
TIM DMA control register, Address offset: 0x48 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::DIER"
TIM DMA/interrupt enable register, Address offset: 0x0C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::DMAR"
TIM DMA address for full transfer register, Address offset: 0x4C 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::EGR"
TIM event generation register, Address offset: 0x14 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::OR"
TIM option register, Address offset: 0x50 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::PSC"
TIM prescaler register, Address offset: 0x28 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::RCR"
TIM repetition counter register, Address offset: 0x30 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::SMCR"
TIM slave Mode Control register, Address offset: 0x08 
.SS "\fB__IO\fP uint32_t TIM_TypeDef::SR"
TIM status register, Address offset: 0x10 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
