.TH "TIM_Input_Capture_Selection" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Input_Capture_Selection
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_ICSELECTION_DIRECTTI\fP   \fBTIM_CCMR1_CC1S_0\fP"
.br
.ti -1c
.RI "#define \fBTIM_ICSELECTION_INDIRECTTI\fP   \fBTIM_CCMR1_CC1S_1\fP"
.br
.ti -1c
.RI "#define \fBTIM_ICSELECTION_TRC\fP   \fBTIM_CCMR1_CC1S\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_ICSELECTION_DIRECTTI   \fBTIM_CCMR1_CC1S_0\fP"
TIM Input 1, 2, 3 or 4 is selected to be connected to IC1, IC2, IC3 or IC4, respectively 
.SS "#define TIM_ICSELECTION_INDIRECTTI   \fBTIM_CCMR1_CC1S_1\fP"
TIM Input 1, 2, 3 or 4 is selected to be connected to IC2, IC1, IC4 or IC3, respectively 
.SS "#define TIM_ICSELECTION_TRC   \fBTIM_CCMR1_CC1S\fP"
TIM Input 1, 2, 3 or 4 is selected to be connected to TRC 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
