.TH "TIM_Exported_Functions_Group9" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group9 \- TIM Callbacks functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHAL_TIM_PeriodElapsedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PeriodElapsedHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_OC_DelayElapsedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_IC_CaptureCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_IC_CaptureHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PWM_PulseFinishedCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PWM_PulseFinishedHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_TriggerCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_TriggerHalfCpltCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_ErrorCallback\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM Callbacks functions\&. 


.SH "Function Documentation"
.PP 
.SS "void HAL_TIM_ErrorCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_IC_CaptureCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_IC_CaptureHalfCpltCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_OC_DelayElapsedCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_PeriodElapsedCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_PeriodElapsedHalfCpltCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_PWM_PulseFinishedCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_PWM_PulseFinishedHalfCpltCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_TriggerCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_TriggerHalfCpltCallback (\fBTIM_HandleTypeDef\fP * htim)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
