.TH "TIM_ClearInput_Source" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_ClearInput_Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLEARINPUTSOURCE_NONE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_CLEARINPUTSOURCE_ETR\fP   0x00000001U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_CLEARINPUTSOURCE_ETR   0x00000001U"
OCREF_CLR is connected to ETRF input 
.SS "#define TIM_CLEARINPUTSOURCE_NONE   0x00000000U"
OCREF_CLR is disabled 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
