.TH "TIM_Output_Compare_N_Polarity" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Output_Compare_N_Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OCNPOLARITY_HIGH\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_OCNPOLARITY_LOW\fP   \fBTIM_CCER_CC1NP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_OCNPOLARITY_HIGH   0x00000000U"
Capture/Compare complementary output polarity 
.SS "#define TIM_OCNPOLARITY_LOW   \fBTIM_CCER_CC1NP\fP"
Capture/Compare complementary output polarity 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
