.TH "TIM_MasterConfigTypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_MasterConfigTypeDef \- TIM Master configuration Structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f1xx_hal_tim\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBMasterOutputTrigger\fP"
.br
.ti -1c
.RI "uint32_t \fBMasterSlaveMode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM Master configuration Structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "uint32_t TIM_MasterConfigTypeDef::MasterOutputTrigger"
Trigger output (TRGO) selection This parameter can be a value of \fBTIM Master Mode Selection\fP 
.SS "uint32_t TIM_MasterConfigTypeDef::MasterSlaveMode"
Master/slave mode selection This parameter can be a value of \fBTIM Master/Slave Mode\fP 
.PP
\fBNote\fP
.RS 4
When the Master/slave mode is enabled, the effect of an event on the trigger input (TRGI) is delayed to allow a perfect synchronization between the current timer and its slaves (through TRGO)\&. It is not mandatory in case of timer synchronization mode\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
