.TH "TIM_OSSR_Off_State_Selection_for_Run_mode_state" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_OSSR_Off_State_Selection_for_Run_mode_state
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OSSR_ENABLE\fP   \fBTIM_BDTR_OSSR\fP"
.br
.ti -1c
.RI "#define \fBTIM_OSSR_DISABLE\fP   0x00000000U"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_OSSR_DISABLE   0x00000000U"
When inactive, OC/OCN outputs are disabled (not controlled any longer by the timer) 
.SS "#define TIM_OSSR_ENABLE   \fBTIM_BDTR_OSSR\fP"
When inactive, OC/OCN outputs are enabled (still controlled by the timer) 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
