.TH "TIM_Clock_Polarity" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Clock_Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_INVERTED\fP   \fBTIM_ETRPOLARITY_INVERTED\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_NONINVERTED\fP   \fBTIM_ETRPOLARITY_NONINVERTED\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_RISING\fP   \fBTIM_INPUTCHANNELPOLARITY_RISING\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_FALLING\fP   \fBTIM_INPUTCHANNELPOLARITY_FALLING\fP"
.br
.ti -1c
.RI "#define \fBTIM_CLOCKPOLARITY_BOTHEDGE\fP   \fBTIM_INPUTCHANNELPOLARITY_BOTHEDGE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_CLOCKPOLARITY_BOTHEDGE   \fBTIM_INPUTCHANNELPOLARITY_BOTHEDGE\fP"
Polarity for TIx clock sources 
.SS "#define TIM_CLOCKPOLARITY_FALLING   \fBTIM_INPUTCHANNELPOLARITY_FALLING\fP"
Polarity for TIx clock sources 
.SS "#define TIM_CLOCKPOLARITY_INVERTED   \fBTIM_ETRPOLARITY_INVERTED\fP"
Polarity for ETRx clock sources 
.SS "#define TIM_CLOCKPOLARITY_NONINVERTED   \fBTIM_ETRPOLARITY_NONINVERTED\fP"
Polarity for ETRx clock sources 
.SS "#define TIM_CLOCKPOLARITY_RISING   \fBTIM_INPUTCHANNELPOLARITY_RISING\fP"
Polarity for TIx clock sources 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
