.TH "TIM_Event_Source" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Event_Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_UPDATE\fP   \fBTIM_EGR_UG\fP"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_CC1\fP   \fBTIM_EGR_CC1G\fP"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_CC2\fP   \fBTIM_EGR_CC2G\fP"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_CC3\fP   \fBTIM_EGR_CC3G\fP"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_CC4\fP   \fBTIM_EGR_CC4G\fP"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_COM\fP   \fBTIM_EGR_COMG\fP"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_TRIGGER\fP   \fBTIM_EGR_TG\fP"
.br
.ti -1c
.RI "#define \fBTIM_EVENTSOURCE_BREAK\fP   \fBTIM_EGR_BG\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_EVENTSOURCE_BREAK   \fBTIM_EGR_BG\fP"
A break event is generated 
.SS "#define TIM_EVENTSOURCE_CC1   \fBTIM_EGR_CC1G\fP"
A capture/compare event is generated on channel 1 
.SS "#define TIM_EVENTSOURCE_CC2   \fBTIM_EGR_CC2G\fP"
A capture/compare event is generated on channel 2 
.SS "#define TIM_EVENTSOURCE_CC3   \fBTIM_EGR_CC3G\fP"
A capture/compare event is generated on channel 3 
.SS "#define TIM_EVENTSOURCE_CC4   \fBTIM_EGR_CC4G\fP"
A capture/compare event is generated on channel 4 
.SS "#define TIM_EVENTSOURCE_COM   \fBTIM_EGR_COMG\fP"
A commutation event is generated 
.SS "#define TIM_EVENTSOURCE_TRIGGER   \fBTIM_EGR_TG\fP"
A trigger event is generated 
.SS "#define TIM_EVENTSOURCE_UPDATE   \fBTIM_EGR_UG\fP"
Reinitialize the counter and generates an update of the registers 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
