.TH "TIM_Private_Functions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTIM_Base_SetConfig\fP (\fBTIM_TypeDef\fP *TIMx, \fBTIM_Base_InitTypeDef\fP *Structure)"
.br
.ti -1c
.RI "void \fBTIM_TI1_SetConfig\fP (\fBTIM_TypeDef\fP *TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter)"
.br
.ti -1c
.RI "void \fBTIM_OC2_SetConfig\fP (\fBTIM_TypeDef\fP *TIMx, \fBTIM_OC_InitTypeDef\fP *OC_Config)"
.br
.ti -1c
.RI "void \fBTIM_ETR_SetConfig\fP (\fBTIM_TypeDef\fP *TIMx, uint32_t TIM_ExtTRGPrescaler, uint32_t TIM_ExtTRGPolarity, uint32_t ExtTRGFilter)"
.br
.ti -1c
.RI "void \fBTIM_DMADelayPulseHalfCplt\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "void \fBTIM_DMAError\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "void \fBTIM_DMACaptureCplt\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "void \fBTIM_DMACaptureHalfCplt\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "void \fBTIM_CCxChannelCmd\fP (\fBTIM_TypeDef\fP *TIMx, uint32_t Channel, uint32_t ChannelState)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void TIM_Base_SetConfig (\fBTIM_TypeDef\fP * TIMx, \fBTIM_Base_InitTypeDef\fP * Structure)"

.SS "void TIM_CCxChannelCmd (\fBTIM_TypeDef\fP * TIMx, uint32_t Channel, uint32_t ChannelState)"

.SS "void TIM_DMACaptureCplt (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "void TIM_DMACaptureHalfCplt (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "void TIM_DMADelayPulseHalfCplt (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "void TIM_DMAError (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "void TIM_ETR_SetConfig (\fBTIM_TypeDef\fP * TIMx, uint32_t TIM_ExtTRGPrescaler, uint32_t TIM_ExtTRGPolarity, uint32_t ExtTRGFilter)"

.SS "void TIM_OC2_SetConfig (\fBTIM_TypeDef\fP * TIMx, \fBTIM_OC_InitTypeDef\fP * OC_Config)"

.SS "void TIM_TI1_SetConfig (\fBTIM_TypeDef\fP * TIMx, uint32_t TIM_ICPolarity, uint32_t TIM_ICSelection, uint32_t TIM_ICFilter)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
