.TH "TIM_Slave_Mode" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Slave_Mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_SLAVEMODE_DISABLE\fP   0x00000000U"
.br
.ti -1c
.RI "#define \fBTIM_SLAVEMODE_RESET\fP   \fBTIM_SMCR_SMS_2\fP"
.br
.ti -1c
.RI "#define \fBTIM_SLAVEMODE_GATED\fP   (\fBTIM_SMCR_SMS_2\fP | \fBTIM_SMCR_SMS_0\fP)"
.br
.ti -1c
.RI "#define \fBTIM_SLAVEMODE_TRIGGER\fP   (\fBTIM_SMCR_SMS_2\fP | \fBTIM_SMCR_SMS_1\fP)"
.br
.ti -1c
.RI "#define \fBTIM_SLAVEMODE_EXTERNAL1\fP   (\fBTIM_SMCR_SMS_2\fP | \fBTIM_SMCR_SMS_1\fP | \fBTIM_SMCR_SMS_0\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_SLAVEMODE_DISABLE   0x00000000U"
Slave mode disabled 
.br
 
.SS "#define TIM_SLAVEMODE_EXTERNAL1   (\fBTIM_SMCR_SMS_2\fP | \fBTIM_SMCR_SMS_1\fP | \fBTIM_SMCR_SMS_0\fP)"
External Clock Mode 1 
.br
 
.SS "#define TIM_SLAVEMODE_GATED   (\fBTIM_SMCR_SMS_2\fP | \fBTIM_SMCR_SMS_0\fP)"
Gated Mode 
.br
 
.SS "#define TIM_SLAVEMODE_RESET   \fBTIM_SMCR_SMS_2\fP"
Reset Mode 
.br
 
.SS "#define TIM_SLAVEMODE_TRIGGER   (\fBTIM_SMCR_SMS_2\fP | \fBTIM_SMCR_SMS_1\fP)"
Trigger Mode 
.br
 
.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
