.TH "TIM_Exported_Functions_Group10" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group10 \- Peripheral State functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_Base_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_OC_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_PWM_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_IC_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_OnePulse_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_StateTypeDef\fP \fBHAL_TIM_Encoder_GetState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_ActiveChannel\fP \fBHAL_TIM_GetActiveChannel\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_TIM_ChannelStateTypeDef\fP \fBHAL_TIM_GetChannelState\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_TIM_DMABurstStateTypeDef\fP \fBHAL_TIM_DMABurstState\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Peripheral State functions\&. 


.SH "Function Documentation"
.PP 
.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_Base_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_DMABurstStateTypeDef\fP HAL_TIM_DMABurstState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_Encoder_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_ActiveChannel\fP HAL_TIM_GetActiveChannel (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_ChannelStateTypeDef\fP HAL_TIM_GetChannelState (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_IC_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_OC_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_OnePulse_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_TIM_StateTypeDef\fP HAL_TIM_PWM_GetState (\fBTIM_HandleTypeDef\fP * htim)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
