.TH "TIM_Exported_Functions_Group3" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Functions_Group3 \- TIM PWM functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_PWM_Init\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_PWM_DeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PWM_MspInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "void \fBHAL_TIM_PWM_MspDeInit\fP (\fBTIM_HandleTypeDef\fP *htim)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_PWM_Start\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_PWM_Stop\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_PWM_Start_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_PWM_Stop_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_PWM_Start_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel, uint32_t *pData, uint16_t Length)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIM_PWM_Stop_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Channel)"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM PWM functions\&. 


.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_PWM_DeInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_PWM_Init (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_PWM_MspDeInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "void HAL_TIM_PWM_MspInit (\fBTIM_HandleTypeDef\fP * htim)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_PWM_Start (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_PWM_Start_DMA (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel, uint32_t * pData, uint16_t Length)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_PWM_Start_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_PWM_Stop (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_PWM_Stop_DMA (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIM_PWM_Stop_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t Channel)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
