.TH "TIMEx_Private_Functions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTIMEx_DMACommutationCplt\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.ti -1c
.RI "void \fBTIMEx_DMACommutationHalfCplt\fP (\fBDMA_HandleTypeDef\fP *hdma)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void TIMEx_DMACommutationCplt (\fBDMA_HandleTypeDef\fP * hdma)"

.SS "void TIMEx_DMACommutationHalfCplt (\fBDMA_HandleTypeDef\fP * hdma)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
