.TH "TIMEx_Exported_Functions_Group5" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Functions_Group5 \- Peripheral Control functions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigCommutEvent\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t InputTrigger, uint32_t CommutationSource)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigCommutEvent_IT\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t InputTrigger, uint32_t CommutationSource)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigCommutEvent_DMA\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t InputTrigger, uint32_t CommutationSource)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_MasterConfigSynchronization\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_MasterConfigTypeDef\fP *sMasterConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_ConfigBreakDeadTime\fP (\fBTIM_HandleTypeDef\fP *htim, \fBTIM_BreakDeadTimeConfigTypeDef\fP *sBreakDeadTimeConfig)"
.br
.ti -1c
.RI "\fBHAL_StatusTypeDef\fP \fBHAL_TIMEx_RemapConfig\fP (\fBTIM_HandleTypeDef\fP *htim, uint32_t Remap)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Peripheral Control functions\&. 


.SH "Function Documentation"
.PP 
.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_ConfigBreakDeadTime (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_BreakDeadTimeConfigTypeDef\fP * sBreakDeadTimeConfig)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_ConfigCommutEvent (\fBTIM_HandleTypeDef\fP * htim, uint32_t InputTrigger, uint32_t CommutationSource)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_ConfigCommutEvent_DMA (\fBTIM_HandleTypeDef\fP * htim, uint32_t InputTrigger, uint32_t CommutationSource)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_ConfigCommutEvent_IT (\fBTIM_HandleTypeDef\fP * htim, uint32_t InputTrigger, uint32_t CommutationSource)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_MasterConfigSynchronization (\fBTIM_HandleTypeDef\fP * htim, \fBTIM_MasterConfigTypeDef\fP * sMasterConfig)"

.SS "\fBHAL_StatusTypeDef\fP HAL_TIMEx_RemapConfig (\fBTIM_HandleTypeDef\fP * htim, uint32_t Remap)"

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
