.TH "TIMEx_Exported_Functions" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIMEx_Exported_Functions
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBExtended Timer Hall Sensor functions\fP"
.br
.RI "Timer Hall Sensor functions\&. "
.ti -1c
.RI "\fBExtended Timer Complementary Output Compare functions\fP"
.br
.RI "Timer Complementary Output Compare functions\&. "
.ti -1c
.RI "\fBExtended Timer Complementary PWM functions\fP"
.br
.RI "Timer Complementary PWM functions\&. "
.ti -1c
.RI "\fBExtended Timer Complementary One Pulse functions\fP"
.br
.RI "Timer Complementary One Pulse functions\&. "
.ti -1c
.RI "\fBExtended Peripheral Control functions\fP"
.br
.RI "Peripheral Control functions\&. "
.ti -1c
.RI "\fBExtended Callbacks functions\fP"
.br
.RI "Extended Callbacks functions\&. "
.ti -1c
.RI "\fBExtended Peripheral State functions\fP"
.br
.RI "Extended Peripheral State functions\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
