.TH "USB_TypeDef" 3 "Thu Oct 29 2020" "lcd_display" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USB_TypeDef \- Universal Serial Bus Full Speed Device\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f103x6\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint16_t \fBEP0R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBEP1R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBEP2R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBEP3R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBEP4R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBEP5R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBEP6R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBEP7R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED7\fP [17]"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCNTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED8\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBISTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVED9\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBFNR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVEDA\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBDADDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVEDB\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBBTABLE\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRESERVEDC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Universal Serial Bus Full Speed Device\&. 
.SH "Field Documentation"
.PP 
.SS "\fB__IO\fP uint16_t USB_TypeDef::BTABLE"
Buffer Table address register, Address offset: 0x50 
.SS "\fB__IO\fP uint16_t USB_TypeDef::CNTR"
Control register, Address offset: 0x40 
.SS "\fB__IO\fP uint16_t USB_TypeDef::DADDR"
Device address register, Address offset: 0x4C 
.SS "\fB__IO\fP uint16_t USB_TypeDef::EP0R"
USB Endpoint 0 register, Address offset: 0x00 
.SS "\fB__IO\fP uint16_t USB_TypeDef::EP1R"
USB Endpoint 1 register, Address offset: 0x04 
.SS "\fB__IO\fP uint16_t USB_TypeDef::EP2R"
USB Endpoint 2 register, Address offset: 0x08 
.SS "\fB__IO\fP uint16_t USB_TypeDef::EP3R"
USB Endpoint 3 register, Address offset: 0x0C 
.SS "\fB__IO\fP uint16_t USB_TypeDef::EP4R"
USB Endpoint 4 register, Address offset: 0x10 
.SS "\fB__IO\fP uint16_t USB_TypeDef::EP5R"
USB Endpoint 5 register, Address offset: 0x14 
.SS "\fB__IO\fP uint16_t USB_TypeDef::EP6R"
USB Endpoint 6 register, Address offset: 0x18 
.SS "\fB__IO\fP uint16_t USB_TypeDef::EP7R"
USB Endpoint 7 register, Address offset: 0x1C 
.SS "\fB__IO\fP uint16_t USB_TypeDef::FNR"
Frame number register, Address offset: 0x48 
.SS "\fB__IO\fP uint16_t USB_TypeDef::ISTR"
Interrupt status register, Address offset: 0x44 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED0"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED1"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED2"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED3"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED4"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED5"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED6"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED7[17]"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED8"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVED9"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVEDA"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVEDB"
Reserved 
.SS "\fB__IO\fP uint16_t USB_TypeDef::RESERVEDC"
Reserved 

.SH "Author"
.PP 
Generated automatically by Doxygen for lcd_display from the source code\&.
